// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/phm/component.art
//
// Main slice (STATEM variant) — TimerService + boot path for FCs
// where at least one node declared a `statem { ... }` block. Each
// node is started with start_statem(timers) (statem nodes) or start()
// (plain GenServer nodes), so a mixed FC — e.g. a statem core node +
// a plain message-handling node — brings up both.


#include "lib/PhmFsm.hh"
#include "lib/PhmGate.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "MachineInstance.hh"  // resolve_node_tipc(--tipc arg) — per-node addr
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386)
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
                         // watchdog — every reporting node. Hand-framed cast,
                         // no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main(int argc, char** argv) {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // --tipc=<node>=<type>:<inst>|... — per-NODE TIPC address from the command
    // line (ARG-only; supervisor appends per child, instance machine-shifted).
    // Parsed once; each node resolves its own via resolve_node_tipc() below.
    ::theia::runtime::set_node_tipc_arg(argc, argv);

    // Crash forensics: install the libtombstone fatal-signal handler before any
    // node starts, so a crash writes a tombstone to $THEIA_TOMBSTONE_DIR (set
    // per child by the supervisor) for GetTombstone / the GUI to serve.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("phm", td);
    }

    using namespace ara::phm;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map). Defaults to Info when unset. Applied
    // to every node's logger below; the SINK kind comes from THEIA_LOGGER.
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON once,
    // before any node is constructed (ctor/init() reads via get_config()).
    ::theia::runtime::init_config("phm");

    ::theia::runtime::TimerService timers;
    // Publish the process TimerService. start_statem(timers) drives the FSM's
    // own send_after, but a plain `requires_timers` node sharing this FC (e.g. a
    // poller that send_after()s its own tick) reaches the SAME service via the
    // global process_timers() accessor — which must be set, or it fatals.
    ::theia::runtime::set_process_timers(&timers);

    // Config-service receiver (#386): reporting nodes register_cast the
    // supervisor's LogLevelPush, applied by GenServer's base handler.
    ::theia::runtime::TipcMux config_mux;
    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    PhmFsm phm_fsm;
    // Per-node logger: tagged [#phm_fsm] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start so init/do_* log
    // through it; the FIRST node's logger also backs process_logger().
    {
        auto phm_fsm_log = MakeContextLogger(PhmFsm::kNodeName);
        phm_fsm_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(phm_fsm_log);
        phm_fsm.set_logger(std::move(phm_fsm_log));
    }
    phm_fsm.start_statem(timers);
    // Resolve this node’s TIPC address from the --tipc arg (the supervisor built
    // it per node from executor.json, instance machine-shifted) so the binary is
    // address-agnostic. Falls back to the compiled kTipcType/kTipcInstance for a
    // standalone run.
    uint32_t phm_fsm_type, phm_fsm_inst;
    ::theia::runtime::resolve_node_tipc(PhmFsm::kNodeName,
        PhmFsm::kTipcType, PhmFsm::kTipcInstance,
        phm_fsm_type, phm_fsm_inst);
    {
        char _tipc[96];
        std::snprintf(_tipc, sizeof(_tipc),
                      "up — TIPC type=0x%x instance=%u; statem initial=OK",
                      phm_fsm_type, phm_fsm_inst);
        phm_fsm.log().info(_tipc);
    }
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (supervisor sets it
    // from the rig's NodeToCPUMapping). No-op when unset; soft-fails on EPERM.
    ::theia::runtime::apply_node_affinity(phm_fsm.native_handle(),
        PhmFsm::kNodeName, std::getenv("THEIA_NODE_CFG"));

    if (auto* phm_fsm_cfg = config_mux.bind_node(
            phm_fsm, phm_fsm_type,
            phm_fsm_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            phm_fsm_cfg, phm_fsm);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            phm_fsm_cfg, phm_fsm);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            phm_fsm_cfg, phm_fsm);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        // PG (manual pub/sub, OTP shape): attach this statem node's PgClient to
        // its demux binding (joined-group frames + PgMembership pushes route into
        // handle_cast) + pass its bound addr as the watcher address (where the
        // supervisor casts PgMembership when this node pg_watch'es a group).
        phm_fsm.pg_attach(PhmFsm::kNodeName, phm_fsm_cfg,
                                phm_fsm_type, phm_fsm_inst);
    } else {
        phm_fsm.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }
    // Liveness beat to the supervisor watchdog (#PHM). A reporting node must
    // beat or the watchdog SIGTERMs it after K missed deadlines. One publisher
    // per node, own timer thread (1s default = the supervisor's check cadence).
    {
        auto phm_fsm_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(PhmFsm::kNodeName);
        if (phm_fsm_hb->open()) {
            phm_fsm_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(phm_fsm_hb));
        } else {
            phm_fsm.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    PhmGate phm_gate;
    // Per-node logger: tagged [#phm_gate] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start so init/do_* log
    // through it; the FIRST node's logger also backs process_logger().
    {
        auto phm_gate_log = MakeContextLogger(PhmGate::kNodeName);
        phm_gate_log->set_level(boot_level);
        phm_gate.set_logger(std::move(phm_gate_log));
    }
    phm_gate.start();
    // Resolve this node’s TIPC address from the --tipc arg (the supervisor built
    // it per node from executor.json, instance machine-shifted) so the binary is
    // address-agnostic. Falls back to the compiled kTipcType/kTipcInstance for a
    // standalone run.
    uint32_t phm_gate_type, phm_gate_inst;
    ::theia::runtime::resolve_node_tipc(PhmGate::kNodeName,
        PhmGate::kTipcType, PhmGate::kTipcInstance,
        phm_gate_type, phm_gate_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      phm_gate_type, phm_gate_inst);
        phm_gate.log().info(_tipc);
    }
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (supervisor sets it
    // from the rig's NodeToCPUMapping). No-op when unset; soft-fails on EPERM.
    ::theia::runtime::apply_node_affinity(phm_gate.native_handle(),
        PhmGate::kNodeName, std::getenv("THEIA_NODE_CFG"));

    if (auto* phm_gate_cfg = config_mux.bind_node(
            phm_gate, phm_gate_type,
            phm_gate_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            phm_gate_cfg, phm_gate);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            phm_gate_cfg, phm_gate);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            phm_gate_cfg, phm_gate);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<PhmStatusReq, PhmStatusMsg>(
            phm_gate_cfg, phm_gate);
        config_mux.register_cast<SupervisionEvent>(phm_gate_cfg, phm_gate);
        config_mux.register_cast<HeartbeatReport>(phm_gate_cfg, phm_gate);
        config_mux.register_cast<SendTimeoutReport>(phm_gate_cfg, phm_gate);
        config_mux.register_cast<PhmCheckpoint>(phm_gate_cfg, phm_gate);
        config_mux.register_cast<FcHealthReport>(phm_gate_cfg, phm_gate);
        // PG (manual pub/sub, OTP shape): attach this statem node's PgClient to
        // its demux binding (joined-group frames + PgMembership pushes route into
        // handle_cast) + pass its bound addr as the watcher address (where the
        // supervisor casts PgMembership when this node pg_watch'es a group).
        phm_gate.pg_attach(PhmGate::kNodeName, phm_gate_cfg,
                                phm_gate_type, phm_gate_inst);
    } else {
        phm_gate.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }
    // Liveness beat to the supervisor watchdog (#PHM). A reporting node must
    // beat or the watchdog SIGTERMs it after K missed deadlines. One publisher
    // per node, own timer thread (1s default = the supervisor's check cadence).
    {
        auto phm_gate_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(PhmGate::kNodeName);
        if (phm_gate_hb->open()) {
            phm_gate_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(phm_gate_hb));
        } else {
            phm_gate.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    phm_fsm.stop("signal");

    phm_gate.stop("signal");

    return 0;
}
