// AUTO-GENERATED by `artheia gen-fc` — DO NOT EDIT.
// source: system/services/ucm/package.art
//
// FC-wide inbound RemoteCodec specializations (#387).
//
// register_call / register_cast on a reporting node's config service
// need a RemoteCodec<T> for every inbound type. This header declares
// ONE THEIA_DECLARE_REMOTE_CODEC per inbound (receiver-port data /
// server-op req+rep) type, deduplicated across EVERY node in the FC.
//
// It lives in one header — not per-node — so that when two nodes in
// the same FC share an inbound type (e.g. com's ComDaemon and the
// test ProbeDaemon both take ComEmpty), the codec specialization is
// declared exactly once even though main.cc includes both node
// headers. Each node header #includes this (guarded by #pragma once),
// so a node header used standalone still has its codecs.
//
// A codec keys its service_id on the proto type name in the message's
// DEFINING package — so an inbound type imported from another package
// (e.g. a PSP bus PDU) declares its codec under that package's name,
// matching the sender. The #include set below covers every defining
// package an inbound type comes from.

#pragma once

#include "RemoteCodec.hh"   // THEIA_DECLARE_REMOTE_CODEC
#include "system/services/ucm/ucm.pb.h"

#include "system/services/phm/phm.pb.h"



#ifndef THEIA_CODEC_system_services_ucm_UcmProgress
#define THEIA_CODEC_system_services_ucm_UcmProgress
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_UcmProgress)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvStartUpdate
#define THEIA_CODEC_system_services_ucm_EvStartUpdate
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvStartUpdate)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvDownloaded
#define THEIA_CODEC_system_services_ucm_EvDownloaded
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvDownloaded)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvValidated
#define THEIA_CODEC_system_services_ucm_EvValidated
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvValidated)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvStaged
#define THEIA_CODEC_system_services_ucm_EvStaged
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvStaged)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvInstalled
#define THEIA_CODEC_system_services_ucm_EvInstalled
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvInstalled)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvRestarted
#define THEIA_CODEC_system_services_ucm_EvRestarted
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvRestarted)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvVerified
#define THEIA_CODEC_system_services_ucm_EvVerified
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvVerified)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvProvisional
#define THEIA_CODEC_system_services_ucm_EvProvisional
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvProvisional)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvConfirmed
#define THEIA_CODEC_system_services_ucm_EvConfirmed
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvConfirmed)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvFailed
#define THEIA_CODEC_system_services_ucm_EvFailed
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvFailed)
#endif
#ifndef THEIA_CODEC_system_services_ucm_EvRolledBack
#define THEIA_CODEC_system_services_ucm_EvRolledBack
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_EvRolledBack)
#endif
#ifndef THEIA_CODEC_system_services_phm_PhmHealthStatus
#define THEIA_CODEC_system_services_phm_PhmHealthStatus
THEIA_DECLARE_REMOTE_CODEC(system_services_phm_PhmHealthStatus)
#endif
#ifndef THEIA_CODEC_system_services_ucm_PackageManifest
#define THEIA_CODEC_system_services_ucm_PackageManifest
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_PackageManifest)
#endif
#ifndef THEIA_CODEC_system_services_ucm_UcmReply
#define THEIA_CODEC_system_services_ucm_UcmReply
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_UcmReply)
#endif
#ifndef THEIA_CODEC_system_services_ucm_ConfirmRequest
#define THEIA_CODEC_system_services_ucm_ConfirmRequest
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_ConfirmRequest)
#endif
#ifndef THEIA_CODEC_system_services_ucm_CancelRequest
#define THEIA_CODEC_system_services_ucm_CancelRequest
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_CancelRequest)
#endif

// FC-wide enum aliases — the enum TYPE and each VALUE inside the FC namespace, so
// impl code writes the readable `UpdateKind` / `UK_SOFTWARE`
// instead of nanopb's double-prefixed name
// (system_services_ucm_<Enum>_<Enum>_<VALUE>). Emitted ONCE here (this header
// is #pragma once + included by every node header) — NOT per-node, so two node
// headers in one TU don't redefine them.
namespace ara::ucm {
using UpdateKind = system_services_ucm_UpdateKind;
inline constexpr UpdateKind UK_SOFTWARE = system_services_ucm_UpdateKind_UpdateKind_UK_SOFTWARE;
inline constexpr UpdateKind UK_CONFIG = system_services_ucm_UpdateKind_UpdateKind_UK_CONFIG;
using UpdateScope = system_services_ucm_UpdateScope;
inline constexpr UpdateScope US_FULL = system_services_ucm_UpdateScope_UpdateScope_US_FULL;
inline constexpr UpdateScope US_PARTIAL = system_services_ucm_UpdateScope_UpdateScope_US_PARTIAL;
using UcmState = system_services_ucm_UcmState;
inline constexpr UcmState IDLE = system_services_ucm_UcmState_UcmState_IDLE;
inline constexpr UcmState DOWNLOADED = system_services_ucm_UcmState_UcmState_DOWNLOADED;
inline constexpr UcmState VALIDATED = system_services_ucm_UcmState_UcmState_VALIDATED;
inline constexpr UcmState STAGED = system_services_ucm_UcmState_UcmState_STAGED;
inline constexpr UcmState INSTALLING = system_services_ucm_UcmState_UcmState_INSTALLING;
inline constexpr UcmState RESTARTING = system_services_ucm_UcmState_UcmState_RESTARTING;
inline constexpr UcmState VERIFYING = system_services_ucm_UcmState_UcmState_VERIFYING;
inline constexpr UcmState ACTIVE = system_services_ucm_UcmState_UcmState_ACTIVE;
inline constexpr UcmState ROLLBACK = system_services_ucm_UcmState_UcmState_ROLLBACK;
inline constexpr UcmState PROVISIONAL = system_services_ucm_UcmState_UcmState_PROVISIONAL;
using ActivationState = system_services_ucm_ActivationState;
inline constexpr ActivationState ACT_NONE = system_services_ucm_ActivationState_ActivationState_ACT_NONE;
inline constexpr ActivationState ACT_PROVISIONAL = system_services_ucm_ActivationState_ActivationState_ACT_PROVISIONAL;
inline constexpr ActivationState ACT_CONFIRMED = system_services_ucm_ActivationState_ActivationState_ACT_CONFIRMED;
}  // namespace ara::ucm
