// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/apps/v2v_app/component.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "packages/meshtastic/lib/Meshtastic.hh"   // imported package node — links via bazel dep
#include "packages/v2v/lib/OsiV2v.hh"   // imported package node — links via bazel dep

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "MachineInstance.hh"  // resolve_node_tipc(--tipc arg) — per-node addr
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386).
                         // GenServer nodes use bind_node + register_cast;
                         // reporting runnables use bind_listener +
                         // register_cast_inline (no mailbox).
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
#include "PgClient.hh"            // process-group join/watch (broadcast fan-out)
                         // watchdog — every reporting node (GenServer AND
                         // runnable). Hand-framed cast, no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main(int argc, char** argv) {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // --tipc=<node>=<type>:<inst>|... — per-NODE TIPC address from the command
    // line (ARG-only; the supervisor appends it per child, instance machine-
    // shifted). Parse it once; each node below resolves its own address via
    // resolve_node_tipc(), falling back to its compiled .art address when absent
    // (a bare / un-supervised run binds the declared instance 0 — host-dev).
    ::theia::runtime::set_node_tipc_arg(argc, argv);

    // Crash forensics: install the libtombstone fatal-signal handler BEFORE any
    // node starts, so a SIGSEGV/SIGABRT/etc — even during startup — writes a
    // tombstone (backtrace + maps) to $THEIA_TOMBSTONE_DIR (the supervisor sets
    // it per child). The supervisor's GetTombstone serves it back (GUI
    // "Download tombstone"). No dir set (standalone run) → handler not armed.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("v2v_app", td);
    }

    using namespace ara::v2v_app;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map, sourced from Process.log_level on the
    // rig). Defaults to Info when unset/unparseable. Applied to every node's
    // logger below. The SINK kind comes from THEIA_LOGGER (MakeContextLogger).
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON ONCE,
    // before any node is constructed, so a node's ctor / init() can read its
    // knobs via ::theia::runtime::get_config().node(kNodeName).u32(...). A
    // missing file is fine — every lookup falls back to the caller's default.
    // Path from $THEIA_CONFIG / $THEIA_CONFIG_DIR / ./config/v2v_app.json.
    ::theia::runtime::init_config("v2v_app");

    ::theia::runtime::TimerService timers;
    // Publish the process TimerService so a `requires_timers` node's
    // handlers / init() reach it via process_timers() — mirrors
    // set_process_logger above. Set once, before any node starts.
    ::theia::runtime::set_process_timers(&timers);

    // Config-service receiver (#386). A reporting node binds its TIPC name
    // and registers the supervisor's control pushes. A GenServer node's cast
    // lands in its base handle_cast on the node thread; a reporting runnable
    // (no mailbox) takes them INLINE on the mux thread (register_cast_inline).
    // Same standard GwMessageHeader path as any app message — no bespoke frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);

    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below. The supervisor watchdog only watches nodes that
    // beat, so non-reporting nodes simply never appear here.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    ara::meshtastic::Meshtastic mesh;
    // Per-node logger: tagged [#mesh] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto mesh_log = MakeContextLogger(ara::meshtastic::Meshtastic::kNodeName);
        mesh_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(mesh_log);
        mesh.set_logger(std::move(mesh_log));
    }
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run. Done BEFORE
    // start() so the node's init() — which runs on the node thread right after
    // start() — sees its own instance via tipc_instance() (a clone that keys its
    // per-instance config in init() would otherwise race and read 0).
    uint32_t mesh_type, mesh_inst;
    ::theia::runtime::resolve_node_tipc(ara::meshtastic::Meshtastic::kNodeName,
        ara::meshtastic::Meshtastic::kTipcType, ara::meshtastic::Meshtastic::kTipcInstance,
        mesh_type, mesh_inst);
    // Generic node params (read via the static-deploy ParamsConfig, overridable
    // per-rig in config/<fc>.json under this node's section — same mechanism as
    // tsync's prebuilt `enabled`):
    //   enabled          (default true)  — boot gate; a disabled node does NOT
    //                     start, freeing its TIPC slot (e.g. a probe replaces it).
    //   start_delay_ms   (default 0)     — deterministic intra-executable ordering.
    // A node section may be absent entirely → all defaults apply (start normally).
    const auto mesh_params =
        ::theia::runtime::get_config().node(ara::meshtastic::Meshtastic::kNodeName);
    const bool mesh_enabled = mesh_params.boolean("enabled", true);
    if (!mesh_enabled) {
        mesh.log().info("node disabled (params.enabled=false) — not "
            "started; its TIPC address is free for a test/probe to bind");
    } else {
    if (auto mesh_delay = mesh_params.u32("start_delay_ms", 0))
        std::this_thread::sleep_for(std::chrono::milliseconds(mesh_delay));
    mesh.start();
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      mesh_type, mesh_inst);
        mesh.log().info(_tipc);
    }
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(mesh.native_handle(),
        ara::meshtastic::Meshtastic::kNodeName, std::getenv("THEIA_NODE_CFG"));


    // GenRunnable has no mailbox, so it can't take the supervisor's control
    // pushes via the GenServer handle_cast/mailbox path. Bind a listener and
    // register the LogLevelPush / TraceControlPush INLINE — the mux dispatch
    // thread applies them directly (on_log_level_push / on_trace_control_push,
    // touching only atomics). This is what makes a runnable's log level + trace
    // live-controllable (`tdb loglevel`/`trace <node>`), same as a gen_server.
    if (auto* mesh_cfg = config_mux.bind_listener(
            mesh_type, mesh_inst)) {
        config_mux.register_cast_inline<platform_runtime_LogLevelPush>(
            mesh_cfg, mesh, &ara::meshtastic::Meshtastic::on_log_level_push);
        config_mux.register_cast_inline<platform_runtime_TraceControlPush>(
            mesh_cfg, mesh, &ara::meshtastic::Meshtastic::on_trace_control_push);
    } else {
        mesh.log().warn("config service bind failed; live log-level "
                                 "push disabled");
    }


    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto mesh_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(ara::meshtastic::Meshtastic::kNodeName);
        if (mesh_hb->open()) {
            mesh_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(mesh_hb));
        } else {
            mesh.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }

    }  // end if (mesh_enabled)

    ara::v2v::OsiV2v v2v;
    // Per-node logger: tagged [#v2v] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto v2v_log = MakeContextLogger(ara::v2v::OsiV2v::kNodeName);
        v2v_log->set_level(boot_level);
        v2v.set_logger(std::move(v2v_log));
    }
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run. Done BEFORE
    // start() so the node's init() — which runs on the node thread right after
    // start() — sees its own instance via tipc_instance() (a clone that keys its
    // per-instance config in init() would otherwise race and read 0).
    uint32_t v2v_type, v2v_inst;
    ::theia::runtime::resolve_node_tipc(ara::v2v::OsiV2v::kNodeName,
        ara::v2v::OsiV2v::kTipcType, ara::v2v::OsiV2v::kTipcInstance,
        v2v_type, v2v_inst);
    // set_tipc_instance() is a GenServer method (a runnable resolves its own
    // instance in do_start via resolve_node_tipc); only emit it for gen_server/
    // statem nodes so init() sees its instance before start().
    v2v.set_tipc_instance(v2v_inst);
    // Generic node params (read via the static-deploy ParamsConfig, overridable
    // per-rig in config/<fc>.json under this node's section — same mechanism as
    // tsync's prebuilt `enabled`):
    //   enabled          (default true)  — boot gate; a disabled node does NOT
    //                     start, freeing its TIPC slot (e.g. a probe replaces it).
    //   start_delay_ms   (default 0)     — deterministic intra-executable ordering.
    // A node section may be absent entirely → all defaults apply (start normally).
    const auto v2v_params =
        ::theia::runtime::get_config().node(ara::v2v::OsiV2v::kNodeName);
    const bool v2v_enabled = v2v_params.boolean("enabled", true);
    if (!v2v_enabled) {
        v2v.log().info("node disabled (params.enabled=false) — not "
            "started; its TIPC address is free for a test/probe to bind");
    } else {
    if (auto v2v_delay = v2v_params.u32("start_delay_ms", 0))
        std::this_thread::sleep_for(std::chrono::milliseconds(v2v_delay));
    v2v.start();
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      v2v_type, v2v_inst);
        v2v.log().info(_tipc);
    }
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(v2v.native_handle(),
        ara::v2v::OsiV2v::kNodeName, std::getenv("THEIA_NODE_CFG"));

    if (auto* v2v_cfg = config_mux.bind_node(
            v2v, v2v_type,
            v2v_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            v2v_cfg, v2v);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            v2v_cfg, v2v);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            v2v_cfg, v2v);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<ara::v2v::GetConstellationReq, ara::v2v::ConstellationUpdate>(
            v2v_cfg, v2v);
        config_mux.register_call<ara::v2v::GetAlertDecisionReq, ara::v2v::AlertDecision>(
            v2v_cfg, v2v);
        config_mux.register_call<ara::v2v::InjectBeaconReq, ara::v2v::InjectBeaconReply>(
            v2v_cfg, v2v);
        config_mux.register_cast<ara::v2v::Beacon>(v2v_cfg, v2v);
        // ---- process groups (pg): MANUAL pub/sub control (OTP pg shape) ----
        // The node OWNS its membership: pg_join<T>() to CONSUME a group,
        // pg_watch<T>()/broadcast_*() to PRODUCE, pg_leave<T>() to stop — from its
        // OWN logic (init()/handlers), never automatically here. We ATTACH the
        // node's PgClient to its demux binding (so a joined group's frames + the
        // supervisor's PgMembership pushes route into handle_cast) and pass its
        // BOUND ADDRESS as the watcher address — where the supervisor casts
        // PgMembership when this node pg_watch'es a group it produces to.
        v2v.pg_attach(ara::v2v::OsiV2v::kNodeName, v2v_cfg,
                                v2v_type, v2v_inst);
    } else {
        v2v.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto v2v_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(ara::v2v::OsiV2v::kNodeName);
        if (v2v_hb->open()) {
            v2v_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(v2v_hb));
        } else {
            v2v.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }

    }  // end if (v2v_enabled)


    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    mesh.stop("signal");

    v2v.stop("signal");

    return 0;
}
