// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/osi/component.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/OsiCtl.hh"
#include "lib/OsiV2v.hh"
#include "lib/Meshtastic.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "MachineInstance.hh"  // resolve_node_tipc(--tipc arg) — per-node addr
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386).
                         // GenServer nodes use bind_node + register_cast;
                         // reporting runnables use bind_listener +
                         // register_cast_inline (no mailbox).
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
#include "PgClient.hh"            // process-group join/watch (broadcast fan-out)
                         // watchdog — every reporting node (GenServer AND
                         // runnable). Hand-framed cast, no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main(int argc, char** argv) {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // --tipc=<node>=<type>:<inst>|... — per-NODE TIPC address from the command
    // line (ARG-only; the supervisor appends it per child, instance machine-
    // shifted). Parse it once; each node below resolves its own address via
    // resolve_node_tipc(), falling back to its compiled .art address when absent
    // (a bare / un-supervised run binds the declared instance 0 — host-dev).
    ::theia::runtime::set_node_tipc_arg(argc, argv);

    // Crash forensics: install the libtombstone fatal-signal handler BEFORE any
    // node starts, so a SIGSEGV/SIGABRT/etc — even during startup — writes a
    // tombstone (backtrace + maps) to $THEIA_TOMBSTONE_DIR (the supervisor sets
    // it per child). The supervisor's GetTombstone serves it back (GUI
    // "Download tombstone"). No dir set (standalone run) → handler not armed.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("osi", td);
    }

    using namespace ara::osi;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map, sourced from Process.log_level on the
    // rig). Defaults to Info when unset/unparseable. Applied to every node's
    // logger below. The SINK kind comes from THEIA_LOGGER (MakeContextLogger).
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON ONCE,
    // before any node is constructed, so a node's ctor / init() can read its
    // knobs via ::theia::runtime::get_config().node(kNodeName).u32(...). A
    // missing file is fine — every lookup falls back to the caller's default.
    // Path from $THEIA_CONFIG / $THEIA_CONFIG_DIR / ./config/osi.json.
    ::theia::runtime::init_config("osi");

    ::theia::runtime::TimerService timers;
    // Publish the process TimerService so a `requires_timers` node's
    // handlers / init() reach it via process_timers() — mirrors
    // set_process_logger above. Set once, before any node starts.
    ::theia::runtime::set_process_timers(&timers);

    // Config-service receiver (#386). A reporting node binds its TIPC name
    // and registers the supervisor's control pushes. A GenServer node's cast
    // lands in its base handle_cast on the node thread; a reporting runnable
    // (no mailbox) takes them INLINE on the mux thread (register_cast_inline).
    // Same standard GwMessageHeader path as any app message — no bespoke frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);

    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below. The supervisor watchdog only watches nodes that
    // beat, so non-reporting nodes simply never appear here.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    OsiCtl osi_ctl;
    // Per-node logger: tagged [#osi_ctl] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto osi_ctl_log = MakeContextLogger(OsiCtl::kNodeName);
        osi_ctl_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(osi_ctl_log);
        osi_ctl.set_logger(std::move(osi_ctl_log));
    }
    osi_ctl.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(osi_ctl.native_handle(),
        OsiCtl::kNodeName, std::getenv("THEIA_NODE_CFG"));
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run.
    uint32_t osi_ctl_type, osi_ctl_inst;
    ::theia::runtime::resolve_node_tipc(OsiCtl::kNodeName,
        OsiCtl::kTipcType, OsiCtl::kTipcInstance,
        osi_ctl_type, osi_ctl_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      osi_ctl_type, osi_ctl_inst);
        osi_ctl.log().info(_tipc);
    }

    if (auto* osi_ctl_cfg = config_mux.bind_node(
            osi_ctl, osi_ctl_type,
            osi_ctl_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            osi_ctl_cfg, osi_ctl);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            osi_ctl_cfg, osi_ctl);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            osi_ctl_cfg, osi_ctl);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<ResourceStatusReq, ResourceStatus>(
            osi_ctl_cfg, osi_ctl);
        config_mux.register_call<ResourceLimitReq, ResourceLimitReply>(
            osi_ctl_cfg, osi_ctl);
        // ---- process groups (pg): MANUAL pub/sub control (OTP pg shape) ----
        // The node OWNS its membership: pg_join<T>() to CONSUME a group,
        // pg_watch<T>()/broadcast_*() to PRODUCE, pg_leave<T>() to stop — from its
        // OWN logic (init()/handlers), never automatically here. We ATTACH the
        // node's PgClient to its demux binding (so a joined group's frames + the
        // supervisor's PgMembership pushes route into handle_cast) and pass its
        // BOUND ADDRESS as the watcher address — where the supervisor casts
        // PgMembership when this node pg_watch'es a group it produces to.
        osi_ctl.pg_attach(OsiCtl::kNodeName, osi_ctl_cfg,
                                osi_ctl_type, osi_ctl_inst);
    } else {
        osi_ctl.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto osi_ctl_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(OsiCtl::kNodeName);
        if (osi_ctl_hb->open()) {
            osi_ctl_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(osi_ctl_hb));
        } else {
            osi_ctl.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    OsiV2v osi_v2v;
    // Per-node logger: tagged [#osi_v2v] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto osi_v2v_log = MakeContextLogger(OsiV2v::kNodeName);
        osi_v2v_log->set_level(boot_level);
        osi_v2v.set_logger(std::move(osi_v2v_log));
    }
    osi_v2v.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(osi_v2v.native_handle(),
        OsiV2v::kNodeName, std::getenv("THEIA_NODE_CFG"));
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run.
    uint32_t osi_v2v_type, osi_v2v_inst;
    ::theia::runtime::resolve_node_tipc(OsiV2v::kNodeName,
        OsiV2v::kTipcType, OsiV2v::kTipcInstance,
        osi_v2v_type, osi_v2v_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      osi_v2v_type, osi_v2v_inst);
        osi_v2v.log().info(_tipc);
    }

    if (auto* osi_v2v_cfg = config_mux.bind_node(
            osi_v2v, osi_v2v_type,
            osi_v2v_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            osi_v2v_cfg, osi_v2v);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            osi_v2v_cfg, osi_v2v);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            osi_v2v_cfg, osi_v2v);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<GetConstellationReq, ConstellationUpdate>(
            osi_v2v_cfg, osi_v2v);
        config_mux.register_call<GetAlertDecisionReq, AlertDecision>(
            osi_v2v_cfg, osi_v2v);
        config_mux.register_call<InjectBeaconReq, InjectBeaconReply>(
            osi_v2v_cfg, osi_v2v);
        config_mux.register_cast<Beacon>(osi_v2v_cfg, osi_v2v);
        // ---- process groups (pg): MANUAL pub/sub control (OTP pg shape) ----
        // The node OWNS its membership: pg_join<T>() to CONSUME a group,
        // pg_watch<T>()/broadcast_*() to PRODUCE, pg_leave<T>() to stop — from its
        // OWN logic (init()/handlers), never automatically here. We ATTACH the
        // node's PgClient to its demux binding (so a joined group's frames + the
        // supervisor's PgMembership pushes route into handle_cast) and pass its
        // BOUND ADDRESS as the watcher address — where the supervisor casts
        // PgMembership when this node pg_watch'es a group it produces to.
        osi_v2v.pg_attach(OsiV2v::kNodeName, osi_v2v_cfg,
                                osi_v2v_type, osi_v2v_inst);
    } else {
        osi_v2v.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto osi_v2v_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(OsiV2v::kNodeName);
        if (osi_v2v_hb->open()) {
            osi_v2v_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(osi_v2v_hb));
        } else {
            osi_v2v.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    Meshtastic meshtastic;
    // Per-node logger: tagged [#meshtastic] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto meshtastic_log = MakeContextLogger(Meshtastic::kNodeName);
        meshtastic_log->set_level(boot_level);
        meshtastic.set_logger(std::move(meshtastic_log));
    }
    meshtastic.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(meshtastic.native_handle(),
        Meshtastic::kNodeName, std::getenv("THEIA_NODE_CFG"));
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run.
    uint32_t meshtastic_type, meshtastic_inst;
    ::theia::runtime::resolve_node_tipc(Meshtastic::kNodeName,
        Meshtastic::kTipcType, Meshtastic::kTipcInstance,
        meshtastic_type, meshtastic_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      meshtastic_type, meshtastic_inst);
        meshtastic.log().info(_tipc);
    }


    // GenRunnable has no mailbox, so it can't take the supervisor's control
    // pushes via the GenServer handle_cast/mailbox path. Bind a listener and
    // register the LogLevelPush / TraceControlPush INLINE — the mux dispatch
    // thread applies them directly (on_log_level_push / on_trace_control_push,
    // touching only atomics). This is what makes a runnable's log level + trace
    // live-controllable (`tdb loglevel`/`trace <node>`), same as a gen_server.
    if (auto* meshtastic_cfg = config_mux.bind_listener(
            meshtastic_type, meshtastic_inst)) {
        config_mux.register_cast_inline<platform_runtime_LogLevelPush>(
            meshtastic_cfg, meshtastic, &Meshtastic::on_log_level_push);
        config_mux.register_cast_inline<platform_runtime_TraceControlPush>(
            meshtastic_cfg, meshtastic, &Meshtastic::on_trace_control_push);
    } else {
        meshtastic.log().warn("config service bind failed; live log-level "
                                 "push disabled");
    }


    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto meshtastic_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(Meshtastic::kNodeName);
        if (meshtastic_hb->open()) {
            meshtastic_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(meshtastic_hb));
        } else {
            meshtastic.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    osi_ctl.stop("signal");

    osi_v2v.stop("signal");

    meshtastic.stop("signal");

    return 0;
}
