// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/ucm/component.art
//
// Main slice (STATEM variant) — TimerService + boot path for FCs
// where at least one node declared a `statem { ... }` block. Each
// node is started with start_statem(timers) (statem nodes) or start()
// (plain GenServer nodes), so a mixed FC — e.g. a statem core node +
// a plain message-handling node — brings up both.


#include "lib/UcmFsm.hh"
#include "lib/UcmGate.hh"
#include "lib/UcmDaemon.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "MachineInstance.hh"  // resolve_node_tipc(--tipc arg) — per-node addr
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386)
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
                         // watchdog — every reporting node. Hand-framed cast,
                         // no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main(int argc, char** argv) {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // --tipc=<node>=<type>:<inst>|... — per-NODE TIPC address from the command
    // line (ARG-only; supervisor appends per child, instance machine-shifted).
    // Parsed once; each node resolves its own via resolve_node_tipc() below.
    ::theia::runtime::set_node_tipc_arg(argc, argv);

    // Crash forensics: install the libtombstone fatal-signal handler before any
    // node starts, so a crash writes a tombstone to $THEIA_TOMBSTONE_DIR (set
    // per child by the supervisor) for GetTombstone / the GUI to serve.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("ucm", td);
    }

    using namespace ara::ucm;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map). Defaults to Info when unset. Applied
    // to every node's logger below; the SINK kind comes from THEIA_LOGGER.
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON once,
    // before any node is constructed (ctor/init() reads via get_config()).
    ::theia::runtime::init_config("ucm");

    ::theia::runtime::TimerService timers;
    // Publish the process TimerService. start_statem(timers) drives the FSM's
    // own send_after, but a plain `requires_timers` node sharing this FC (e.g. a
    // poller that send_after()s its own tick) reaches the SAME service via the
    // global process_timers() accessor — which must be set, or it fatals.
    ::theia::runtime::set_process_timers(&timers);

    // Config-service receiver (#386): reporting nodes register_cast the
    // supervisor's LogLevelPush, applied by GenServer's base handler.
    ::theia::runtime::TipcMux config_mux;
    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    UcmFsm ucm_fsm;
    // Per-node logger: tagged [#ucm_fsm] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start so init/do_* log
    // through it; the FIRST node's logger also backs process_logger().
    {
        auto ucm_fsm_log = MakeContextLogger(UcmFsm::kNodeName);
        ucm_fsm_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(ucm_fsm_log);
        ucm_fsm.set_logger(std::move(ucm_fsm_log));
    }
    ucm_fsm.start_statem(timers);
    // Resolve this node’s TIPC address from the --tipc arg (the supervisor built
    // it per node from executor.json, instance machine-shifted) so the binary is
    // address-agnostic. Falls back to the compiled kTipcType/kTipcInstance for a
    // standalone run.
    uint32_t ucm_fsm_type, ucm_fsm_inst;
    ::theia::runtime::resolve_node_tipc(UcmFsm::kNodeName,
        UcmFsm::kTipcType, UcmFsm::kTipcInstance,
        ucm_fsm_type, ucm_fsm_inst);
    {
        char _tipc[96];
        std::snprintf(_tipc, sizeof(_tipc),
                      "up — TIPC type=0x%x instance=%u; statem initial=IDLE",
                      ucm_fsm_type, ucm_fsm_inst);
        ucm_fsm.log().info(_tipc);
    }
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (supervisor sets it
    // from the rig's NodeToCPUMapping). No-op when unset; soft-fails on EPERM.
    ::theia::runtime::apply_node_affinity(ucm_fsm.native_handle(),
        UcmFsm::kNodeName, std::getenv("THEIA_NODE_CFG"));

    if (auto* ucm_fsm_cfg = config_mux.bind_node(
            ucm_fsm, ucm_fsm_type,
            ucm_fsm_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            ucm_fsm_cfg, ucm_fsm);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            ucm_fsm_cfg, ucm_fsm);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            ucm_fsm_cfg, ucm_fsm);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        // PG (manual pub/sub): attach this statem node's PgClient to its demux
        // binding so a joined group's multicast datagrams route into its normal
        // handle_cast (register_cast above). The node pg_join<T>()s from init().
        ucm_fsm.pg_attach(UcmFsm::kNodeName, ucm_fsm_cfg);
    } else {
        ucm_fsm.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }
    // Liveness beat to the supervisor watchdog (#PHM). A reporting node must
    // beat or the watchdog SIGTERMs it after K missed deadlines. One publisher
    // per node, own timer thread (1s default = the supervisor's check cadence).
    {
        auto ucm_fsm_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(UcmFsm::kNodeName);
        if (ucm_fsm_hb->open()) {
            ucm_fsm_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(ucm_fsm_hb));
        } else {
            ucm_fsm.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    UcmGate ucm_gate;
    // Per-node logger: tagged [#ucm_gate] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start so init/do_* log
    // through it; the FIRST node's logger also backs process_logger().
    {
        auto ucm_gate_log = MakeContextLogger(UcmGate::kNodeName);
        ucm_gate_log->set_level(boot_level);
        ucm_gate.set_logger(std::move(ucm_gate_log));
    }
    ucm_gate.start();
    // Resolve this node’s TIPC address from the --tipc arg (the supervisor built
    // it per node from executor.json, instance machine-shifted) so the binary is
    // address-agnostic. Falls back to the compiled kTipcType/kTipcInstance for a
    // standalone run.
    uint32_t ucm_gate_type, ucm_gate_inst;
    ::theia::runtime::resolve_node_tipc(UcmGate::kNodeName,
        UcmGate::kTipcType, UcmGate::kTipcInstance,
        ucm_gate_type, ucm_gate_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      ucm_gate_type, ucm_gate_inst);
        ucm_gate.log().info(_tipc);
    }
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (supervisor sets it
    // from the rig's NodeToCPUMapping). No-op when unset; soft-fails on EPERM.
    ::theia::runtime::apply_node_affinity(ucm_gate.native_handle(),
        UcmGate::kNodeName, std::getenv("THEIA_NODE_CFG"));

    if (auto* ucm_gate_cfg = config_mux.bind_node(
            ucm_gate, ucm_gate_type,
            ucm_gate_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            ucm_gate_cfg, ucm_gate);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            ucm_gate_cfg, ucm_gate);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            ucm_gate_cfg, ucm_gate);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_cast<EvStartUpdate>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvDownloaded>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvValidated>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvStaged>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvInstalled>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvRestarted>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvVerified>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvFailed>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<EvRolledBack>(ucm_gate_cfg, ucm_gate);
        config_mux.register_cast<PhmHealthStatus>(ucm_gate_cfg, ucm_gate);
        // PG (manual pub/sub): attach this statem node's PgClient to its demux
        // binding so a joined group's multicast datagrams route into its normal
        // handle_cast (register_cast above). The node pg_join<T>()s from init().
        ucm_gate.pg_attach(UcmGate::kNodeName, ucm_gate_cfg);
    } else {
        ucm_gate.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }
    // Liveness beat to the supervisor watchdog (#PHM). A reporting node must
    // beat or the watchdog SIGTERMs it after K missed deadlines. One publisher
    // per node, own timer thread (1s default = the supervisor's check cadence).
    {
        auto ucm_gate_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(UcmGate::kNodeName);
        if (ucm_gate_hb->open()) {
            ucm_gate_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(ucm_gate_hb));
        } else {
            ucm_gate.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    UcmDaemon ucm_daemon;
    // Per-node logger: tagged [#ucm_daemon] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start so init/do_* log
    // through it; the FIRST node's logger also backs process_logger().
    {
        auto ucm_daemon_log = MakeContextLogger(UcmDaemon::kNodeName);
        ucm_daemon_log->set_level(boot_level);
        ucm_daemon.set_logger(std::move(ucm_daemon_log));
    }
    ucm_daemon.start();
    // Resolve this node’s TIPC address from the --tipc arg (the supervisor built
    // it per node from executor.json, instance machine-shifted) so the binary is
    // address-agnostic. Falls back to the compiled kTipcType/kTipcInstance for a
    // standalone run.
    uint32_t ucm_daemon_type, ucm_daemon_inst;
    ::theia::runtime::resolve_node_tipc(UcmDaemon::kNodeName,
        UcmDaemon::kTipcType, UcmDaemon::kTipcInstance,
        ucm_daemon_type, ucm_daemon_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      ucm_daemon_type, ucm_daemon_inst);
        ucm_daemon.log().info(_tipc);
    }
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (supervisor sets it
    // from the rig's NodeToCPUMapping). No-op when unset; soft-fails on EPERM.
    ::theia::runtime::apply_node_affinity(ucm_daemon.native_handle(),
        UcmDaemon::kNodeName, std::getenv("THEIA_NODE_CFG"));

    if (auto* ucm_daemon_cfg = config_mux.bind_node(
            ucm_daemon, ucm_daemon_type,
            ucm_daemon_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            ucm_daemon_cfg, ucm_daemon);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            ucm_daemon_cfg, ucm_daemon);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            ucm_daemon_cfg, ucm_daemon);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<PackageManifest, UcmReply>(
            ucm_daemon_cfg, ucm_daemon);
        // PG (manual pub/sub): attach this statem node's PgClient to its demux
        // binding so a joined group's multicast datagrams route into its normal
        // handle_cast (register_cast above). The node pg_join<T>()s from init().
        ucm_daemon.pg_attach(UcmDaemon::kNodeName, ucm_daemon_cfg);
    } else {
        ucm_daemon.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }
    // Liveness beat to the supervisor watchdog (#PHM). A reporting node must
    // beat or the watchdog SIGTERMs it after K missed deadlines. One publisher
    // per node, own timer thread (1s default = the supervisor's check cadence).
    {
        auto ucm_daemon_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(UcmDaemon::kNodeName);
        if (ucm_daemon_hb->open()) {
            ucm_daemon_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(ucm_daemon_hb));
        } else {
            ucm_daemon.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    ucm_fsm.stop("signal");

    ucm_gate.stop("signal");

    ucm_daemon.stop("signal");

    return 0;
}
