// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/ucm/system/ucm/package.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/UcmDaemon.hh"

#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / MakeContextLogger / process_logger

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386)


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    using namespace ara::ucm;

    // Process-wide logger. Pick up THEIA_LOG_LEVEL from the env
    // (supervisor sets it from executor.json's per-child env map,
    // sourced from Process.log_level on the rig). Defaults to Info
    // when unset or unparseable. set_process_logger publishes it so a
    // reporting node's config service can apply a live ConfigureLogLevel
    // push (#386) via process_logger().set_level on the node thread.
    auto logger = MakeContextLogger();
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        logger->set_level(::theia::runtime::parse_log_level(lvl));
    }
    ::theia::runtime::set_process_logger(logger);
    (void)logger;  // available for user handlers via RuntimeContext

    ::theia::runtime::TimerService timers;
    (void)timers;  // no node requires_timers

    // Config-service receiver (#386). A reporting node binds its TIPC
    // name and register_cast's the supervisor's control push; the cast
    // lands in GenServer's base handle_cast(LogLevelPush) on the node
    // thread. Same standard GwMessageHeader path as any app message —
    // no bespoke control frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);


    UcmDaemon ucm_daemon;
    ucm_daemon.start();
    std::fprintf(stderr, "[ucm_daemon] up — TIPC type=0x%x instance=%u\n",
                 UcmDaemon::kTipcType, UcmDaemon::kTipcInstance);

    if (auto* ucm_daemon_cfg = config_mux.bind_node(
            ucm_daemon, UcmDaemon::kTipcType,
            UcmDaemon::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            ucm_daemon_cfg, ucm_daemon);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            ucm_daemon_cfg, ucm_daemon);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<UcmRequest, UcmReply>(
            ucm_daemon_cfg, ucm_daemon);
    } else {
        std::fprintf(stderr,
                     "[ucm_daemon] WARN: config service bind failed; "
                     "live log-level push + signal inject disabled\n");
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    ucm_daemon.stop("signal");

    return 0;
}
