// AUTO-GENERATED by `artheia gen-transform` — DO NOT EDIT.
// source transform: migration/counter_v1_to_v2.json
//
// Migration plugin: reshapes CounterConfig from digest cfg_4be5118245cc2df4 to cfg_68334f330fa1ceae. dlopen'd by per
// (MigrateBulk). Works on the nanopb STRUCT — no JSON, no libprotobuf. Mirrors
// the field ops in tools/migrate/migrate.py (the JSON design/test bench).

#include "impl/migration_plugin_api.h"
#include "system/demo/demo.pb.h"

#include <pb_decode.h>
#include <pb_encode.h>

#include <cstdlib>
#include <cstring>

// Custom hooks (rules the declarative codegen can't express) — implemented by
// the user in the write-once sidecar counter_v1_to_v2_custom.cc.
// (no custom hooks)

extern "C" int transform_CounterConfig(const char* in, size_t in_len,
                             char** out, size_t* out_len) {
    system_demo_CounterConfig from = system_demo_CounterConfig_init_zero;
    system_demo_CounterConfig to   = system_demo_CounterConfig_init_zero;

    pb_istream_t is = pb_istream_from_buffer(
        reinterpret_cast<const pb_byte_t*>(in), in_len);
    if (!pb_decode(&is, system_demo_CounterConfig_fields, &from)) return 1;

    // Default carry: every field keeps its value unless a rule overrides it.
    to.step = from.step;
    to.max_value = from.max_value;
    to.wrap = from.wrap;
    std::strncpy(to.label, from.label, sizeof(to.label) - 1);
    to.hysteresis = from.hysteresis;

    // ---- rules (same semantics as tools/migrate/migrate.py) ----
    // add (default-if-absent; proto3 scalar -> set):
    to.hysteresis = 3;

    // Encode the TO struct.
    pb_ostream_t os = pb_ostream_from_buffer(
        reinterpret_cast<pb_byte_t*>(*out = static_cast<char*>(std::malloc(4096))),
        4096);
    if (!*out) return 1;
    if (!pb_encode(&os, system_demo_CounterConfig_fields, &to)) { std::free(*out); return 1; }
    *out_len = os.bytes_written;
    return 0;
}

extern "C" void per_register_migrations(const per_migration_api* api) {
    if (!api || api->abi_version != PER_MIGRATION_ABI_VERSION) return;
    api->add_edge(api->host, "cfg_4be5118245cc2df4", "cfg_68334f330fa1ceae", &transform_CounterConfig);
}
