// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/tsync/package.art
//
// Lib slice — class declaration for ONE prebuilt node (.art `node prebuilt`).
// A prebuilt node forks + supervises a THIRD-PARTY binary (iox-roudi, etcd, …)
// that is NOT a Theia FC: it speaks no TIPC, sends no heartbeat. It derives
// from GenRunnable (owns a thread), but unlike a `node runnable` ALL of its
// do_start/do_loop/do_stop are GENERATED — there is no hand-written impl:
//   do_start()  fork() + execvp("/usr/sbin/chronyd", args), stdout/stderr → pipes
//   do_loop()   drain the child's stdout/stderr line-by-line INTO this node's
//               logger (behave-like-a-pipe), waitpid() the child; on its death
//               return so the supervisor's restart strategy re-forks us
//   do_stop()   SIGTERM the child, reap (SIGKILL after a grace)
// reporting=false — a prebuilt node is normally NON-reporting, so the
// supervisor forks/reaps it but its watchdog (which only tracks nodes that
// actually send HeartbeatReport) never touches it.

#pragma once

#include "GenRunnable.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag

#include <cstdint>
#include <sys/types.h>   // pid_t

namespace ara::tsync {


// ---- ChronyProvider (prebuilt: forks "/usr/sbin/chronyd") -------------------------

class ChronyProvider : public ::theia::runtime::GenRunnable<ChronyProvider> {
public:
    static constexpr const char* kNodeName = "chrony";
    static constexpr uint32_t kTipcType     = 0x80010055u;
    static constexpr uint32_t kTipcInstance = 0u;
    static constexpr bool kReporting = false;

    // The third-party binary + its argv (from the .art `path` + `args` param).
    static constexpr const char* kPath = "/usr/sbin/chronyd";

    // The generated runnable contract (bodies in impl/ChronyProvider_handlers.cc,
    // also generated — overwritten on every regen).
    void do_start();
    void do_loop();
    void do_stop();

private:
    pid_t child_pid_ = -1;
    int   out_fd_    = -1;   // read end of the child's stdout pipe
    int   err_fd_    = -1;   // read end of the child's stderr pipe
};

}  // namespace ara::tsync
