site_name: Theia Docs
docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

exclude_docs: |
  preview/
  tasks/
