// AUTO-GENERATED by `artheia gen-app-composition` — DO NOT EDIT
// composition: Demo3WayP3
// process:     P3
//
// Boot scaffold: TimerService, TipcMux, RemoteRef connects,
// local node Inputs construction, inbound dispatch registration,
// start/kick_off, run until deadline, stop("normal").

#include "GenServer.hh"
#include "Logger.hh"
#include "NodeRef.hh"
#include "TimerService.hh"
#include "TipcMux.hh"
#include "demo_codecs.hh"

#include "incrementer_node.hh"
#include "counter_node.hh"

#include "system/demo/demo.pb.h"

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {
std::atomic<bool> g_shutdown{false};
void on_sig(int) noexcept { g_shutdown.store(true); }
}

int main() {
    std::signal(SIGINT,  on_sig);
    std::signal(SIGTERM, on_sig);
    auto logger = platform::runtime::MakeConsoleLogger();
    logger->info("=== P3 start (gen) ===");

    demo::runtime::TimerService timers;
    demo::runtime::TipcMux mux;

    // remote: CounterNode on process P1
    demo::runtime::RemoteRef<demo::CounterNode, 0xd0010001u, 0u> counter_node_ref;
    if (!counter_node_ref.connect(3000)) {
        logger->error("P3: failed to connect to CounterNode (tipc 0xd0010001:0)");
        return 1;
    }
    mux.watch_remote_ref(counter_node_ref);

    // local: IncrementerNode
    using incrementer_node_T = demo::IncrementerNode<demo::runtime::RemoteRef<demo::CounterNode, 0xd0010001u, 0u>>;
    incrementer_node_T incrementer_node(incrementer_node_T::Inputs{logger, timers, counter_node_ref});

    mux.start();
    incrementer_node.start();
    incrementer_node.kick_off();

    int run_ms = 5000;
    if (const char* env = std::getenv("DEMO_RUN_MS")) run_ms = std::atoi(env);
    auto deadline = std::chrono::steady_clock::now() +
                    std::chrono::milliseconds(run_ms);
    while (!g_shutdown.load() &&
           std::chrono::steady_clock::now() < deadline) {
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }

    logger->info("=== P3 stopping ===");
    mux.stop();
    incrementer_node.stop("normal");

    logger->info(std::string("=== P3 summary: ") + 
        "casts_sent=" + std::to_string(incrementer_node.state().casts_sent) + " ===");
    return 0;
}
