// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/tsync/component.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/Ptp4lProvider.hh"
#include "lib/Phc2sysProvider.hh"
#include "lib/TsyncCtl.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "MachineInstance.hh"  // resolve_node_tipc(--tipc arg) — per-node addr
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386).
                         // GenServer nodes use bind_node + register_cast;
                         // reporting runnables use bind_listener +
                         // register_cast_inline (no mailbox).
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
#include "PgClient.hh"            // process-group join/watch (broadcast fan-out)
                         // watchdog — every reporting node (GenServer AND
                         // runnable). Hand-framed cast, no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main(int argc, char** argv) {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // --tipc=<node>=<type>:<inst>|... — per-NODE TIPC address from the command
    // line (ARG-only; the supervisor appends it per child, instance machine-
    // shifted). Parse it once; each node below resolves its own address via
    // resolve_node_tipc(), falling back to its compiled .art address when absent
    // (a bare / un-supervised run binds the declared instance 0 — host-dev).
    ::theia::runtime::set_node_tipc_arg(argc, argv);

    // Crash forensics: install the libtombstone fatal-signal handler BEFORE any
    // node starts, so a SIGSEGV/SIGABRT/etc — even during startup — writes a
    // tombstone (backtrace + maps) to $THEIA_TOMBSTONE_DIR (the supervisor sets
    // it per child). The supervisor's GetTombstone serves it back (GUI
    // "Download tombstone"). No dir set (standalone run) → handler not armed.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("tsync", td);
    }

    using namespace ara::tsync;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map, sourced from Process.log_level on the
    // rig). Defaults to Info when unset/unparseable. Applied to every node's
    // logger below. The SINK kind comes from THEIA_LOGGER (MakeContextLogger).
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON ONCE,
    // before any node is constructed, so a node's ctor / init() can read its
    // knobs via ::theia::runtime::get_config().node(kNodeName).u32(...). A
    // missing file is fine — every lookup falls back to the caller's default.
    // Path from $THEIA_CONFIG / $THEIA_CONFIG_DIR / ./config/tsync.json.
    ::theia::runtime::init_config("tsync");

    ::theia::runtime::TimerService timers;
    // Publish the process TimerService so a `requires_timers` node's
    // handlers / init() reach it via process_timers() — mirrors
    // set_process_logger above. Set once, before any node starts.
    ::theia::runtime::set_process_timers(&timers);

    // Config-service receiver (#386). A reporting node binds its TIPC name
    // and registers the supervisor's control pushes. A GenServer node's cast
    // lands in its base handle_cast on the node thread; a reporting runnable
    // (no mailbox) takes them INLINE on the mux thread (register_cast_inline).
    // Same standard GwMessageHeader path as any app message — no bespoke frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);

    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below. The supervisor watchdog only watches nodes that
    // beat, so non-reporting nodes simply never appear here.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    Ptp4lProvider ptp4l;
    // Per-node logger: tagged [#ptp4l] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto ptp4l_log = MakeContextLogger(Ptp4lProvider::kNodeName);
        ptp4l_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(ptp4l_log);
        ptp4l.set_logger(std::move(ptp4l_log));
    }
    ptp4l.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(ptp4l.native_handle(),
        Ptp4lProvider::kNodeName, std::getenv("THEIA_NODE_CFG"));
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run.
    uint32_t ptp4l_type, ptp4l_inst;
    ::theia::runtime::resolve_node_tipc(Ptp4lProvider::kNodeName,
        Ptp4lProvider::kTipcType, Ptp4lProvider::kTipcInstance,
        ptp4l_type, ptp4l_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      ptp4l_type, ptp4l_inst);
        ptp4l.log().info(_tipc);
    }




    Phc2sysProvider phc2sys;
    // Per-node logger: tagged [#phc2sys] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto phc2sys_log = MakeContextLogger(Phc2sysProvider::kNodeName);
        phc2sys_log->set_level(boot_level);
        phc2sys.set_logger(std::move(phc2sys_log));
    }
    phc2sys.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(phc2sys.native_handle(),
        Phc2sysProvider::kNodeName, std::getenv("THEIA_NODE_CFG"));
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run.
    uint32_t phc2sys_type, phc2sys_inst;
    ::theia::runtime::resolve_node_tipc(Phc2sysProvider::kNodeName,
        Phc2sysProvider::kTipcType, Phc2sysProvider::kTipcInstance,
        phc2sys_type, phc2sys_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      phc2sys_type, phc2sys_inst);
        phc2sys.log().info(_tipc);
    }




    TsyncCtl tsync_ctl;
    // Per-node logger: tagged [#tsync_ctl] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto tsync_ctl_log = MakeContextLogger(TsyncCtl::kNodeName);
        tsync_ctl_log->set_level(boot_level);
        tsync_ctl.set_logger(std::move(tsync_ctl_log));
    }
    tsync_ctl.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(tsync_ctl.native_handle(),
        TsyncCtl::kNodeName, std::getenv("THEIA_NODE_CFG"));
    // Resolve this node's TIPC address from the --tipc arg the supervisor built
    // from executor.json (per node, instance machine-shifted), so the BINARY is
    // address-agnostic — same binary on every machine. Falls back to the compiled
    // kTipcType/kTipcInstance (the .art instance) for a standalone run.
    uint32_t tsync_ctl_type, tsync_ctl_inst;
    ::theia::runtime::resolve_node_tipc(TsyncCtl::kNodeName,
        TsyncCtl::kTipcType, TsyncCtl::kTipcInstance,
        tsync_ctl_type, tsync_ctl_inst);
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      tsync_ctl_type, tsync_ctl_inst);
        tsync_ctl.log().info(_tipc);
    }

    if (auto* tsync_ctl_cfg = config_mux.bind_node(
            tsync_ctl, tsync_ctl_type,
            tsync_ctl_inst)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            tsync_ctl_cfg, tsync_ctl);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            tsync_ctl_cfg, tsync_ctl);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            tsync_ctl_cfg, tsync_ctl);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<SyncStatusReq, SyncStatus>(
            tsync_ctl_cfg, tsync_ctl);
        config_mux.register_call<TimeSourceReq, TimeSourceReply>(
            tsync_ctl_cfg, tsync_ctl);
        config_mux.register_call<SyncStateReq, SyncStateReply>(
            tsync_ctl_cfg, tsync_ctl);
        config_mux.register_call<OffsetReq, OffsetReply>(
            tsync_ctl_cfg, tsync_ctl);
        config_mux.register_call<GmInfoReq, GrandmasterReply>(
            tsync_ctl_cfg, tsync_ctl);
        // ---- process groups (pg): MANUAL pub/sub control (OTP pg shape) ----
        // The node OWNS its membership: pg_join<T>() to CONSUME a group,
        // pg_watch<T>()/broadcast_*() to PRODUCE, pg_leave<T>() to stop — from its
        // OWN logic (init()/handlers), never automatically here. We ATTACH the
        // node's PgClient to its demux binding (so a joined group's frames + the
        // supervisor's PgMembership pushes route into handle_cast) and pass its
        // BOUND ADDRESS as the watcher address — where the supervisor casts
        // PgMembership when this node pg_watch'es a group it produces to.
        tsync_ctl.pg_attach(TsyncCtl::kNodeName, tsync_ctl_cfg,
                                tsync_ctl_type, tsync_ctl_inst);
    } else {
        tsync_ctl.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto tsync_ctl_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(TsyncCtl::kNodeName);
        if (tsync_ctl_hb->open()) {
            tsync_ctl_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(tsync_ctl_hb));
        } else {
            tsync_ctl.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    ptp4l.stop("signal");

    phc2sys.stop("signal");

    tsync_ctl.stop("signal");

    return 0;
}
