// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/phm/component.art
//
// Lib slice (STATEM variant) — message wiring + GenStateM-derived
// daemon class for ONE node. Regenerated on every gen-app run. User
// edits land in impl/PhmFsm_handlers.cc.
//
// This template is the statem-aware sibling of Daemon.hh.j2 — it
// fires when this node's .art NodeDecl carries a `statem { ... }`
// block. The daemon derives from ::theia::runtime::GenStateM<T,S,D> and
// the transition table is encoded as switch-on-state per event type
// (one handle_event overload per declared event type).

#pragma once

#include "GenStateM.hh"
#include "NodeRef.hh"   // TipcAddr (PG plumbing)
#include "PgClient.hh"  // OTP-pg broadcast fan-out (sender-port broadcast_*)
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "phm_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/phm/phm.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::phm {



// ---- PhmFsm state machine ------------------------------------

// State enum: one entry per `.art statem.states [...]`, in declared
// order. Underlying type is uint8_t to match the gen_statem template
// + minimize per-event payload overhead.
enum class PhmFsmState : uint8_t {
    OK = 0,
    WARNING = 1,
    DEGRADED = 2,
    FAILED = 3
};

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_phm_*); aliasing them here keeps callers'
// signatures readable.
using PhmHealthStatus = system_services_phm_PhmHealthStatus;

using FaultObserved = system_services_phm_FaultObserved;
using FaultEscalate = system_services_phm_FaultEscalate;
using FaultCleared = system_services_phm_FaultCleared;
using PhmFaultEvent = system_services_phm_PhmFaultEvent;


using PhmFsmData = PhmHealthStatus;

// (Subscriber-list / gen_event RETIRED — on_enter broadcasts the new state via
// the sender-port broadcast_*(), which is PURE PG multicast. Consumers pg_join
// the state message's group.)

// Forward-declare the user-facing daemon so the GenStateM template
// can be instantiated below (CRTP).
class PhmFsm;

// PhmFsm — GenStateM-derived FSM daemon.
//
// Generated members:
//   - init(PhmFsmData&) returns the initial state
//     (PhmFsmState::OK)
//   - one handle_event overload per declared event type
//     (FaultObserved, FaultEscalate, FaultEscalate, FaultCleared, FaultEscalate, FaultCleared, FaultCleared)
//   - handle_event for ::theia::runtime::StateTimeoutMsg<PhmFsmState>
//     covering states with `timeout → ...` rules
//   - subscribe/unsubscribe/broadcast helpers for sender ports
//
// User-overridable (in impl/):
//   - on_enter(new, old, data) — side effects (broadcast, log, persist)
//   - any handle_event overload (if the static table needs a guard)
class PhmFsm : public ::theia::runtime::GenStateM<PhmFsm,
                                                       PhmFsmState,
                                                       PhmFsmData> {
public:
    static constexpr const char* kNodeName = "phm_fsm";
    static constexpr uint32_t kTipcType     = 0x80010065u;
    static constexpr uint32_t kTipcInstance = 0u;

    // State enum → its .art name. The GenStateM base calls this when it emits
    // a STATEM trace so the record carries from/to state names (OFF→STARTING),
    // not just the bare ordinal — what `tdb tracecat` / the GUI / rf assert on.
    static const char* state_name(PhmFsmState s) {
        switch (s) {
        case PhmFsmState::OK: return "OK";
        case PhmFsmState::WARNING: return "WARNING";
        case PhmFsmState::DEGRADED: return "DEGRADED";
        case PhmFsmState::FAILED: return "FAILED";
        }
        return "?";
    }

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). See doc on the non-statem Daemon template for full
    // semantics. statem-flavour FCs use the same per-(node, msg_type)
    // filter map as plain GenServer ones.
    static constexpr bool kReporting = true;


    // ---- Trace config (reporting=true only) -----------------------
    // Delegates to the process-wide Tracer per #355; see the
    // non-statem Daemon template for full semantics.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }

    // ---- process groups (pg): MANUAL pub/sub over TIPC nameseq multicast ----
    // Same model as the non-statem Daemon template: group identity =
    // msg_type_name<T>() (the .art wire name); the supervisor allocates the
    // group's TIPC type + a unique instance; broadcast_*() multicasts ONE
    // datagram to the whole group. A consumer pg_join<T>()s from init(); a
    // broadcaster pg_resolve<T>()s the type (cached). See [[project-pg-broadcast-model]].
    void pg_attach(const char* node_name, ::theia::runtime::NodeBinding* b) {
        pg_.attach(node_name, b);
    }
    template <typename T> ::theia::runtime::PgClient::Group pg_join() {
        return pg_.join<T>();
    }
    template <typename T> ::theia::runtime::PgClient::Group pg_resolve() {
        if (!pg_groups_[::theia::runtime::RemoteCodec<T>::service_id].ok)
            pg_groups_[::theia::runtime::RemoteCodec<T>::service_id] = pg_.resolve<T>();
        return pg_groups_[::theia::runtime::RemoteCodec<T>::service_id];
    }
    template <typename T> void pg_leave() { pg_.leave<T>(); }
    template <typename T>
    void pg_broadcast(uint32_t group_type, const T& msg) {
        uint8_t _buf[8192];
        pb_ostream_t _os = pb_ostream_from_buffer(_buf, sizeof(_buf));
        if (!pb_encode(&_os, ::theia::runtime::RemoteCodec<T>::fields(), &msg))
            return;
        pg_.broadcast<T>(group_type, _buf,
                         static_cast<uint16_t>(_os.bytes_written));
    }

    // Keep the framework's config-service handler
    // (handle_cast(LogLevelPush)) visible (#386) — a derived handle_cast
    // would otherwise hide the base overload by name, so
    // register_cast<LogLevelPush> wouldn't resolve. Same name-hiding
    // guard as the handle_event using-decl below. GenStateM derives
    // from GenServer, so the handler is inherited.
    using ::theia::runtime::GenStateM<PhmFsm,
                                    PhmFsmState,
                                    PhmFsmData>::handle_cast;


    PhmFsmState init(PhmFsmData& /*d*/) {
        return PhmFsmState::OK;
    }

    // Keep base-class handle_event(StateTimeoutMsg) visible — derived
    // overloads otherwise hide it (C++ name hiding).
    using ::theia::runtime::GenStateM<PhmFsm,
                                    PhmFsmState,
                                    PhmFsmData>::handle_event;




    // FaultObserved — handled from: OK → WARNING
    ::theia::runtime::EventResult<PhmFsmState> handle_event(
            PhmFsmState s, const FaultObserved& /*e*/,
            PhmFsmData& /*d*/) {
        if (s == PhmFsmState::OK) {
            return ::theia::runtime::transition_to<PhmFsmState>(
                PhmFsmState::WARNING);
        }
        return ::theia::runtime::keep_state<PhmFsmState>();
    }

    // FaultEscalate — handled from: OK → DEGRADED | WARNING → DEGRADED | DEGRADED → FAILED
    ::theia::runtime::EventResult<PhmFsmState> handle_event(
            PhmFsmState s, const FaultEscalate& /*e*/,
            PhmFsmData& /*d*/) {
        if (s == PhmFsmState::OK) {
            return ::theia::runtime::transition_to<PhmFsmState>(
                PhmFsmState::DEGRADED);
        }
        if (s == PhmFsmState::WARNING) {
            return ::theia::runtime::transition_to<PhmFsmState>(
                PhmFsmState::DEGRADED);
        }
        if (s == PhmFsmState::DEGRADED) {
            return ::theia::runtime::transition_to<PhmFsmState>(
                PhmFsmState::FAILED);
        }
        return ::theia::runtime::keep_state<PhmFsmState>();
    }

    // FaultCleared — handled from: WARNING → OK | DEGRADED → WARNING | FAILED → DEGRADED
    ::theia::runtime::EventResult<PhmFsmState> handle_event(
            PhmFsmState s, const FaultCleared& /*e*/,
            PhmFsmData& /*d*/) {
        if (s == PhmFsmState::WARNING) {
            return ::theia::runtime::transition_to<PhmFsmState>(
                PhmFsmState::OK);
        }
        if (s == PhmFsmState::DEGRADED) {
            return ::theia::runtime::transition_to<PhmFsmState>(
                PhmFsmState::WARNING);
        }
        if (s == PhmFsmState::FAILED) {
            return ::theia::runtime::transition_to<PhmFsmState>(
                PhmFsmState::DEGRADED);
        }
        return ::theia::runtime::keep_state<PhmFsmState>();
    }





    // ---- on_enter — defined in impl/ (user owns side effects)
    void on_enter(PhmFsmState new_s, PhmFsmState old_s,
                   PhmFsmData& d);

    // ---- Broadcast senders (per sender-port data element) — PG multicast --

    void     broadcast_to_sm_health(const PhmHealthStatus& msg);

    void     broadcast_dtc_out_fault(const PhmFaultEvent& msg);


    // ---- Server-port operations (one per unique handler signature) — impl
    //
    // Deduplicated by (req_msg, rep_msg): when two server ports
    // share an interface (e.g. ctl_tdb + ctl_com both providing
    // TraceControl), the handler signature is identical and only
    // gets emitted once. Dispatch is by request type, not by port.


private:
    // The node's PG client + broadcaster group-type cache (see the non-statem
    // Daemon template). Idle until the first pg_join/broadcast.
    ::theia::runtime::PgClient pg_;
    std::map<uint16_t, ::theia::runtime::PgClient::Group> pg_groups_;
};

// Broadcast fan-out — PG name-sequence multicast (one datagram → the whole
// group). Kept in lib (auto-generated); the user touches on_enter/handle_* only.

inline void PhmFsm::broadcast_to_sm_health(const PhmHealthStatus& msg) {
    // group identity = msg_type_name<PhmHealthStatus>() (the .art wire name); the
    // supervisor allocates group_type on first resolve. Members pg_join the same
    // type → register_cast<PhmHealthStatus> delivers it to their handle_cast.
    auto _g = pg_resolve<PhmHealthStatus>();
    if (!_g.ok) return;                       // supervisor unreachable — drop
    pg_broadcast<PhmHealthStatus>(_g.type, msg);
}

inline void PhmFsm::broadcast_dtc_out_fault(const PhmFaultEvent& msg) {
    // group identity = msg_type_name<PhmFaultEvent>() (the .art wire name); the
    // supervisor allocates group_type on first resolve. Members pg_join the same
    // type → register_cast<PhmFaultEvent> delivers it to their handle_cast.
    auto _g = pg_resolve<PhmFaultEvent>();
    if (!_g.ok) return;                       // supervisor unreachable — drop
    pg_broadcast<PhmFaultEvent>(_g.type, msg);
}




}  // namespace ara::phm


