// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/system/exec/package.art
//
// Lib slice — message wiring + class declaration. Regenerated on
// every gen-app run. User edits land in impl/ExecDaemon_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "system/services/exec/exec.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <mutex>
#include <utility>
#include <vector>

namespace ara::exec {


// ---- ExecDaemon ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (services_services_exec_*); aliasing them here keeps callers'
// signatures readable.
using StartGroupRequest = services_services_exec_StartGroupRequest;
using ExecEmpty = services_services_exec_ExecEmpty;
using StopGroupRequest = services_services_exec_StopGroupRequest;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.


// State held by the daemon — kept minimal; per-handler scratch
// goes in impl. Future iterations push more here once the FC has
// real persistent state needs.
struct ExecDaemonState {
    
    int  reserved{0};
};

class ExecDaemon : public demo::runtime::GenServer<ExecDaemon, ExecDaemonState> {
public:
    static constexpr const char* kNodeName = "exec_daemon";
    static constexpr uint32_t kTipcType     = 0x80010005u;
    static constexpr uint32_t kTipcInstance = 0u;

    // ---- Subscriber registration ----------------------------------


    // ---- GenServer plumbing: handle_info + terminate defaults
    //
    // GenServer's dispatch_info_ unconditionally calls
    // Derived::handle_info; the base also looks for terminate. We
    // provide no-op defaults inline; impl can shadow either with
    // its own overload if the daemon needs them.
    void handle_info(const char* /*info*/, ExecDaemonState& /*s*/) {}
    void terminate(const char* /*reason*/, ExecDaemonState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl

    ExecEmpty handle_call(const StartGroupRequest& req,
                                            ExecDaemonState& s);

    ExecEmpty handle_call(const StopGroupRequest& req,
                                            ExecDaemonState& s);


    // ---- send helpers — bodies in impl (the broadcast fan-out)


private:

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.




}  // namespace ara::exec
