"""AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.

source: services/system/sm/package.art

SwComponent + Executable for the sm FC. Regenerated on
every gen-app run; rig overlays patch by name via the existing
Override mechanism in artheia.manifest.

The supervision strategy (RestartType, shutdown_ms, start_cmd) lives
next door in ``executor.py`` so a regen of this file doesn't squash
the rig integrator's hand-drafted supervision choices.
"""
from artheia.manifest.application import (
    BuildTypeEnum,
    Executable,
    ExecutionStateReportingBehaviorEnum,
    RootSwComponentPrototype,
    SwComponent,
)


COMPONENT = SwComponent(
    name="sm",
    bazel_target="//services/system/sm:sm",
    owner="platform",
    art_node="system.services.sm/SmDaemon",
)


EXECUTABLE = Executable(
    name="sm",
    category="PLATFORM_LEVEL",
    build_type=BuildTypeEnum.BUILD_TYPE_RELEASE,
    reporting_behavior=(
        ExecutionStateReportingBehaviorEnum.REPORTING_BEHAVIOR_INDIVIDUAL
    ),
    root_sw_component_prototype=RootSwComponentPrototype(
        name="sm_root",
        application_type="SmDaemon",
    ),
)
