// User handler bodies for SmDaemon (STATEM variant).
//
// Generated by gen-app, then hand-edited with sm-specific
// cooperation logic per docs/autosar/services/sm.md §3.B:
//
//   - on_enter mutates SmStateMsg.state + ts_ns and broadcasts to
//     every subscriber registered via subscribe_broadcast_state().
//     Best-effort fan-out (a throwing subscriber doesn't stall the
//     FSM thread).
//   - handle_call(SmRequest) maps an external mode-change request
//     onto the matching FSM event. Targets that are internal-only
//     landing states (RUNNING, OFF, STARTING, DEGRADED) are
//     rejected with a stderr log so the misuse is observable.

#include "lib/SmDaemon.hh"

#include "NodeRef.hh"   // theia::runtime::LocalRef — publish self to the gate

#include <chrono>
#include <cstdio>

namespace ara::sm {

// Defined in SmGate_handlers.cc (impl-owned, shared singleton). on_enter
// publishes this SmDaemon into it so SmGate's handlers can post_event into the
// FSM in-process — replacing the old hand-wired publish in main.cc.
theia::runtime::LocalRef<SmDaemon>& sm_statem_ref();

static uint64_t now_ns_() {
    auto now = std::chrono::steady_clock::now().time_since_epoch();
    return static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::nanoseconds>(now).count());
}

void SmDaemon::on_enter(SmDaemonState new_s,
                          SmDaemonState /*old_s*/,
                          SmDaemonData& d) {
    // SmDaemonData IS SmStateMsg (alias produced by the lib template
    // because the .art's statem block declared `data SmStateMsg`). So
    // mutating d here updates the broadcast payload + the FSM's
    // persistent data in one move.
    // Publish self to the gate on first entry (idempotent on later
    // transitions). The initial OFF entry runs during start_statem(), so the
    // ref is wired before SmGate could receive a forwardable event. This is
    // the impl-owned replacement for main.cc's old hand-wired publish.
    if (!sm_statem_ref().valid()) {
        sm_statem_ref() = theia::runtime::LocalRef<SmDaemon>(*this);
    }

    d.state = static_cast<system_services_sm_SmState>(new_s);
    d.ts_ns = now_ns_();

    // Diagnostic — the supervisor's per-child log capture surfaces
    // this in the GUI's Trace panel.
    static const char* names[] = {
        "OFF", "STARTING", "RUNNING", "DEGRADED", "UPDATE", "SHUTDOWN",
    };
    const auto idx = static_cast<std::size_t>(new_s);
    std::fprintf(stderr, "[%s] → %s @ %llu\n",
                 kNodeName,
                 idx < sizeof(names)/sizeof(names[0]) ? names[idx] : "?",
                 static_cast<unsigned long long>(d.ts_ns));

    // §3.B notifier: fan out to every registered SmStateStream
    // subscriber. The lib template's broadcast_broadcast_state()
    // snapshots subscribers under the lock + invokes outside it, so
    // a slow subscriber can't stall the FSM thread.
    broadcast_broadcast_state(d);
}

// StateMgmtCtl::RequestMode — map an external mode-change request
// onto the matching FSM event. Caller is typically UCM (UpdateMode)
// or whatever app holds a StateMgmtCtl client.
//
// RUNNING is reached via internal events (StartupComplete,
// UpdateComplete) — not via a direct request. OFF/STARTING/DEGRADED
// are likewise internal-only landing states. Reject those with a
// stderr log so misuse is observable.
SmEmpty SmDaemon::handle_call(
        const SmRequest& req,
        theia::runtime::GenStateMHolder<SmDaemonState, SmDaemonData>& /*h*/) {
    switch (req.target) {
    case system_services_sm_SmState_SmState_SHUTDOWN:
        theia::runtime::post_event(*this, ShutdownRequest{});
        break;
    case system_services_sm_SmState_SmState_UPDATE:
        theia::runtime::post_event(*this, UpdateRequest{});
        break;
    case system_services_sm_SmState_SmState_RUNNING:
        std::fprintf(stderr,
            "[%s] RequestMode(RUNNING) — RUNNING is reached via "
            "internal events; request ignored\n", kNodeName);
        break;
    default:
        std::fprintf(stderr,
            "[%s] RequestMode(target=%u) — not a client-driven "
            "target; request ignored\n",
            kNodeName, static_cast<unsigned>(req.target));
        break;
    }
    return SmEmpty{};
}

}  // namespace ara::sm
