// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/system/ucm/package.art
//
// Lib slice — message wiring + class declaration. Regenerated on
// every gen-app run. User edits land in impl/UcmDaemon_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "system/services/ucm/ucm.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <mutex>
#include <utility>
#include <vector>

namespace system_services_ucm {


// ---- UcmDaemon ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (services_services_ucm_*); aliasing them here keeps callers'
// signatures readable.
using UcmRequest = services_services_ucm_UcmRequest;
using UcmReply = services_services_ucm_UcmReply;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.


// State held by the daemon — kept minimal; per-handler scratch
// goes in impl. Future iterations push more here once the FC has
// real persistent state needs.
struct UcmDaemonState {
    
    int  reserved{0};
};

class UcmDaemon : public demo::runtime::GenServer<UcmDaemon, UcmDaemonState> {
public:
    static constexpr const char* kNodeName = "ucm_daemon";
    static constexpr uint32_t kTipcType     = 0x8001000Eu;
    static constexpr uint32_t kTipcInstance = 0u;

    // ---- Subscriber registration ----------------------------------


    // ---- GenServer plumbing: handle_info + terminate defaults
    //
    // GenServer's dispatch_info_ unconditionally calls
    // Derived::handle_info; the base also looks for terminate. We
    // provide no-op defaults inline; impl can shadow either with
    // its own overload if the daemon needs them.
    void handle_info(const char* /*info*/, UcmDaemonState& /*s*/) {}
    void terminate(const char* /*reason*/, UcmDaemonState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl

    UcmReply handle_call(const UcmRequest& req,
                                            UcmDaemonState& s);


    // ---- send helpers — bodies in impl (the broadcast fan-out)


private:

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.




}  // namespace system_services_ucm
