// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/log/package.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/LogDaemon.hh"
#include "lib/LogStreamPump.hh"
#include "lib/TraceStreamPump.hh"
#include "lib/TraceCtl.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386).
                         // GenServer nodes use bind_node + register_cast;
                         // reporting runnables use bind_listener +
                         // register_cast_inline (no mailbox).
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
                         // watchdog — every reporting node (GenServer AND
                         // runnable). Hand-framed cast, no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // Crash forensics: install the libtombstone fatal-signal handler BEFORE any
    // node starts, so a SIGSEGV/SIGABRT/etc — even during startup — writes a
    // tombstone (backtrace + maps) to $THEIA_TOMBSTONE_DIR (the supervisor sets
    // it per child). The supervisor's GetTombstone serves it back (GUI
    // "Download tombstone"). No dir set (standalone run) → handler not armed.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("log", td);
    }

    using namespace ara::log;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map, sourced from Process.log_level on the
    // rig). Defaults to Info when unset/unparseable. Applied to every node's
    // logger below. The SINK kind comes from THEIA_LOGGER (MakeContextLogger).
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON ONCE,
    // before any node is constructed, so a node's ctor / init() can read its
    // knobs via ::theia::runtime::get_config().node(kNodeName).u32(...). A
    // missing file is fine — every lookup falls back to the caller's default.
    // Path from $THEIA_CONFIG / $THEIA_CONFIG_DIR / ./config/log.json.
    ::theia::runtime::init_config("log");

    ::theia::runtime::TimerService timers;
    (void)timers;  // no node requires_timers

    // Config-service receiver (#386). A reporting node binds its TIPC name
    // and registers the supervisor's control pushes. A GenServer node's cast
    // lands in its base handle_cast on the node thread; a reporting runnable
    // (no mailbox) takes them INLINE on the mux thread (register_cast_inline).
    // Same standard GwMessageHeader path as any app message — no bespoke frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);

    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below. The supervisor watchdog only watches nodes that
    // beat, so non-reporting nodes simply never appear here.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    LogDaemon log_daemon;
    // Per-node logger: tagged [#log_daemon] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto log_daemon_log = MakeContextLogger(LogDaemon::kNodeName);
        log_daemon_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(log_daemon_log);
        log_daemon.set_logger(std::move(log_daemon_log));
    }
    log_daemon.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(log_daemon.native_handle(),
        LogDaemon::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      LogDaemon::kTipcType, LogDaemon::kTipcInstance);
        log_daemon.log().info(_tipc);
    }

    if (auto* log_daemon_cfg = config_mux.bind_node(
            log_daemon, LogDaemon::kTipcType,
            LogDaemon::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            log_daemon_cfg, log_daemon);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            log_daemon_cfg, log_daemon);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            log_daemon_cfg, log_daemon);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<LogSubscribeReq, LogEmpty>(
            log_daemon_cfg, log_daemon);
    } else {
        log_daemon.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto log_daemon_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(LogDaemon::kNodeName);
        if (log_daemon_hb->open()) {
            log_daemon_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(log_daemon_hb));
        } else {
            log_daemon.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    LogStreamPump log_pump;
    // Per-node logger: tagged [#log_pump] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto log_pump_log = MakeContextLogger(LogStreamPump::kNodeName);
        log_pump_log->set_level(boot_level);
        log_pump.set_logger(std::move(log_pump_log));
    }
    log_pump.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(log_pump.native_handle(),
        LogStreamPump::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      LogStreamPump::kTipcType, LogStreamPump::kTipcInstance);
        log_pump.log().info(_tipc);
    }


    // GenRunnable has no mailbox, so it can't take the supervisor's control
    // pushes via the GenServer handle_cast/mailbox path. Bind a listener and
    // register the LogLevelPush / TraceControlPush INLINE — the mux dispatch
    // thread applies them directly (on_log_level_push / on_trace_control_push,
    // touching only atomics). This is what makes a runnable's log level + trace
    // live-controllable (`tdb loglevel`/`trace <node>`), same as a gen_server.
    if (auto* log_pump_cfg = config_mux.bind_listener(
            LogStreamPump::kTipcType, LogStreamPump::kTipcInstance)) {
        config_mux.register_cast_inline<platform_runtime_LogLevelPush>(
            log_pump_cfg, log_pump, &LogStreamPump::on_log_level_push);
        config_mux.register_cast_inline<platform_runtime_TraceControlPush>(
            log_pump_cfg, log_pump, &LogStreamPump::on_trace_control_push);
    } else {
        log_pump.log().warn("config service bind failed; live log-level "
                                 "push disabled");
    }


    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto log_pump_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(LogStreamPump::kNodeName);
        if (log_pump_hb->open()) {
            log_pump_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(log_pump_hb));
        } else {
            log_pump.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    TraceStreamPump trace_pump;
    // Per-node logger: tagged [#trace_pump] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto trace_pump_log = MakeContextLogger(TraceStreamPump::kNodeName);
        trace_pump_log->set_level(boot_level);
        trace_pump.set_logger(std::move(trace_pump_log));
    }
    trace_pump.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(trace_pump.native_handle(),
        TraceStreamPump::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      TraceStreamPump::kTipcType, TraceStreamPump::kTipcInstance);
        trace_pump.log().info(_tipc);
    }


    // GenRunnable has no mailbox, so it can't take the supervisor's control
    // pushes via the GenServer handle_cast/mailbox path. Bind a listener and
    // register the LogLevelPush / TraceControlPush INLINE — the mux dispatch
    // thread applies them directly (on_log_level_push / on_trace_control_push,
    // touching only atomics). This is what makes a runnable's log level + trace
    // live-controllable (`tdb loglevel`/`trace <node>`), same as a gen_server.
    if (auto* trace_pump_cfg = config_mux.bind_listener(
            TraceStreamPump::kTipcType, TraceStreamPump::kTipcInstance)) {
        config_mux.register_cast_inline<platform_runtime_LogLevelPush>(
            trace_pump_cfg, trace_pump, &TraceStreamPump::on_log_level_push);
        config_mux.register_cast_inline<platform_runtime_TraceControlPush>(
            trace_pump_cfg, trace_pump, &TraceStreamPump::on_trace_control_push);
    } else {
        trace_pump.log().warn("config service bind failed; live log-level "
                                 "push disabled");
    }


    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto trace_pump_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(TraceStreamPump::kNodeName);
        if (trace_pump_hb->open()) {
            trace_pump_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(trace_pump_hb));
        } else {
            trace_pump.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    TraceCtl trace_ctl;
    // Per-node logger: tagged [#trace_ctl] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto trace_ctl_log = MakeContextLogger(TraceCtl::kNodeName);
        trace_ctl_log->set_level(boot_level);
        trace_ctl.set_logger(std::move(trace_ctl_log));
    }
    trace_ctl.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(trace_ctl.native_handle(),
        TraceCtl::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      TraceCtl::kTipcType, TraceCtl::kTipcInstance);
        trace_ctl.log().info(_tipc);
    }

    if (auto* trace_ctl_cfg = config_mux.bind_node(
            trace_ctl, TraceCtl::kTipcType,
            TraceCtl::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            trace_ctl_cfg, trace_ctl);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            trace_ctl_cfg, trace_ctl);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            trace_ctl_cfg, trace_ctl);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<SubscribeReq, TraceEmpty>(
            trace_ctl_cfg, trace_ctl);
    } else {
        trace_ctl.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto trace_ctl_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(TraceCtl::kNodeName);
        if (trace_ctl_hb->open()) {
            trace_ctl_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(trace_ctl_hb));
        } else {
            trace_ctl.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    log_daemon.stop("signal");

    log_pump.stop("signal");

    trace_pump.stop("signal");

    trace_ctl.stop("signal");

    return 0;
}
