// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/log/system/package.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/TraceCollector_handlers.cc.

#include "lib/TraceCollector.hh"

#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / MakeContextLogger / process_logger

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386)


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    using namespace ara::log;

    // Process-wide logger. Pick up THEIA_LOG_LEVEL from the env
    // (supervisor sets it from executor.json's per-child env map,
    // sourced from Process.log_level on the rig). Defaults to Info
    // when unset or unparseable. set_process_logger publishes it so a
    // reporting node's config service can apply a live ConfigureLogLevel
    // push (#386) via process_logger().set_level on the node thread.
    auto logger = MakeContextLogger();
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        logger->set_level(::platform::runtime::parse_log_level(lvl));
    }
    ::platform::runtime::set_process_logger(logger);
    (void)logger;  // available for user handlers via RuntimeContext

    demo::runtime::TimerService timers;
    (void)timers;  // wired into the daemon if it needs send_after

    // Config-service receiver (#386). A reporting node binds its TIPC
    // name and register_cast's the supervisor's control push; the cast
    // lands in GenServer's base handle_cast(LogLevelPush) on the node
    // thread. Same standard GwMessageHeader path as any app message —
    // no bespoke control frame.
    demo::runtime::TipcMux config_mux;


    TraceCollector trace_collector;
    trace_collector.start();
    std::fprintf(stderr, "[trace_collector] up — TIPC type=0x%x instance=%u\n",
                 TraceCollector::kTipcType, TraceCollector::kTipcInstance);

    if (auto* trace_collector_cfg = config_mux.bind_node(
            trace_collector, TraceCollector::kTipcType,
            TraceCollector::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            trace_collector_cfg, trace_collector);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<TraceConfigRequest, TraceEmpty>(
            trace_collector_cfg, trace_collector);
        config_mux.register_cast<TraceRecord>(trace_collector_cfg, trace_collector);
    } else {
        std::fprintf(stderr,
                     "[trace_collector] WARN: config service bind failed; "
                     "live log-level push + signal inject disabled\n");
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    trace_collector.stop("signal");

    return 0;
}
