/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PLATFORM_RUNTIME_TEST_PLATFORM_RUNTIME_TEST_MESSAGES_PB_H_INCLUDED
#define PB_PLATFORM_RUNTIME_TEST_PLATFORM_RUNTIME_TEST_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _platform_runtime_test_Inc {
    int32_t n;
} platform_runtime_test_Inc;

typedef struct _platform_runtime_test_Get {
    char dummy_field;
} platform_runtime_test_Get;

typedef struct _platform_runtime_test_GetReply {
    int32_t value;
} platform_runtime_test_GetReply;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define platform_runtime_test_Inc_init_default   {0}
#define platform_runtime_test_Get_init_default   {0}
#define platform_runtime_test_GetReply_init_default {0}
#define platform_runtime_test_Inc_init_zero      {0}
#define platform_runtime_test_Get_init_zero      {0}
#define platform_runtime_test_GetReply_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define platform_runtime_test_Inc_n_tag          1
#define platform_runtime_test_GetReply_value_tag 1

/* Struct field encoding specification for nanopb */
#define platform_runtime_test_Inc_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    n,                 1)
#define platform_runtime_test_Inc_CALLBACK NULL
#define platform_runtime_test_Inc_DEFAULT NULL

#define platform_runtime_test_Get_FIELDLIST(X, a) \

#define platform_runtime_test_Get_CALLBACK NULL
#define platform_runtime_test_Get_DEFAULT NULL

#define platform_runtime_test_GetReply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1)
#define platform_runtime_test_GetReply_CALLBACK NULL
#define platform_runtime_test_GetReply_DEFAULT NULL

extern const pb_msgdesc_t platform_runtime_test_Inc_msg;
extern const pb_msgdesc_t platform_runtime_test_Get_msg;
extern const pb_msgdesc_t platform_runtime_test_GetReply_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define platform_runtime_test_Inc_fields &platform_runtime_test_Inc_msg
#define platform_runtime_test_Get_fields &platform_runtime_test_Get_msg
#define platform_runtime_test_GetReply_fields &platform_runtime_test_GetReply_msg

/* Maximum encoded size of messages (where known) */
#define PLATFORM_RUNTIME_TEST_PLATFORM_RUNTIME_TEST_MESSAGES_PB_H_MAX_SIZE platform_runtime_test_Inc_size
#define platform_runtime_test_GetReply_size      11
#define platform_runtime_test_Get_size           0
#define platform_runtime_test_Inc_size           11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
