// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/idsm/component.art
//
// Lib slice — message wiring + class declaration for ONE node. An FC
// may declare several nodes; each gets its own <Node>.hh (this file).
// Regenerated on every gen-app run. User edits land in
// impl/IdsmDaemon_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "NodeRef.hh"   // cast(self, msg, TipcAddr) — pg broadcast fan-out
#include "PgClient.hh"  // OTP-pg broadcast fan-out (sender-port broadcast_*)
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "idsm_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/idsm/idsm.pb.h"
// State held by the daemon — FIELDS are APP-OWNED (node behaviour, not
// derived from the .art), so the struct lives in a WRITE-ONCE impl header
// (seeded empty, never clobbered without --force) that the user fills in.
// Included at GLOBAL scope (the header opens its own `namespace
// ara::idsm`) so it isn't nested under this file's
// namespace block — bound as the GenServer State type below.
#include "impl/IdsmDaemon_state.hh"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::idsm {


// ---- IdsmDaemon ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_idsm_*); aliasing them here keeps callers'
// signatures readable.
using IdsStatusMsg = system_services_idsm_IdsStatusMsg;
using IdsStatusReq = system_services_idsm_IdsStatusReq;
using IdsmDigestUpdate = system_services_idsm_IdsmDigestUpdate;
using IdsmModeInput = system_services_idsm_IdsmModeInput;



// (The in-process subscriber-list / gen_event pattern is RETIRED — OTP
// deprecated gen_event. A sender-port broadcast_*() is PURE PG multicast now;
// consumers pg_join the message type's group. No std::function subscriber
// typedef, no subscribe_*/unsubscribe_*, no per-node _subs_ list.)

class IdsmDaemon : public ::theia::runtime::GenServer<IdsmDaemon, IdsmDaemonState> {
public:
    static constexpr const char* kNodeName = "idsm_daemon";
    static constexpr uint32_t kTipcType     = 0x8001000Fu;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). When true, this node sends HeartbeatReport, the
    // supervisor watchdogs it, and the supervisor can push trace
    // config to it via the methods below.
    static constexpr bool kReporting = true;


    // Bring the framework's config-service handler
    // (handle_cast(LogLevelPush)) into scope (#386). A Derived
    // handle_cast for any port message would otherwise HIDE the base
    // overload by name, so register_cast<LogLevelPush> wouldn't
    // resolve. This using-decl keeps both visible; overload resolution
    // then picks the right one per message type.
    using ::theia::runtime::GenServer<IdsmDaemon, IdsmDaemonState>::handle_cast;

    // ---- Trace config (reporting=true only) -----------------------
    //
    // Per #355, the per-message-type filter lives in the process-wide
    // Tracer (see platform/runtime/Tracer.hh). These methods are thin
    // delegations so the supervisor / NodeTraceCtl wire path has a
    // stable in-class API while the actual storage stays in one place.
    //
    // The supervisor (#361) pushes (msg_type, enabled) pairs by
    // calling trace_enable() on receipt of an ApplyConfig RPC. emit()
    // consults the same filter inside Tracer; non-listed types are
    // dropped on the disabled fast path.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }

    // ---- process groups (pg): MANUAL pub/sub, the node decides WHEN ------
    //
    // OTP pg:join/leave shape over TIPC name-sequence MULTICAST. A group's
    // identity is its message TYPE T (group name = msg_type_name<T>(), a
    // generated .art-derived wire constant — no strings, no collision). The
    // SUPERVISOR is the namespace authority: pg_join<T>() CALLs it, gets a
    // {group_type, unique instance}, and binds a recv socket — received group
    // frames flow into this node's normal handle_cast via its demux. A
    // broadcaster pg_resolve<T>()s the type once, then broadcast<T>() multicasts
    // ONE datagram to the whole group (the kernel fans out — no per-member loop).
    // JOINING/RESOLVING/BROADCASTING are DELIBERATE node calls (from init()/a
    // handler), never automatic.
    //   pg_join<T>()    — consume T's group (deliver to this node's handle_cast).
    //   pg_resolve<T>() — learn T's group_type before broadcasting (sender only).
    //   pg_leave<T>()   — stop consuming T (frees the instance).
    //   broadcast_<port>_<data>(msg) — multicast to T's whole group.
    // pg_attach() is called once by main.cc with this node's name + demux binding
    // so PgClient can route received frames into the node and label CALLs.
    void pg_attach(const char* node_name, ::theia::runtime::NodeBinding* b) {
        pg_.attach(node_name, b);
    }
    template <typename T> ::theia::runtime::PgClient::Group pg_join() {
        return pg_.join<T>();
    }
    template <typename T> ::theia::runtime::PgClient::Group pg_resolve() {
        if (!pg_groups_[::theia::runtime::RemoteCodec<T>::service_id].ok)
            pg_groups_[::theia::runtime::RemoteCodec<T>::service_id] = pg_.resolve<T>();
        return pg_groups_[::theia::runtime::RemoteCodec<T>::service_id];
    }
    template <typename T> void pg_leave() { pg_.leave<T>(); }
    // Multicast `msg` to a group whose group_type the CALLER already resolved.
    // For the SUPERVISOR, which is itself the allocator and must not TIPC-self-CALL
    // pg_resolve: it resolves the type LOCALLY (engine registry) and calls this.
    // A normal FC uses broadcast_*() (which pg_resolve()s) — this is the escape
    // hatch for a node that owns the allocator.
    template <typename T>
    void pg_broadcast(uint32_t group_type, const T& msg) {
        uint8_t _buf[8192];
        pb_ostream_t _os = pb_ostream_from_buffer(_buf, sizeof(_buf));
        if (!pb_encode(&_os, ::theia::runtime::RemoteCodec<T>::fields(), &msg))
            return;
        pg_.broadcast<T>(group_type, _buf,
                         static_cast<uint16_t>(_os.bytes_written));
    }


    // ---- GenServer plumbing: terminate default
    //
    // terminate keeps an inline no-op default; impl may shadow it.
    //
    // There is NO handle_info(const InfoMsg&) clause: the wire-info path
    // was removed. An inbound TIPC frame that matched no register_cast/
    // register_call is dropped with a CRITICAL log in TipcMux — never
    // delivered as untyped bytes. Cross-node traffic is exclusively typed
    // cast/call. The only handle_info is the LOCAL string clause below
    // (post_info / self-tick).
    void terminate(const char* /*reason*/, IdsmDaemonState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl
    //
    // Deduplicated by message type: if two ports share the same
    // interface (e.g. ctl_tdb + ctl_com both providing
    // TraceControl) the handler signature is identical and only
    // gets emitted once. handle_call/handle_cast dispatch by
    // request type, not by port.

    void handle_cast(const IdsmDigestUpdate& msg, IdsmDaemonState& s);


    IdsStatusMsg handle_call(const IdsStatusReq& req,
                                            IdsmDaemonState& s);


    // ---- OTP init/1 — body in impl (IdsmDaemon_handlers.cc) ----------
    //
    // Called ONCE by the runtime on this node's thread after start(),
    // before the first mailbox item (GenServer::dispatch_init_). A
    // self-driving node bootstraps its work loop here (e.g.
    // ::theia::runtime::post_info(*this, "tick")); a passive node leaves it
    // empty. Emitted for every node so the hook is always visible.
    void init(IdsmDaemonState& s);

    // ---- string handle_info — body in impl ----------------------------
    //
    // The post_info()/send_after() string-message path (timer loops,
    // internal ticks). LOCAL-ONLY opaque signal — never crosses the wire.
    // Declared so a node can override the GenServer base no-op in its impl.
    void handle_info(const char* info, IdsmDaemonState& s);

    // ---- config update — body in impl (IdsmDaemon_handlers.cc) -------
    //
    // This node binds `config IdsmConfig`. services/per casts a
    // platform.runtime.ConfigUpdated when the etcd-backed config changes; the
    // GenServer base decodes the envelope + logs, then calls this hook. Declared
    // (shadowing the base no-op) so the node can apply its typed config LIVE —
    // ParseFromString cfg.config into IdsmConfig and honor the changed mask.
    // A node that only reads config at boot leaves the impl body empty.
    void on_config_update(const platform_runtime_ConfigUpdated& cfg,
                          IdsmDaemonState& s);

    // ---- send helpers — bodies in impl (the broadcast fan-out)

    void broadcast_broadcast_status(const IdsStatusMsg& msg);

    void broadcast_to_sm_mode_input(const IdsmModeInput& msg);


private:
    // The node's process-group client: owns the recv thread for joined groups and
    // the supervisor CALL channel. Attached to this node's demux via pg_attach()
    // from main.cc. Idle (no thread, no socket) until the first pg_join/broadcast.
    ::theia::runtime::PgClient pg_;
    // group_type cache for broadcasters: service_id(T) -> resolved {type,inst}.
    std::map<uint16_t, ::theia::runtime::PgClient::Group> pg_groups_;
};

// Broadcast fan-out — defined in the lib slice (not impl) so it stays
// auto-generated. The user touches handle_* in impl.

inline void IdsmDaemon::broadcast_broadcast_status(const IdsStatusMsg& msg) {
    // OTP-pg multicast: encode `msg` once and send ONE datagram to its TYPE's
    // process group {group_type, 0..~0} — the TIPC kernel fans out a copy to every
    // bound member (no per-member loop). group identity = msg_type_name<IdsStatusMsg>()
    // (the .art wire name); the supervisor allocates group_type the first time we
    // resolve it. Members receive it via register_cast<IdsStatusMsg> (same service_id),
    // so the receive path is the node's normal handle_cast. Best-effort (lossy).
    auto _g = pg_resolve<IdsStatusMsg>();
    if (!_g.ok) return;                       // supervisor unreachable — drop
    uint8_t _buf[8192];
    pb_ostream_t _os = pb_ostream_from_buffer(_buf, sizeof(_buf));
    if (!pb_encode(&_os, ::theia::runtime::RemoteCodec<IdsStatusMsg>::fields(), &msg))
        return;
    pg_.broadcast<IdsStatusMsg>(_g.type, _buf, static_cast<uint16_t>(_os.bytes_written));
}

inline void IdsmDaemon::broadcast_to_sm_mode_input(const IdsmModeInput& msg) {
    // OTP-pg multicast: encode `msg` once and send ONE datagram to its TYPE's
    // process group {group_type, 0..~0} — the TIPC kernel fans out a copy to every
    // bound member (no per-member loop). group identity = msg_type_name<IdsmModeInput>()
    // (the .art wire name); the supervisor allocates group_type the first time we
    // resolve it. Members receive it via register_cast<IdsmModeInput> (same service_id),
    // so the receive path is the node's normal handle_cast. Best-effort (lossy).
    auto _g = pg_resolve<IdsmModeInput>();
    if (!_g.ok) return;                       // supervisor unreachable — drop
    uint8_t _buf[8192];
    pb_ostream_t _os = pb_ostream_from_buffer(_buf, sizeof(_buf));
    if (!pb_encode(&_os, ::theia::runtime::RemoteCodec<IdsmModeInput>::fields(), &msg))
        return;
    pg_.broadcast<IdsmModeInput>(_g.type, _buf, static_cast<uint16_t>(_os.bytes_written));
}




}  // namespace ara::idsm


