// AUTO-GENERATED by `artheia gen-app-composition` — DO NOT EDIT
// composition: Demo3Way
// process:     P1
//
// Boot scaffold: TimerService, TipcMux, RemoteRef connects,
// local node Inputs construction, inbound dispatch registration,
// start/kick_off, run until deadline, stop("normal").

#include "GenServer.hh"
#include "Logger.hh"
#include "NodeRef.hh"
#include "TimerService.hh"
#include "TipcMux.hh"
#include "demo_codecs.hh"

#include "counter_node.hh"
#include "driver_node.hh"
#include "ticker_node.hh"

#include "demo/system/system.pb.h"

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {
std::atomic<bool> g_shutdown{false};
void on_sig(int) noexcept { g_shutdown.store(true); }
}

int main() {
    std::signal(SIGINT,  on_sig);
    std::signal(SIGTERM, on_sig);
    auto logger = platform::runtime::MakeConsoleLogger();
    logger->info("=== P1 start (gen) ===");

    demo::runtime::TimerService timers;
    demo::runtime::TipcMux mux;

    // local: CounterNode
    demo::CounterNode counter_node(demo::CounterNodeInputs{logger});
    demo::runtime::LocalRef<demo::CounterNode> counter_node_local_ref(counter_node);

    // local: TickerNode
    demo::TickerNode ticker_node(demo::TickerNodeInputs{logger, timers});

    // local: DriverNode
    using driver_node_T = demo::DriverNode<demo::runtime::LocalRef<demo::CounterNode>, demo::runtime::LocalRef<demo::CounterNode>>;
    driver_node_T driver_node(driver_node_T::Inputs{logger, timers, counter_node_local_ref, counter_node_local_ref});

    auto* bind_counter_node = mux.bind_node(counter_node, 0xd0010001u, 0u);
    mux.register_call<demo_system_Get, demo_system_GetReply>(bind_counter_node, counter_node);
    mux.register_cast<demo_system_Inc>(bind_counter_node, counter_node);

    mux.start();
    counter_node.start();
    ticker_node.start();
    driver_node.start();
    ticker_node.kick_off();
    driver_node.kick_off();

    int run_ms = 5000;
    if (const char* env = std::getenv("DEMO_RUN_MS")) run_ms = std::atoi(env);
    auto deadline = std::chrono::steady_clock::now() +
                    std::chrono::milliseconds(run_ms);
    while (!g_shutdown.load() &&
           std::chrono::steady_clock::now() < deadline) {
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }

    logger->info("=== P1 stopping ===");
    mux.stop();
    driver_node.stop("normal");
    ticker_node.stop("normal");
    counter_node.stop("normal");

    logger->info(std::string("=== P1 summary: ") + 
        "counter=" + std::to_string(counter_node.state().counter) + " " + "driver.replies_ok=" + std::to_string(driver_node.state().replies_ok) + " ===");
    return 0;
}
