// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/crypto/package.art
//
// Lib slice — message wiring + class declaration for ONE node. An FC
// may declare several nodes; each gets its own <Node>.hh (this file).
// Regenerated on every gen-app run. User edits land in
// impl/CryptoProvider_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "crypto_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/crypto/crypto.pb.h"
// State held by the daemon — FIELDS are APP-OWNED (node behaviour, not
// derived from the .art), so the struct lives in a WRITE-ONCE impl header
// (seeded empty, never clobbered without --force) that the user fills in.
// Included at GLOBAL scope (the header opens its own `namespace
// ara::crypto`) so it isn't nested under this file's
// namespace block — bound as the GenServer State type below.
#include "impl/CryptoProvider_state.hh"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::crypto {


// ---- CryptoProvider ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_crypto_*); aliasing them here keeps callers'
// signatures readable.
using CreateCtxReq = system_services_crypto_CreateCtxReq;
using CreateCtxReply = system_services_crypto_CreateCtxReply;
using CtxStartReq = system_services_crypto_CtxStartReq;
using CtxAck = system_services_crypto_CtxAck;
using CtxUpdateReq = system_services_crypto_CtxUpdateReq;
using CtxFinishReq = system_services_crypto_CtxFinishReq;
using CtxFinishReply = system_services_crypto_CtxFinishReply;
using SlotInfoReq = system_services_crypto_SlotInfoReq;
using SlotInfoReply = system_services_crypto_SlotInfoReply;
using HashReq = system_services_crypto_HashReq;
using HashReply = system_services_crypto_HashReply;
using SignReq = system_services_crypto_SignReq;
using SignReply = system_services_crypto_SignReply;
using VerifyReq = system_services_crypto_VerifyReq;
using VerifyReply = system_services_crypto_VerifyReply;
using CertReq = system_services_crypto_CertReq;
using CertReply = system_services_crypto_CertReply;
using PrivOpReq = system_services_crypto_PrivOpReq;
using PrivOpReply = system_services_crypto_PrivOpReply;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.


class CryptoProvider : public ::theia::runtime::GenServer<CryptoProvider, CryptoProviderState> {
public:
    static constexpr const char* kNodeName = "crypto_provider";
    static constexpr uint32_t kTipcType     = 0x80010006u;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). When true, this node sends HeartbeatReport, the
    // supervisor watchdogs it, and the supervisor can push trace
    // config to it via the methods below.
    static constexpr bool kReporting = true;


    // Bring the framework's config-service handler
    // (handle_cast(LogLevelPush)) into scope (#386). A Derived
    // handle_cast for any port message would otherwise HIDE the base
    // overload by name, so register_cast<LogLevelPush> wouldn't
    // resolve. This using-decl keeps both visible; overload resolution
    // then picks the right one per message type.
    using ::theia::runtime::GenServer<CryptoProvider, CryptoProviderState>::handle_cast;

    // ---- Trace config (reporting=true only) -----------------------
    //
    // Per #355, the per-message-type filter lives in the process-wide
    // Tracer (see platform/runtime/Tracer.hh). These methods are thin
    // delegations so the supervisor / NodeTraceCtl wire path has a
    // stable in-class API while the actual storage stays in one place.
    //
    // The supervisor (#361) pushes (msg_type, enabled) pairs by
    // calling trace_enable() on receipt of an ApplyConfig RPC. emit()
    // consults the same filter inside Tracer; non-listed types are
    // dropped on the disabled fast path.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }


    // ---- Subscriber registration ----------------------------------


    // ---- GenServer plumbing: terminate default
    //
    // terminate keeps an inline no-op default; impl may shadow it.
    //
    // There is NO handle_info(const InfoMsg&) clause: the wire-info path
    // was removed. An inbound TIPC frame that matched no register_cast/
    // register_call is dropped with a CRITICAL log in TipcMux — never
    // delivered as untyped bytes. Cross-node traffic is exclusively typed
    // cast/call. The only handle_info is the LOCAL string clause below
    // (post_info / self-tick).
    void terminate(const char* /*reason*/, CryptoProviderState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl
    //
    // Deduplicated by message type: if two ports share the same
    // interface (e.g. ctl_supdbg + ctl_com both providing
    // TraceControl) the handler signature is identical and only
    // gets emitted once. handle_call/handle_cast dispatch by
    // request type, not by port.


    CreateCtxReply handle_call(const CreateCtxReq& req,
                                            CryptoProviderState& s);

    CtxAck handle_call(const CtxStartReq& req,
                                            CryptoProviderState& s);

    CtxAck handle_call(const CtxUpdateReq& req,
                                            CryptoProviderState& s);

    CtxFinishReply handle_call(const CtxFinishReq& req,
                                            CryptoProviderState& s);

    SlotInfoReply handle_call(const SlotInfoReq& req,
                                            CryptoProviderState& s);

    HashReply handle_call(const HashReq& req,
                                            CryptoProviderState& s);

    SignReply handle_call(const SignReq& req,
                                            CryptoProviderState& s);

    VerifyReply handle_call(const VerifyReq& req,
                                            CryptoProviderState& s);

    CertReply handle_call(const CertReq& req,
                                            CryptoProviderState& s);

    PrivOpReply handle_call(const PrivOpReq& req,
                                            CryptoProviderState& s);


    // ---- OTP init/1 — body in impl (CryptoProvider_handlers.cc) ----------
    //
    // Called ONCE by the runtime on this node's thread after start(),
    // before the first mailbox item (GenServer::dispatch_init_). A
    // self-driving node bootstraps its work loop here (e.g.
    // ::theia::runtime::post_info(*this, "tick")); a passive node leaves it
    // empty. Emitted for every node so the hook is always visible.
    void init(CryptoProviderState& s);

    // ---- string handle_info — body in impl ----------------------------
    //
    // The post_info()/send_after() string-message path (timer loops,
    // internal ticks). LOCAL-ONLY opaque signal — never crosses the wire.
    // Declared so a node can override the GenServer base no-op in its impl.
    void handle_info(const char* info, CryptoProviderState& s);

    // ---- config update — body in impl (CryptoProvider_handlers.cc) -------
    //
    // This node binds `config CryptoConfig`. services/per casts a
    // platform.runtime.ConfigUpdated when the etcd-backed config changes; the
    // GenServer base decodes the envelope + logs, then calls this hook. Declared
    // (shadowing the base no-op) so the node can apply its typed config LIVE —
    // ParseFromString cfg.config into CryptoConfig and honor the changed mask.
    // A node that only reads config at boot leaves the impl body empty.
    void on_config_update(const platform_runtime_ConfigUpdated& cfg,
                          CryptoProviderState& s);

    // ---- send helpers — bodies in impl (the broadcast fan-out)


private:

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.




}  // namespace ara::crypto


