// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/crypto/package.art
//
// FC-wide inbound RemoteCodec specializations (#387).
//
// register_call / register_cast on a reporting node's config service
// need a RemoteCodec<T> for every inbound type. This header declares
// ONE THEIA_DECLARE_REMOTE_CODEC per inbound (receiver-port data /
// server-op req+rep) type, deduplicated across EVERY node in the FC.
//
// It lives in one header — not per-node — so that when two nodes in
// the same FC share an inbound type (e.g. com's ComDaemon and the
// test ProbeDaemon both take ComEmpty), the codec specialization is
// declared exactly once even though main.cc includes both node
// headers. Each node header #includes this (guarded by #pragma once),
// so a node header used standalone still has its codecs.
//
// A codec keys its service_id on the proto type name in the message's
// DEFINING package — so an inbound type imported from another package
// (e.g. a PSP bus PDU) declares its codec under that package's name,
// matching the sender. The #include set below covers every defining
// package an inbound type comes from.

#pragma once

#include "RemoteCodec.hh"   // THEIA_DECLARE_REMOTE_CODEC
#include "system/services/crypto/crypto.pb.h"




#ifndef THEIA_CODEC_system_services_crypto_CreateCtxReq
#define THEIA_CODEC_system_services_crypto_CreateCtxReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CreateCtxReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CreateCtxReply
#define THEIA_CODEC_system_services_crypto_CreateCtxReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CreateCtxReply)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CtxStartReq
#define THEIA_CODEC_system_services_crypto_CtxStartReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CtxStartReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CtxAck
#define THEIA_CODEC_system_services_crypto_CtxAck
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CtxAck)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CtxUpdateReq
#define THEIA_CODEC_system_services_crypto_CtxUpdateReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CtxUpdateReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CtxFinishReq
#define THEIA_CODEC_system_services_crypto_CtxFinishReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CtxFinishReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CtxFinishReply
#define THEIA_CODEC_system_services_crypto_CtxFinishReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CtxFinishReply)
#endif
#ifndef THEIA_CODEC_system_services_crypto_SlotInfoReq
#define THEIA_CODEC_system_services_crypto_SlotInfoReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_SlotInfoReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_SlotInfoReply
#define THEIA_CODEC_system_services_crypto_SlotInfoReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_SlotInfoReply)
#endif
#ifndef THEIA_CODEC_system_services_crypto_HashReq
#define THEIA_CODEC_system_services_crypto_HashReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_HashReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_HashReply
#define THEIA_CODEC_system_services_crypto_HashReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_HashReply)
#endif
#ifndef THEIA_CODEC_system_services_crypto_SignReq
#define THEIA_CODEC_system_services_crypto_SignReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_SignReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_SignReply
#define THEIA_CODEC_system_services_crypto_SignReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_SignReply)
#endif
#ifndef THEIA_CODEC_system_services_crypto_VerifyReq
#define THEIA_CODEC_system_services_crypto_VerifyReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_VerifyReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_VerifyReply
#define THEIA_CODEC_system_services_crypto_VerifyReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_VerifyReply)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CertReq
#define THEIA_CODEC_system_services_crypto_CertReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CertReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_CertReply
#define THEIA_CODEC_system_services_crypto_CertReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_CertReply)
#endif
#ifndef THEIA_CODEC_system_services_crypto_PrivOpReq
#define THEIA_CODEC_system_services_crypto_PrivOpReq
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_PrivOpReq)
#endif
#ifndef THEIA_CODEC_system_services_crypto_PrivOpReply
#define THEIA_CODEC_system_services_crypto_PrivOpReply
THEIA_DECLARE_REMOTE_CODEC(system_services_crypto_PrivOpReply)
#endif

// FC-wide enum aliases — the enum TYPE and each VALUE inside the FC namespace, so
// impl code writes the readable `HashAlgo` / `SHA256`
// instead of nanopb's double-prefixed name
// (system_services_crypto_<Enum>_<Enum>_<VALUE>). Emitted ONCE here (this header
// is #pragma once + included by every node header) — NOT per-node, so two node
// headers in one TU don't redefine them.
namespace ara::crypto {
using HashAlgo = system_services_crypto_HashAlgo;
inline constexpr HashAlgo SHA256 = system_services_crypto_HashAlgo_HashAlgo_SHA256;
inline constexpr HashAlgo SHA384 = system_services_crypto_HashAlgo_HashAlgo_SHA384;
inline constexpr HashAlgo SHA512 = system_services_crypto_HashAlgo_HashAlgo_SHA512;
using CryptoStatus = system_services_crypto_CryptoStatus;
inline constexpr CryptoStatus OK = system_services_crypto_CryptoStatus_CryptoStatus_OK;
inline constexpr CryptoStatus UNKNOWN_IDENTIFIER = system_services_crypto_CryptoStatus_CryptoStatus_UNKNOWN_IDENTIFIER;
inline constexpr CryptoStatus INCOMPATIBLE_ARGS = system_services_crypto_CryptoStatus_CryptoStatus_INCOMPATIBLE_ARGS;
inline constexpr CryptoStatus USAGE_VIOLATION = system_services_crypto_CryptoStatus_CryptoStatus_USAGE_VIOLATION;
inline constexpr CryptoStatus AUTH_TAG_FAILED = system_services_crypto_CryptoStatus_CryptoStatus_AUTH_TAG_FAILED;
inline constexpr CryptoStatus BAD_ALGO = system_services_crypto_CryptoStatus_CryptoStatus_BAD_ALGO;
inline constexpr CryptoStatus BAD_CONTEXT = system_services_crypto_CryptoStatus_CryptoStatus_BAD_CONTEXT;
inline constexpr CryptoStatus BACKEND_ERROR = system_services_crypto_CryptoStatus_CryptoStatus_BACKEND_ERROR;
inline constexpr CryptoStatus BAD_INPUT = system_services_crypto_CryptoStatus_CryptoStatus_BAD_INPUT;
using CtxKind = system_services_crypto_CtxKind;
inline constexpr CtxKind HASH = system_services_crypto_CtxKind_CtxKind_HASH;
inline constexpr CtxKind SIGNER = system_services_crypto_CtxKind_CtxKind_SIGNER;
inline constexpr CtxKind VERIFIER = system_services_crypto_CtxKind_CtxKind_VERIFIER;
}  // namespace ara::crypto
