// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/nm/package.art
//
// Lib slice (STATEM variant) — message wiring + GenStateM-derived
// daemon class for ONE node. Regenerated on every gen-app run. User
// edits land in impl/NmDaemon_handlers.cc.
//
// This template is the statem-aware sibling of Daemon.hh.j2 — it
// fires when this node's .art NodeDecl carries a `statem { ... }`
// block. The daemon derives from ::theia::runtime::GenStateM<T,S,D> and
// the transition table is encoded as switch-on-state per event type
// (one handle_event overload per declared event type).

#pragma once

#include "GenStateM.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "nm_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/nm/nm.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::nm {



// ---- NmDaemon state machine ------------------------------------

// State enum: one entry per `.art statem.states [...]`, in declared
// order. Underlying type is uint8_t to match the gen_statem template
// + minimize per-event payload overhead.
enum class NmDaemonState : uint8_t {
    NETWORK_OFF = 0,
    LINK_AVAILABLE = 1,
    WIFI_ASSOCIATED = 2,
    IP_ACQUIRED = 3,
    VPN_ESTABLISHED = 4,
    NETWORK_OPERATIONAL = 5,
    DEGRADED = 6
};

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_nm_*); aliasing them here keeps callers'
// signatures readable.
using NmStatusMsg = system_services_nm_NmStatusMsg;

using LinkUp = system_services_nm_LinkUp;
using WifiAssociated = system_services_nm_WifiAssociated;
using AddrAcquired = system_services_nm_AddrAcquired;
using LinkDown = system_services_nm_LinkDown;
using WifiDisassociated = system_services_nm_WifiDisassociated;
using VpnUp = system_services_nm_VpnUp;
using AddrLost = system_services_nm_AddrLost;
using Operational = system_services_nm_Operational;
using VpnDown = system_services_nm_VpnDown;
using NetStatusReq = system_services_nm_NetStatusReq;
using WifiScanReq = system_services_nm_WifiScanReq;
using WifiScanReply = system_services_nm_WifiScanReply;
using WifiConnectReq = system_services_nm_WifiConnectReq;
using WifiConnectReply = system_services_nm_WifiConnectReply;


using NmDaemonData = NmStatusMsg;

// Subscribers (one type per sender-port data element). Free-functions
// so the daemon stays delivery-flavor agnostic. on_enter — declared
// in impl — typically broadcasts the new state to these.
using BroadcastStatusSubscriber =
    std::function<void(const NmStatusMsg&)>;


// Forward-declare the user-facing daemon so the GenStateM template
// can be instantiated below (CRTP).
class NmDaemon;

// NmDaemon — GenStateM-derived FSM daemon.
//
// Generated members:
//   - init(NmDaemonData&) returns the initial state
//     (NmDaemonState::NETWORK_OFF)
//   - one handle_event overload per declared event type
//     (LinkUp, WifiAssociated, AddrAcquired, LinkDown, AddrAcquired, WifiDisassociated, LinkDown, VpnUp, AddrLost, WifiDisassociated, LinkDown, Operational, VpnDown, AddrLost, WifiDisassociated, LinkDown, VpnDown, AddrLost, WifiDisassociated, LinkDown, VpnUp, AddrAcquired, WifiAssociated, LinkUp, LinkDown)
//   - handle_event for ::theia::runtime::StateTimeoutMsg<NmDaemonState>
//     covering states with `timeout → ...` rules
//   - subscribe/unsubscribe/broadcast helpers for sender ports
//
// User-overridable (in impl/):
//   - on_enter(new, old, data) — side effects (broadcast, log, persist)
//   - any handle_event overload (if the static table needs a guard)
class NmDaemon : public ::theia::runtime::GenStateM<NmDaemon,
                                                       NmDaemonState,
                                                       NmDaemonData> {
public:
    static constexpr const char* kNodeName = "nm_daemon";
    static constexpr uint32_t kTipcType     = 0x8001002Eu;
    static constexpr uint32_t kTipcInstance = 0u;

    // State enum → its .art name. The GenStateM base calls this when it emits
    // a STATEM trace so the record carries from/to state names (OFF→STARTING),
    // not just the bare ordinal — what `tdb tracecat` / the GUI / rf assert on.
    static const char* state_name(NmDaemonState s) {
        switch (s) {
        case NmDaemonState::NETWORK_OFF: return "NETWORK_OFF";
        case NmDaemonState::LINK_AVAILABLE: return "LINK_AVAILABLE";
        case NmDaemonState::WIFI_ASSOCIATED: return "WIFI_ASSOCIATED";
        case NmDaemonState::IP_ACQUIRED: return "IP_ACQUIRED";
        case NmDaemonState::VPN_ESTABLISHED: return "VPN_ESTABLISHED";
        case NmDaemonState::NETWORK_OPERATIONAL: return "NETWORK_OPERATIONAL";
        case NmDaemonState::DEGRADED: return "DEGRADED";
        }
        return "?";
    }

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). See doc on the non-statem Daemon template for full
    // semantics. statem-flavour FCs use the same per-(node, msg_type)
    // filter map as plain GenServer ones.
    static constexpr bool kReporting = true;


    // ---- Trace config (reporting=true only) -----------------------
    // Delegates to the process-wide Tracer per #355; see the
    // non-statem Daemon template for full semantics.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }

    // Keep the framework's config-service handler
    // (handle_cast(LogLevelPush)) visible (#386) — a derived handle_cast
    // would otherwise hide the base overload by name, so
    // register_cast<LogLevelPush> wouldn't resolve. Same name-hiding
    // guard as the handle_event using-decl below. GenStateM derives
    // from GenServer, so the handler is inherited.
    using ::theia::runtime::GenStateM<NmDaemon,
                                    NmDaemonState,
                                    NmDaemonData>::handle_cast;


    NmDaemonState init(NmDaemonData& /*d*/) {
        return NmDaemonState::NETWORK_OFF;
    }

    // Keep base-class handle_event(StateTimeoutMsg) visible — derived
    // overloads otherwise hide it (C++ name hiding).
    using ::theia::runtime::GenStateM<NmDaemon,
                                    NmDaemonState,
                                    NmDaemonData>::handle_event;




    // LinkUp — handled from: NETWORK_OFF → LINK_AVAILABLE | DEGRADED → LINK_AVAILABLE
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const LinkUp& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::NETWORK_OFF) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::LINK_AVAILABLE);
        }
        if (s == NmDaemonState::DEGRADED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::LINK_AVAILABLE);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // WifiAssociated — handled from: LINK_AVAILABLE → WIFI_ASSOCIATED | DEGRADED → WIFI_ASSOCIATED
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const WifiAssociated& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::LINK_AVAILABLE) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::WIFI_ASSOCIATED);
        }
        if (s == NmDaemonState::DEGRADED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::WIFI_ASSOCIATED);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // AddrAcquired — handled from: LINK_AVAILABLE → IP_ACQUIRED | WIFI_ASSOCIATED → IP_ACQUIRED | DEGRADED → IP_ACQUIRED
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const AddrAcquired& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::LINK_AVAILABLE) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::IP_ACQUIRED);
        }
        if (s == NmDaemonState::WIFI_ASSOCIATED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::IP_ACQUIRED);
        }
        if (s == NmDaemonState::DEGRADED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::IP_ACQUIRED);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // LinkDown — handled from: LINK_AVAILABLE → NETWORK_OFF | WIFI_ASSOCIATED → NETWORK_OFF | IP_ACQUIRED → DEGRADED | VPN_ESTABLISHED → DEGRADED | NETWORK_OPERATIONAL → DEGRADED | DEGRADED → NETWORK_OFF
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const LinkDown& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::LINK_AVAILABLE) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::NETWORK_OFF);
        }
        if (s == NmDaemonState::WIFI_ASSOCIATED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::NETWORK_OFF);
        }
        if (s == NmDaemonState::IP_ACQUIRED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        if (s == NmDaemonState::VPN_ESTABLISHED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        if (s == NmDaemonState::NETWORK_OPERATIONAL) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        if (s == NmDaemonState::DEGRADED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::NETWORK_OFF);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // WifiDisassociated — handled from: WIFI_ASSOCIATED → LINK_AVAILABLE | IP_ACQUIRED → DEGRADED | VPN_ESTABLISHED → DEGRADED | NETWORK_OPERATIONAL → DEGRADED
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const WifiDisassociated& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::WIFI_ASSOCIATED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::LINK_AVAILABLE);
        }
        if (s == NmDaemonState::IP_ACQUIRED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        if (s == NmDaemonState::VPN_ESTABLISHED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        if (s == NmDaemonState::NETWORK_OPERATIONAL) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // VpnUp — handled from: IP_ACQUIRED → VPN_ESTABLISHED | DEGRADED → VPN_ESTABLISHED
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const VpnUp& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::IP_ACQUIRED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::VPN_ESTABLISHED);
        }
        if (s == NmDaemonState::DEGRADED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::VPN_ESTABLISHED);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // AddrLost — handled from: IP_ACQUIRED → DEGRADED | VPN_ESTABLISHED → DEGRADED | NETWORK_OPERATIONAL → DEGRADED
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const AddrLost& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::IP_ACQUIRED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        if (s == NmDaemonState::VPN_ESTABLISHED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        if (s == NmDaemonState::NETWORK_OPERATIONAL) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // Operational — handled from: VPN_ESTABLISHED → NETWORK_OPERATIONAL
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const Operational& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::VPN_ESTABLISHED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::NETWORK_OPERATIONAL);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }

    // VpnDown — handled from: VPN_ESTABLISHED → IP_ACQUIRED | NETWORK_OPERATIONAL → DEGRADED
    ::theia::runtime::EventResult<NmDaemonState> handle_event(
            NmDaemonState s, const VpnDown& /*e*/,
            NmDaemonData& /*d*/) {
        if (s == NmDaemonState::VPN_ESTABLISHED) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::IP_ACQUIRED);
        }
        if (s == NmDaemonState::NETWORK_OPERATIONAL) {
            return ::theia::runtime::transition_to<NmDaemonState>(
                NmDaemonState::DEGRADED);
        }
        return ::theia::runtime::keep_state<NmDaemonState>();
    }





    // ---- on_enter — defined in impl/ (user owns side effects)
    void on_enter(NmDaemonState new_s, NmDaemonState old_s,
                   NmDaemonData& d);

    // ---- config update — body in impl (NmDaemon_handlers.cc) -------
    //
    // This statem node binds `config NmConfig`. services/per casts a
    // platform.runtime.ConfigUpdated when the etcd-backed config changes; the
    // GenServer base (GenStateM derives from it) decodes the envelope + logs,
    // then calls this hook. Declared (shadowing the base no-op) so the FSM can
    // apply its typed config LIVE — ParseFromString cfg.config into
    // NmConfig and honor the changed mask. The second arg is the FSM
    // holder (same as handle_call) — reach h.data / post_event(*this, …) from it.
    // A node that only reads config at boot leaves the impl body empty.
    void on_config_update(const platform_runtime_ConfigUpdated& cfg,
                          ::theia::runtime::GenStateMHolder<NmDaemonState, NmDaemonData>& h);

    // ---- Subscriber registration (per sender-port data element) --------

    uint32_t subscribe_broadcast_status(
        BroadcastStatusSubscriber s);
    void     unsubscribe_broadcast_status(uint32_t id);
    void     broadcast_broadcast_status(const NmStatusMsg& msg);


    // ---- Server-port operations (one per unique handler signature) — impl
    //
    // Deduplicated by (req_msg, rep_msg): when two server ports
    // share an interface (e.g. ctl_supdbg + ctl_com both providing
    // TraceControl), the handler signature is identical and only
    // gets emitted once. Dispatch is by request type, not by port.
NmStatusMsg handle_call(const NetStatusReq& req,
                                            ::theia::runtime::GenStateMHolder<NmDaemonState, NmDaemonData>& h);
WifiScanReply handle_call(const WifiScanReq& req,
                                            ::theia::runtime::GenStateMHolder<NmDaemonState, NmDaemonData>& h);
WifiConnectReply handle_call(const WifiConnectReq& req,
                                            ::theia::runtime::GenStateMHolder<NmDaemonState, NmDaemonData>& h);


private:

    struct BroadcastStatusEntry {
        uint32_t id;
        BroadcastStatusSubscriber fn;
    };
    std::mutex broadcast_status_mu_;
    uint32_t broadcast_status_next_id_{1};
    std::vector<BroadcastStatusEntry>
        broadcast_status_subs_;

};

// Subscriber + broadcast inline impls — pure boilerplate; kept in
// lib because they're per-instance bookkeeping with no policy.

inline uint32_t NmDaemon::subscribe_broadcast_status(
        BroadcastStatusSubscriber s) {
    std::lock_guard<std::mutex> lk(broadcast_status_mu_);
    uint32_t id = broadcast_status_next_id_++;
    broadcast_status_subs_.push_back({id, std::move(s)});
    return id;
}

inline void NmDaemon::unsubscribe_broadcast_status(uint32_t id) {
    std::lock_guard<std::mutex> lk(broadcast_status_mu_);
    auto& v = broadcast_status_subs_;
    v.erase(std::remove_if(v.begin(), v.end(),
              [id](const auto& e) { return e.id == id; }), v.end());
}

inline void NmDaemon::broadcast_broadcast_status(const NmStatusMsg& msg) {
    std::vector<BroadcastStatusEntry> snap;
    {
        std::lock_guard<std::mutex> lk(broadcast_status_mu_);
        snap = broadcast_status_subs_;
    }
    for (const auto& e : snap) {
        try { e.fn(msg); }
        catch (...) {
            std::fprintf(stderr,
                "[%s] subscriber %u threw on broadcast.status — dropping\n",
                kNodeName, e.id);
        }
    }
}




}  // namespace ara::nm


