// AUTO-GENERATED by `artheia gen-app` — DO NOT EDIT.
// source: odd_path_client/system/components/odd_path_monitor.art
// node:   OddPathMonitor
//
// Slice 1 (core): dependency-injection bundle the app receives from
// its runtime. Holds shared_ptr handles to the platform services
// (logger, clock, timer) and a typed reference to the signal-junction
// dispatcher generated alongside this file. Regenerated on any model
// change; do not hand-edit.

#pragma once
#include <memory>

#include "gateway/libs/pero_cmp_lnx/lib/include/lifecycle_interface.hh"
#include "gateway/libs/pero_cmp_lnx/lib/include/logging_interface.hh"
#include "gateway/libs/pero_cmp_lnx/lib/include/clock_interface.hh"
#include "gateway/libs/pero_cmp_lnx/lib/include/timer_interface.hh"

#include "odd_path_monitor_signals.hh"

namespace odd_path_client {

class OddPathMonitorInputs {
 public:
  OddPathMonitorInputs() = delete;

  OddPathMonitorInputs(std::shared_ptr<pero_cmp_lnx::TimerInterface> timer,
                       odd_path_monitor_signals& signals,
                       std::shared_ptr<pero_cmp_lnx::ClockInterface> clock,
                       std::shared_ptr<pero_cmp_lnx::LoggingInterface> logger)
      : timer_(timer), signals_(signals), clock_(clock), logger_(logger) {}

  std::shared_ptr<pero_cmp_lnx::TimerInterface>   timer_;
  odd_path_monitor_signals&                       signals_;
  std::shared_ptr<pero_cmp_lnx::ClockInterface>   clock_;
  std::shared_ptr<pero_cmp_lnx::LoggingInterface> logger_;
};

}  // namespace odd_path_client
