// AUTO-GENERATED by `artheia gen-fc` — DO NOT EDIT.
// source: system/services/per/package.art
//
// FC-wide inbound RemoteCodec specializations (#387).
//
// register_call / register_cast on a reporting node's config service
// need a RemoteCodec<T> for every inbound type. This header declares
// ONE THEIA_DECLARE_REMOTE_CODEC per inbound (receiver-port data /
// server-op req+rep) type, deduplicated across EVERY node in the FC.
//
// It lives in one header — not per-node — so that when two nodes in
// the same FC share an inbound type (e.g. com's ComDaemon and the
// test ProbeDaemon both take ComEmpty), the codec specialization is
// declared exactly once even though main.cc includes both node
// headers. Each node header #includes this (guarded by #pragma once),
// so a node header used standalone still has its codecs.
//
// A codec keys its service_id on the proto type name in the message's
// DEFINING package — so an inbound type imported from another package
// (e.g. a PSP bus PDU) declares its codec under that package's name,
// matching the sender. The #include set below covers every defining
// package an inbound type comes from.

#pragma once

#include "RemoteCodec.hh"   // THEIA_DECLARE_REMOTE_CODEC
#include "system/services/per/per.pb.h"

#include "platform_runtime/runtime.pb.h"
#include "system/services/phm/phm.pb.h"



#ifndef THEIA_CODEC_system_services_per_GetConfigReq
#define THEIA_CODEC_system_services_per_GetConfigReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_GetConfigReq)
#endif
#ifndef THEIA_CODEC_system_services_per_ConfigSnapshot
#define THEIA_CODEC_system_services_per_ConfigSnapshot
THEIA_DECLARE_REMOTE_CODEC(system_services_per_ConfigSnapshot)
#endif
#ifndef THEIA_CODEC_system_services_per_PutConfigReq
#define THEIA_CODEC_system_services_per_PutConfigReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_PutConfigReq)
#endif
#ifndef THEIA_CODEC_system_services_per_PerReply
#define THEIA_CODEC_system_services_per_PerReply
THEIA_DECLARE_REMOTE_CODEC(system_services_per_PerReply)
#endif
#ifndef THEIA_CODEC_system_services_per_WatchConfigReq
#define THEIA_CODEC_system_services_per_WatchConfigReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_WatchConfigReq)
#endif
#ifndef THEIA_CODEC_system_services_phm_FcHealthReport
#define THEIA_CODEC_system_services_phm_FcHealthReport
THEIA_DECLARE_REMOTE_CODEC(system_services_phm_FcHealthReport)
#endif
#ifndef THEIA_CODEC_system_services_per_RegisterSchemaReq
#define THEIA_CODEC_system_services_per_RegisterSchemaReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_RegisterSchemaReq)
#endif
#ifndef THEIA_CODEC_system_services_per_ListSchemasReq
#define THEIA_CODEC_system_services_per_ListSchemasReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_ListSchemasReq)
#endif
#ifndef THEIA_CODEC_system_services_per_SchemaList
#define THEIA_CODEC_system_services_per_SchemaList
THEIA_DECLARE_REMOTE_CODEC(system_services_per_SchemaList)
#endif
#ifndef THEIA_CODEC_system_services_per_MigrateBulkReq
#define THEIA_CODEC_system_services_per_MigrateBulkReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_MigrateBulkReq)
#endif
#ifndef THEIA_CODEC_system_services_per_SnapshotReq
#define THEIA_CODEC_system_services_per_SnapshotReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_SnapshotReq)
#endif
#ifndef THEIA_CODEC_system_services_per_RestoreSnapshotReq
#define THEIA_CODEC_system_services_per_RestoreSnapshotReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_RestoreSnapshotReq)
#endif
#ifndef THEIA_CODEC_system_services_per_GetStoreSnapshotReq
#define THEIA_CODEC_system_services_per_GetStoreSnapshotReq
THEIA_DECLARE_REMOTE_CODEC(system_services_per_GetStoreSnapshotReq)
#endif
#ifndef THEIA_CODEC_system_services_per_PerStoreSnapshot
#define THEIA_CODEC_system_services_per_PerStoreSnapshot
THEIA_DECLARE_REMOTE_CODEC(system_services_per_PerStoreSnapshot)
#endif
