// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/per/package.art
//
// Lib slice — message wiring + class declaration for ONE node. An FC
// may declare several nodes; each gets its own <Node>.hh (this file).
// Regenerated on every gen-app run. User edits land in
// impl/PerManager_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "per_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/per/per.pb.h"
// State held by the daemon — FIELDS are APP-OWNED (node behaviour, not
// derived from the .art), so the struct lives in a WRITE-ONCE impl header
// (seeded empty, never clobbered without --force) that the user fills in.
// Included at GLOBAL scope (the header opens its own `namespace
// ara::per`) so it isn't nested under this file's
// namespace block — bound as the GenServer State type below.
#include "impl/PerManager_state.hh"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::per {


// ---- PerManager ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_per_*); aliasing them here keeps callers'
// signatures readable.
using RegisterSchemaReq = system_services_per_RegisterSchemaReq;
using PerReply = system_services_per_PerReply;
using ListSchemasReq = system_services_per_ListSchemasReq;
using SchemaList = system_services_per_SchemaList;
using MigrateBulkReq = system_services_per_MigrateBulkReq;
using SnapshotReq = system_services_per_SnapshotReq;
using RestoreSnapshotReq = system_services_per_RestoreSnapshotReq;
using GetStoreSnapshotReq = system_services_per_GetStoreSnapshotReq;
using PerStoreSnapshot = system_services_per_PerStoreSnapshot;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.


class PerManager : public ::theia::runtime::GenServer<PerManager, PerManagerState> {
public:
    static constexpr const char* kNodeName = "per_manager";
    static constexpr uint32_t kTipcType     = 0x80010016u;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). When true, this node sends HeartbeatReport, the
    // supervisor watchdogs it, and the supervisor can push trace
    // config to it via the methods below.
    static constexpr bool kReporting = true;


    // Bring the framework's config-service handler
    // (handle_cast(LogLevelPush)) into scope (#386). A Derived
    // handle_cast for any port message would otherwise HIDE the base
    // overload by name, so register_cast<LogLevelPush> wouldn't
    // resolve. This using-decl keeps both visible; overload resolution
    // then picks the right one per message type.
    using ::theia::runtime::GenServer<PerManager, PerManagerState>::handle_cast;

    // ---- Trace config (reporting=true only) -----------------------
    //
    // Per #355, the per-message-type filter lives in the process-wide
    // Tracer (see platform/runtime/Tracer.hh). These methods are thin
    // delegations so the supervisor / NodeTraceCtl wire path has a
    // stable in-class API while the actual storage stays in one place.
    //
    // The supervisor (#361) pushes (msg_type, enabled) pairs by
    // calling trace_enable() on receipt of an ApplyConfig RPC. emit()
    // consults the same filter inside Tracer; non-listed types are
    // dropped on the disabled fast path.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }


    // ---- Subscriber registration ----------------------------------


    // ---- GenServer plumbing: terminate default
    //
    // terminate keeps an inline no-op default; impl may shadow it.
    //
    // There is NO handle_info(const InfoMsg&) clause: the wire-info path
    // was removed. An inbound TIPC frame that matched no register_cast/
    // register_call is dropped with a CRITICAL log in TipcMux — never
    // delivered as untyped bytes. Cross-node traffic is exclusively typed
    // cast/call. The only handle_info is the LOCAL string clause below
    // (post_info / self-tick).
    void terminate(const char* /*reason*/, PerManagerState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl
    //
    // Deduplicated by message type: if two ports share the same
    // interface (e.g. ctl_supdbg + ctl_com both providing
    // TraceControl) the handler signature is identical and only
    // gets emitted once. handle_call/handle_cast dispatch by
    // request type, not by port.


    PerReply handle_call(const RegisterSchemaReq& req,
                                            PerManagerState& s);

    SchemaList handle_call(const ListSchemasReq& req,
                                            PerManagerState& s);

    PerReply handle_call(const MigrateBulkReq& req,
                                            PerManagerState& s);

    PerReply handle_call(const SnapshotReq& req,
                                            PerManagerState& s);

    PerReply handle_call(const RestoreSnapshotReq& req,
                                            PerManagerState& s);

    PerStoreSnapshot handle_call(const GetStoreSnapshotReq& req,
                                            PerManagerState& s);


    // ---- OTP init/1 — body in impl (PerManager_handlers.cc) ----------
    //
    // Called ONCE by the runtime on this node's thread after start(),
    // before the first mailbox item (GenServer::dispatch_init_). A
    // self-driving node bootstraps its work loop here (e.g.
    // ::theia::runtime::post_info(*this, "tick")); a passive node leaves it
    // empty. Emitted for every node so the hook is always visible.
    void init(PerManagerState& s);

    // ---- string handle_info — body in impl ----------------------------
    //
    // The post_info()/send_after() string-message path (timer loops,
    // internal ticks). LOCAL-ONLY opaque signal — never crosses the wire.
    // Declared so a node can override the GenServer base no-op in its impl.
    void handle_info(const char* info, PerManagerState& s);

    // ---- send helpers — bodies in impl (the broadcast fan-out)


private:

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.




}  // namespace ara::per


