// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/demo/component.art
//
// Per-node netgraph: one `constexpr TipcAddr` per peer this node
// can reach (.art-declared via `connect` in any composition or
// cluster). Symbolic peer name = node name. The user writes
// `cast(*this, msg, netgraph::<peer>)` — point-to-point, addressed
// by name.
//
// What's NOT here:
//   - No aggregate / destinations[] array. Fan-out is USER POLICY,
//     not topology — sm doesn't broadcast SmStateMsg "to everyone
//     consuming the type"; it sends to whichever peers its
//     application logic decides at that moment. The user defines
//     a local fan-out array in impl/<Node>_handlers.cc and iterates
//     it with the explicit per-peer cast.
//
//   - No PSP bus-side metadata (CAN id, FlexRay slot). PSP goes
//     `cast(*this, msg, netgraph::gateway)` — the gateway daemon
//     translates from its own per-bus PSP netgraph (loaded as
//     JSON; see artheia/generators/psp_netgraph.py).
//
//   - No cluster-wide address book. The supervisor daemon loads
//     the whole cluster netgraph as JSON for its GUI / stats view;
//     apps only know the peers their .art connects them to.
//
// TIPC is a cluster protocol — the kernel discovers nodes over
// Ethernet, so a constexpr TipcAddr resolves transparently across
// machines. No host-vs-cluster routing logic needed here.

#pragma once

#include "NodeRef.hh"   // TipcAddr + cast(Daemon&,Msg,TipcAddr); RemoteRef<>

namespace demo::netgraph {



// Peer CounterNode (reached from ObserverNode's outbound connects).
//
// Cast (fire-and-forget): cast(*this, msg, netgraph::counternode).
inline constexpr ::theia::runtime::TipcAddr counternode = {
    0xd0010001u, 0u, "counter"
};
// Call (sync request/reply): a RemoteRef the caller declares + connect()s,
//   netgraph::CounterNodeRef ref; ref.connect();
//   auto r = ::theia::runtime::call<Reply>(ref, req, act, timeout_ms);
// RemoteRef tags its trace with the peer's kNodeName only, so a tiny
// local peer-tag suffices — no need to pull in the peer node's full lib
// header (which, cross-process, isn't even in this app's tree).
struct CounterNode_peer {
    static constexpr const char* kNodeName = "counter";
};
using CounterNodeRef =
    ::theia::runtime::RemoteRef<CounterNode_peer, 0xd0010001u, 0u>;



}  // namespace demo::netgraph
