// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/com/system/com/package.art
//
// Lib slice — class declaration for ONE runnable node (.art `node
// runnable`). A runnable is a GenRunnable free worker: it owns a thread and
// runs its own loop (typically a blocking server, e.g. a gRPC proxy) rather
// than reacting to a message mailbox. User code lives in
// impl/ComGrpcProxy_handlers.cc (the do_* bodies). Regenerated on every
// gen-app run.

#pragma once

#include "GenRunnable.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag

#include <cstdint>

namespace ara::com {


// ---- ComGrpcProxy (runnable) -----------------------------------------------

class ComGrpcProxy : public ::theia::runtime::GenRunnable<ComGrpcProxy> {
public:
    static constexpr const char* kNodeName = "com_grpc_proxy";
    static constexpr uint32_t kTipcType     = 0x80010009u;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting (per .art `reporting`). The base
    // adds NO heartbeat thread — if reporting, do_loop() must beat itself
    // (write it as `while (!stop_requested()) { ...; beat(); }`). The
    // generated do_loop stub below is a cooperative skeleton ready for that.
    static constexpr bool kReporting = false;

    // ---- the runnable contract (bodies in impl) -----------------------
    //   do_start() — one-time setup on the worker thread (build/start the
    //                server, open sockets, …). Optional; default no-op.
    //   do_loop()  — the body, runs until it returns. For a blocking server
    //                call do_stop() must unblock it; for a polling loop use
    //                `while (!stop_requested()) { … }`. Required.
    //   do_stop()  — release + signal the loop to end (server->Shutdown()).
    //                Optional; default no-op.
    void do_start();
    void do_loop();
    void do_stop();
};

}  // namespace ara::com
