// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/supervisor/component.art
//
// FC-wide inbound RemoteCodec specializations (#387).
//
// register_call / register_cast on a reporting node's config service
// need a RemoteCodec<T> for every inbound type. This header declares
// ONE THEIA_DECLARE_REMOTE_CODEC per inbound (receiver-port data /
// server-op req+rep) type, deduplicated across EVERY node in the FC.
//
// It lives in one header — not per-node — so that when two nodes in
// the same FC share an inbound type (e.g. com's ComDaemon and the
// test ProbeDaemon both take ComEmpty), the codec specialization is
// declared exactly once even though main.cc includes both node
// headers. Each node header #includes this (guarded by #pragma once),
// so a node header used standalone still has its codecs.
//
// A codec keys its service_id on the proto type name in the message's
// DEFINING package — so an inbound type imported from another package
// (e.g. a PSP bus PDU) declares its codec under that package's name,
// matching the sender. The #include set below covers every defining
// package an inbound type comes from.

#pragma once

#include "RemoteCodec.hh"   // THEIA_DECLARE_REMOTE_CODEC
#include "system/supervisor/supervisor.pb.h"




THEIA_DECLARE_REMOTE_CODEC(system_supervisor_GetTreeRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_TreeSnapshot)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_GetChildRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_ChildState)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_StartChildRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_ControlReply)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_DeleteChildRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_ChildSelector)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_Stop)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_GetSystemInfoRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_SystemInfo)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_ConfigureTraceRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_GetTraceConfigRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_TraceConfigList)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_ConfigureLogLevelRequest)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_HeartbeatReport)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_SendTimeoutReport)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_SupervisionEvent)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_HealthBeacon)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_SnapshotBegin)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_NodeEdge)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_NodeState)
THEIA_DECLARE_REMOTE_CODEC(system_supervisor_SnapshotEnd)
