"""AUTO-GENERATED from system/services/cluster.art, DO NOT EDIT (regen via gen-manifest).

A base :class:`DeploymentLayer` on the orthogonal-ARA engine
(:mod:`artheia.manifest.deployment`). Each cluster member maps to one
EXECUTION-axis process; provided interfaces map to SERVICE-axis instances.

``machine`` is intentionally LEFT OPEN on every process: this is a BASE
manifest — a deploy variant binds each process to a machine (see
``manifest/demo/single.py`` for the override idiom). ``validate()`` of THIS
base therefore reports ``machine`` Undefined; that is expected — the variant
makes it consistent.

Authoring style: inline + literal. The process / service rows ARE the table.
"""
from __future__ import annotations

from artheia.manifest.algebra import Default, Explicit
from artheia.manifest.deployment import (
    ApplicationLayer,
    ApplicationSetLayer,
    DeploymentLayer,
    ExecutionLayer,
    ProcessLayer,
    ServiceInstanceLayer,
    ServiceLayer,
)

DEPLOYMENT = DeploymentLayer(
    execution=ExecutionLayer(processes={
        ProcessLayer(
            name='com', executable=Explicit('//services/com/main:com'),
            start_cmd=Explicit('bin/com'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='crypto', executable=Explicit('//services/crypto/main:crypto'),
            start_cmd=Explicit('bin/crypto'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='diag', executable=Explicit('//services/diag/main:diag'),
            start_cmd=Explicit('bin/diag'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='fw', executable=Explicit('//services/fw/main:fw'),
            start_cmd=Explicit('bin/fw'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='idsm', executable=Explicit('//services/idsm/main:idsm'),
            start_cmd=Explicit('bin/idsm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='log', executable=Explicit('//services/log/main:log'),
            start_cmd=Explicit('bin/log'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='nm', executable=Explicit('//services/nm/main:nm'),
            start_cmd=Explicit('bin/nm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='osi', executable=Explicit('//services/osi/main:osi'),
            start_cmd=Explicit('bin/osi'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='per', executable=Explicit('//services/per/main:per'),
            start_cmd=Explicit('bin/per'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='phm', executable=Explicit('//services/phm/main:phm'),
            start_cmd=Explicit('bin/phm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='rds', executable=Explicit('//services/rds/main:rds'),
            start_cmd=Explicit('bin/rds'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='sm', executable=Explicit('//services/sm/main:sm'),
            start_cmd=Explicit('bin/sm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='tsync', executable=Explicit('//services/tsync/main:tsync'),
            start_cmd=Explicit('bin/tsync'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='ucm', executable=Explicit('//services/ucm/main:ucm'),
            start_cmd=Explicit('bin/ucm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='shwa', executable=Explicit('//services/shwa/main:shwa'),
            start_cmd=Explicit('bin/shwa'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
    }),
    applications=ApplicationSetLayer(applications={
        # one AA bundling every process; host bound by the variant.
        ApplicationLayer(name='services', processes={'com', 'crypto', 'diag', 'fw', 'idsm', 'log', 'nm', 'osi', 'per', 'phm', 'rds', 'sm', 'tsync', 'ucm', 'shwa'}),
    }),
)


# Per-process supervisor metadata (modules + nodes) resolved from
# the .art at gen-manifest time. serialize-manifest folds this into the
# executor.json worker leaves. DeploymentLayer stays transport-free.
PROCESS_NODES = {   'com': {   'modules': ['services/com'],
               'nodes': [   {   'name': 'com_daemon',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010008'},
                            {   'name': 'com_grpc_proxy',
                                'reporting': False,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010009'}]},
    'crypto': {   'modules': ['services/crypto'],
                  'nodes': [   {   'name': 'crypto_provider',
                                   'reporting': True,
                                   'tipc_instance': '0',
                                   'tipc_type': '0x80010006'}]},
    'diag': {   'modules': ['services/diag'],
                'nodes': [   {   'name': 'doip_server',
                                 'reporting': False,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x80010017'},
                             {   'name': 'uds_router',
                                 'reporting': True,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x80010018'}]},
    'fw': {   'modules': ['services/fw'],
              'nodes': [   {   'name': 'fw_daemon',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x80010011'}]},
    'idsm': {   'modules': ['services/idsm'],
                'nodes': [   {   'name': 'idsm_daemon',
                                 'reporting': True,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x8001000F'}]},
    'log': {   'modules': ['services/log'],
               'nodes': [   {   'name': 'log_daemon',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010003'},
                            {   'name': 'log_pump',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010023'},
                            {   'name': 'trace_pump',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010013'}]},
    'nm': {   'modules': ['services/nm'],
              'nodes': [   {   'name': 'nm_daemon',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001002E'},
                           {   'name': 'nm_poller',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x80010004'},
                           {   'name': 'nm_cfg_gate',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001002F'},
                           {   'name': 'nm_cfg_txn',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x80010030'}]},
    'osi': {   'modules': ['services/osi'],
               'nodes': [   {   'name': 'osi_ctl',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001000C'}]},
    'per': {   'modules': ['services/per'],
               'nodes': [   {   'name': 'per_client',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010007'},
                            {   'name': 'per_manager',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010016'}]},
    'phm': {   'modules': ['services/phm'],
               'nodes': [   {   'name': 'phm_fsm',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010065'},
                            {   'name': 'phm_gate',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010075'}]},
    'rds': {   'modules': ['services/rds'],
               'nodes': [   {   'name': 'roudi',
                                'reporting': False,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010099'},
                            {   'name': 'ctl',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010098'}]},
    'shwa': {   'modules': ['services/shwa'],
                'nodes': [   {   'name': 'shwa_daemon',
                                 'reporting': True,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x80010012'}]},
    'sm': {   'modules': ['services/sm'],
              'nodes': [   {   'name': 'sm_daemon',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001000D'},
                           {   'name': 'sm_gate',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001001D'},
                           {   'name': 'fg_sm',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001003D'},
                           {   'name': 'fg_gate',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001004D'}]},
    'tsync': {   'modules': ['services/tsync'],
                 'nodes': [   {   'name': 'ptp4l',
                                  'reporting': False,
                                  'tipc_instance': '0',
                                  'tipc_type': '0x80010035'},
                              {   'name': 'phc2sys',
                                  'reporting': False,
                                  'tipc_instance': '0',
                                  'tipc_type': '0x80010045'},
                              {   'name': 'tsync_ctl',
                                  'reporting': True,
                                  'tipc_instance': '0',
                                  'tipc_type': '0x80010005'}]},
    'ucm': {   'modules': ['services/ucm'],
               'nodes': [   {   'name': 'ucm_daemon',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001000E'},
                            {   'name': 'ucm_gate',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001003E'},
                            {   'name': 'ucm_fsm',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001001E'}]}}


# Per-process static params defaults derived from the .art at
# gen-manifest time. serialize-manifest emits config/<fc>.json per
# machine from this — no .art backtrack needed at install/deploy time.
PROCESS_PARAMS = {   'com': {'nodes': {}, 'package': 'system.services.com'},
    'crypto': {   'nodes': {'crypto_provider': {'ctx_idle_ms': 30000}},
                  'package': 'system.services.crypto'},
    'diag': {'nodes': {}, 'package': 'system.services.diag'},
    'fw': {'nodes': {}, 'package': 'system.services.fw'},
    'idsm': {'nodes': {}, 'package': 'system.services.idsm'},
    'log': {'nodes': {}, 'package': 'system.services.log'},
    'nm': {'nodes': {}, 'package': 'system.services.nm'},
    'osi': {'nodes': {}, 'package': 'system.services.osi'},
    'per': {   'const': {'per_client': ['etcd_endpoint']},
               'nodes': {   'per_client': {   'etcd_endpoint': '127.0.0.1:2379',
                                              'push_connect_ms': 250},
                            'per_manager': {'snapshot_dir': '/tmp/theia/dbbackup'}},
               'package': 'system.services.per'},
    'phm': {'nodes': {}, 'package': 'system.services.phm'},
    'rds': {'nodes': {}, 'package': 'system.services.rds'},
    'shwa': {'nodes': {}, 'package': 'system.services.shwa'},
    'sm': {'nodes': {}, 'package': 'system.services.sm'},
    'tsync': {   'nodes': {   'phc2sys': {'args': '-a -r -m -q', 'enabled': True},
                              'ptp4l': {'args': '-i ptpIf0 -s -m -q', 'enabled': True},
                              'tsync_ctl': {   'gps_baud': 460800,
                                               'gps_serial_dev': '',
                                               'poll_ms': 100}},
                 'package': 'system.services.tsync'},
    'ucm': {'nodes': {}, 'package': 'system.services.ucm'}}


# Per-process etcd config-defaults derived from the .art at
# gen-manifest time. serialize-manifest emits config-defaults.json per
# machine for the first-boot etcd seed (migration/seed.py).
PROCESS_CONFIG_DEFAULTS = {   'com': {'configs': {}, 'package': 'system.services.com'},
    'crypto': {   'configs': {   'crypto_provider': {   'art_package': 'system.services.crypto',
                                                        'config_type': 'CryptoConfig',
                                                        'digest': 'cfg_fdf4e93c22c0a095',
                                                        'proto_type': 'system_services_crypto_CryptoConfig',
                                                        'values': {   'ca_subject': '/O=Theia/CN=',
                                                                      'cert_generation': 0,
                                                                      'cert_ttl_days': 825,
                                                                      'hsm_device': '',
                                                                      'slot_dir': '/etc/theia/crypto',
                                                                      'slot_providers': ''}}},
                  'package': 'system.services.crypto'},
    'diag': {   'configs': {   'uds_router': {   'art_package': 'system.services.diag',
                                                 'config_type': 'DiagConfig',
                                                 'digest': 'cfg_8dd80dae14db2c0a',
                                                 'proto_type': 'system_services_diag_DiagConfig',
                                                 'values': {   'doip_port': 13400,
                                                               'ecu_address': 1,
                                                               'session_timeout_ms': 5000}}},
                'package': 'system.services.diag'},
    'fw': {   'configs': {   'fw_daemon': {   'art_package': 'system.services.fw',
                                              'config_type': 'FwConfig',
                                              'digest': 'cfg_f95749cbff58c98c',
                                              'proto_type': 'system_services_fw_FwConfig',
                                              'values': {   'default_policy': 'drop',
                                                            'dmz_tcp_ports': '7700,7710,7711,2379',
                                                            'egress_policy': '',
                                                            'egress_slice': 'theia.slice',
                                                            'enabled': True,
                                                            'forward_policy': '',
                                                            'fw_d_dir': 'config/fw.d',
                                                            'grpc_client_cidrs': '',
                                                            'log_drops': False,
                                                            'log_drops_rate': 5,
                                                            'mgmt_iface': 'eth0',
                                                            'output_policy': '',
                                                            'reassert_ms': 0,
                                                            'vpn_iface': ''}}},
              'package': 'system.services.fw'},
    'idsm': {   'configs': {   'idsm_daemon': {   'art_package': 'system.services.idsm',
                                                  'config_type': 'IdsmConfig',
                                                  'digest': 'cfg_2ae527cb19bbcc13',
                                                  'proto_type': 'system_services_idsm_IdsmConfig',
                                                  'values': {   'bpf_object_path': '',
                                                                'elf_digests': '',
                                                                'escalate_severity': 4,
                                                                'expected_listeners': 'com:7700,com:7710,com:7711',
                                                                'grpc_servers': 'com',
                                                                'mock_event_path': '',
                                                                'poll_ms': 500,
                                                                'proc_scan': True,
                                                                'ringbuf_map': 'ids_events'}}},
                'package': 'system.services.idsm'},
    'log': {'configs': {}, 'package': 'system.services.log'},
    'nm': {   'configs': {   'nm_daemon': {   'art_package': 'system.services.nm',
                                              'config_type': 'NmConfig',
                                              'digest': 'cfg_c68b003f43304690',
                                              'proto_type': 'system_services_nm_NmConfig',
                                              'values': {   'auto_connect': False,
                                                            'auto_vpn': False,
                                                            'interfaces': '',
                                                            'poll_ms': 1000,
                                                            'require_address': True,
                                                            'require_vpn': False,
                                                            'vpn_authkey': '',
                                                            'vpn_interface': ''}},
                             'nm_poller': {   'art_package': 'system.services.nm',
                                              'config_type': 'NmConfig',
                                              'digest': 'cfg_c68b003f43304690',
                                              'proto_type': 'system_services_nm_NmConfig',
                                              'values': {   'auto_connect': False,
                                                            'auto_vpn': False,
                                                            'interfaces': '',
                                                            'poll_ms': 1000,
                                                            'require_address': True,
                                                            'require_vpn': False,
                                                            'vpn_authkey': '',
                                                            'vpn_interface': ''}}},
              'package': 'system.services.nm'},
    'osi': {   'configs': {   'osi_ctl': {   'art_package': 'system.services.osi',
                                             'config_type': 'OsiConfig',
                                             'digest': 'cfg_b3c3dec2b99b6e95',
                                             'proto_type': 'system_services_osi_OsiConfig',
                                             'values': {   'cgroup_root': '/sys/fs/cgroup',
                                                           'poll_ms': 2000,
                                                           'slice_name': 'theia.slice'}}},
               'package': 'system.services.osi'},
    'per': {'configs': {}, 'package': 'system.services.per'},
    'phm': {   'configs': {   'phm_gate': {   'art_package': 'system.services.phm',
                                              'config_type': 'PhmConfig',
                                              'digest': 'cfg_64b91bf7e9607fed',
                                              'proto_type': 'system_services_phm_PhmConfig',
                                              'values': {   'checkpoint_level': 2,
                                                            'deadline_degrade': 5,
                                                            'restart_degrade': 3,
                                                            'restart_fail': 5,
                                                            'restart_warn': 1,
                                                            'restart_window_ms': 30000}}},
               'package': 'system.services.phm'},
    'rds': {'configs': {}, 'package': 'system.services.rds'},
    'shwa': {   'configs': {   'shwa_daemon': {   'art_package': 'system.services.shwa',
                                                  'config_type': 'ShwaConfig',
                                                  'digest': 'cfg_4f48ec6b2efe1d09',
                                                  'proto_type': 'system_services_shwa_ShwaConfig',
                                                  'values': {   'jetson_clocks': False,
                                                                'persist': False,
                                                                'poll_ms': 2000,
                                                                'power_mode': 0}}},
                'package': 'system.services.shwa'},
    'sm': {'configs': {}, 'package': 'system.services.sm'},
    'tsync': {   'configs': {   'tsync_ctl': {   'art_package': 'system.services.tsync',
                                                 'config_type': 'TsyncConfig',
                                                 'digest': 'cfg_5afa9bb0eb030fc8',
                                                 'proto_type': 'system_services_tsync_TsyncConfig',
                                                 'values': {   'discipline_clock': False,
                                                               'gps_fix_timeout_ms': 3000,
                                                               'lock_offset_ns': 100000,
                                                               'poll_ms': 1000,
                                                               'ptp_domain': 0,
                                                               'ptp_interface': '',
                                                               'source': 'ptp'}}},
                 'package': 'system.services.tsync'},
    'ucm': {   'configs': {   'ucm_gate': {   'art_package': 'system.services.ucm',
                                              'config_type': 'UcmConfig',
                                              'digest': 'cfg_144bb81e70faf02b',
                                              'proto_type': 'system_services_ucm_UcmConfig',
                                              'values': {   'releases_root': '/opt/theia/releases',
                                                            'retain_releases': 3,
                                                            'verify_budget_ms': 30000}}},
               'package': 'system.services.ucm'}}
