"""AUTO-GENERATED from system/services/cluster.art, DO NOT EDIT (regen via gen-manifest).

A base :class:`DeploymentLayer` on the orthogonal-ARA engine
(:mod:`artheia.manifest.deployment`). Each cluster member maps to one
EXECUTION-axis process; provided interfaces map to SERVICE-axis instances.

``machine`` is intentionally LEFT OPEN on every process: this is a BASE
manifest — a deploy variant binds each process to a machine (see
``manifest/demo/single.py`` for the override idiom). ``validate()`` of THIS
base therefore reports ``machine`` Undefined; that is expected — the variant
makes it consistent.

Authoring style: inline + literal. The process / service rows ARE the table.
"""
from __future__ import annotations

from artheia.manifest.algebra import Default, Explicit
from artheia.manifest.deployment import (
    ApplicationLayer,
    ApplicationSetLayer,
    DeploymentLayer,
    ExecutionLayer,
    ProcessLayer,
    ServiceInstanceLayer,
    ServiceLayer,
)

DEPLOYMENT = DeploymentLayer(
    execution=ExecutionLayer(processes={
        ProcessLayer(
            name='com', executable=Explicit('//services/com/main:com'),
            start_cmd=Explicit('bin/com'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='crypto', executable=Explicit('//services/crypto/main:crypto'),
            start_cmd=Explicit('bin/crypto'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='diag', executable=Explicit('//services/diag/main:diag'),
            start_cmd=Explicit('bin/diag'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='fw', executable=Explicit('//services/fw/main:fw'),
            start_cmd=Explicit('bin/fw'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='idsm', executable=Explicit('//services/idsm/main:idsm'),
            start_cmd=Explicit('bin/idsm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='log', executable=Explicit('//services/log/main:log'),
            start_cmd=Explicit('bin/log'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='nm', executable=Explicit('//services/nm/main:nm'),
            start_cmd=Explicit('bin/nm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='osi', executable=Explicit('//services/osi/main:osi'),
            start_cmd=Explicit('bin/osi'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='per', executable=Explicit('//services/per/main:per'),
            start_cmd=Explicit('bin/per'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='phm', executable=Explicit('//services/phm/main:phm'),
            start_cmd=Explicit('bin/phm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='rds', executable=Explicit('//services/rds/main:rds'),
            start_cmd=Explicit('bin/rds'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='sm', executable=Explicit('//services/sm/main:sm'),
            start_cmd=Explicit('bin/sm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='tsync', executable=Explicit('//services/tsync/main:tsync'),
            start_cmd=Explicit('bin/tsync'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='ucm', executable=Explicit('//services/ucm/main:ucm'),
            start_cmd=Explicit('bin/ucm'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
        ProcessLayer(
            name='shwa', executable=Explicit('//services/shwa/main:shwa'),
            start_cmd=Explicit('bin/shwa'), function_group=Explicit('services'),
            fg_states={"Startup", "Running"},
        ),
    }),
    applications=ApplicationSetLayer(applications={
        # one AA bundling every process; host bound by the variant.
        ApplicationLayer(name='services', processes={'com', 'crypto', 'diag', 'fw', 'idsm', 'log', 'nm', 'osi', 'per', 'phm', 'rds', 'sm', 'tsync', 'ucm', 'shwa'}),
    }),
)


# Per-process supervisor metadata (modules + nodes) resolved from
# the .art at gen-manifest time. serialize-manifest folds this into the
# executor.json worker leaves. DeploymentLayer stays transport-free.
PROCESS_NODES = {   'com': {   'modules': ['services/com'],
               'nodes': [   {   'name': 'com_daemon',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010008'},
                            {   'name': 'com_grpc_proxy',
                                'reporting': False,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010009'}]},
    'crypto': {   'modules': ['services/crypto'],
                  'nodes': [   {   'name': 'crypto_provider',
                                   'reporting': True,
                                   'tipc_instance': '0',
                                   'tipc_type': '0x80010006'}]},
    'diag': {   'modules': ['services/diag'],
                'nodes': [   {   'name': 'doip_server',
                                 'reporting': False,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x80010017'},
                             {   'name': 'uds_router',
                                 'reporting': True,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x80010018'}]},
    'fw': {   'modules': ['services/fw'],
              'nodes': [   {   'name': 'fw_daemon',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x80010011'}]},
    'idsm': {   'modules': ['services/idsm'],
                'nodes': [   {   'name': 'idsm_daemon',
                                 'reporting': True,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x8001000F'}]},
    'log': {   'modules': ['services/log'],
               'nodes': [   {   'name': 'log_daemon',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010003'},
                            {   'name': 'log_pump',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010023'},
                            {   'name': 'trace_pump',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010013'}]},
    'nm': {   'modules': ['services/nm'],
              'nodes': [   {   'name': 'nm_daemon',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001002E'},
                           {   'name': 'nm_poller',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x80010004'}]},
    'osi': {   'modules': ['services/osi'],
               'nodes': [   {   'name': 'osi_ctl',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001000C'}]},
    'per': {   'modules': ['services/per'],
               'nodes': [   {   'name': 'per_client',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010007'},
                            {   'name': 'per_manager',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010016'}]},
    'phm': {   'modules': ['services/phm'],
               'nodes': [   {   'name': 'phm_fsm',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010065'},
                            {   'name': 'phm_gate',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010075'}]},
    'rds': {   'modules': ['services/rds'],
               'nodes': [   {   'name': 'roudi',
                                'reporting': False,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010099'},
                            {   'name': 'ctl',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x80010098'}]},
    'shwa': {   'modules': ['services/shwa'],
                'nodes': [   {   'name': 'shwa_daemon',
                                 'reporting': True,
                                 'tipc_instance': '0',
                                 'tipc_type': '0x80010012'}]},
    'sm': {   'modules': ['services/sm'],
              'nodes': [   {   'name': 'sm_daemon',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001000D'},
                           {   'name': 'sm_gate',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001001D'},
                           {   'name': 'fg_sm',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001003D'},
                           {   'name': 'fg_gate',
                               'reporting': True,
                               'tipc_instance': '0',
                               'tipc_type': '0x8001004D'}]},
    'tsync': {   'modules': ['services/tsync'],
                 'nodes': [   {   'name': 'ptp4l',
                                  'reporting': False,
                                  'tipc_instance': '0',
                                  'tipc_type': '0x80010035'},
                              {   'name': 'phc2sys',
                                  'reporting': False,
                                  'tipc_instance': '0',
                                  'tipc_type': '0x80010045'},
                              {   'name': 'tsync_ctl',
                                  'reporting': True,
                                  'tipc_instance': '0',
                                  'tipc_type': '0x80010005'}]},
    'ucm': {   'modules': ['services/ucm'],
               'nodes': [   {   'name': 'ucm_daemon',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001000E'},
                            {   'name': 'ucm_gate',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001003E'},
                            {   'name': 'ucm_fsm',
                                'reporting': True,
                                'tipc_instance': '0',
                                'tipc_type': '0x8001001E'}]}}
