// AUTO-GENERATED by `artheia gen-fc` — DO NOT EDIT.
// source: system/services/rdsdemo/package.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-fc run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/FrameProducer.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file
#include "ara/rds/stream.h"   // RDS zero-copy data plane (requires_rds nodes)

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386).
                         // GenServer nodes use bind_node + register_cast;
                         // reporting runnables use bind_listener +
                         // register_cast_inline (no mailbox).
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
                         // watchdog — every reporting node (GenServer AND
                         // runnable). Hand-framed cast, no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // Crash forensics: install the libtombstone fatal-signal handler BEFORE any
    // node starts, so a SIGSEGV/SIGABRT/etc — even during startup — writes a
    // tombstone (backtrace + maps) to $THEIA_TOMBSTONE_DIR (the supervisor sets
    // it per child). The supervisor's GetTombstone serves it back (GUI
    // "Download tombstone"). No dir set (standalone run) → handler not armed.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("rdsdemo", td);
    }

    using namespace ara::rdsdemo;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map, sourced from Process.log_level on the
    // rig). Defaults to Info when unset/unparseable. Applied to every node's
    // logger below. The SINK kind comes from THEIA_LOGGER (MakeContextLogger).
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON ONCE,
    // before any node is constructed, so a node's ctor / init() can read its
    // knobs via ::theia::runtime::get_config().node(kNodeName).u32(...). A
    // missing file is fine — every lookup falls back to the caller's default.
    // Path from $THEIA_CONFIG / $THEIA_CONFIG_DIR / ./config/rdsdemo.json.
    ::theia::runtime::init_config("rdsdemo");

    // RDS (Raw Data Stream): register this process with the iceoryx broker
    // (RouDi) ONCE, before any requires_rds node opens a stream. The node's
    // StreamWriter/Reader handles (one per `rds_stream`) connect in its init().
    ::ara::rds::Runtime::Init("rdsdemo");

    ::theia::runtime::TimerService timers;
    // Publish the process TimerService so a `requires_timers` node's
    // handlers / init() reach it via process_timers() — mirrors
    // set_process_logger above. Set once, before any node starts.
    ::theia::runtime::set_process_timers(&timers);

    // Config-service receiver (#386). A reporting node binds its TIPC name
    // and registers the supervisor's control pushes. A GenServer node's cast
    // lands in its base handle_cast on the node thread; a reporting runnable
    // (no mailbox) takes them INLINE on the mux thread (register_cast_inline).
    // Same standard GwMessageHeader path as any app message — no bespoke frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);

    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below. The supervisor watchdog only watches nodes that
    // beat, so non-reporting nodes simply never appear here.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    FrameProducer frame_producer;
    // Per-node logger: tagged [#frame_producer] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto frame_producer_log = MakeContextLogger(FrameProducer::kNodeName);
        frame_producer_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(frame_producer_log);
        frame_producer.set_logger(std::move(frame_producer_log));
    }
    frame_producer.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(frame_producer.native_handle(),
        FrameProducer::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      FrameProducer::kTipcType, FrameProducer::kTipcInstance);
        frame_producer.log().info(_tipc);
    }

    if (auto* frame_producer_cfg = config_mux.bind_node(
            frame_producer, FrameProducer::kTipcType,
            FrameProducer::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            frame_producer_cfg, frame_producer);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            frame_producer_cfg, frame_producer);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            frame_producer_cfg, frame_producer);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
    } else {
        frame_producer.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto frame_producer_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(FrameProducer::kNodeName);
        if (frame_producer_hb->open()) {
            frame_producer_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(frame_producer_hb));
        } else {
            frame_producer.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    frame_producer.stop("signal");

    return 0;
}
