// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/sm/package.art
//
// Lib slice (STATEM variant) — message wiring + GenStateM-derived
// daemon class for ONE node. Regenerated on every gen-app run. User
// edits land in impl/FunctionGroupSm_handlers.cc.
//
// This template is the statem-aware sibling of Daemon.hh.j2 — it
// fires when this node's .art NodeDecl carries a `statem { ... }`
// block. The daemon derives from ::theia::runtime::GenStateM<T,S,D> and
// the transition table is encoded as switch-on-state per event type
// (one handle_event overload per declared event type).

#pragma once

#include "GenStateM.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "sm_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/sm/sm.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::sm {



// ---- FunctionGroupSm state machine ------------------------------------

// State enum: one entry per `.art statem.states [...]`, in declared
// order. Underlying type is uint8_t to match the gen_statem template
// + minimize per-event payload overhead.
enum class FunctionGroupSmState : uint8_t {
    FG_OFF = 0,
    FG_STARTUP = 1,
    FG_RUNNING = 2,
    FG_SHUTDOWN = 3,
    FG_RESTART = 4
};

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_sm_*); aliasing them here keeps callers'
// signatures readable.
using FgStatusMsg = system_services_sm_FgStatusMsg;

using FgStart = system_services_sm_FgStart;
using FgStarted = system_services_sm_FgStarted;
using FgStop = system_services_sm_FgStop;
using FgDegraded = system_services_sm_FgDegraded;
using FgStopped = system_services_sm_FgStopped;
using FgRetry = system_services_sm_FgRetry;


using FunctionGroupSmData = FgStatusMsg;

// Subscribers (one type per sender-port data element). Free-functions
// so the daemon stays delivery-flavor agnostic. on_enter — declared
// in impl — typically broadcasts the new state to these.
using BroadcastFg_stateSubscriber =
    std::function<void(const FgStatusMsg&)>;


// Forward-declare the user-facing daemon so the GenStateM template
// can be instantiated below (CRTP).
class FunctionGroupSm;

// FunctionGroupSm — GenStateM-derived FSM daemon.
//
// Generated members:
//   - init(FunctionGroupSmData&) returns the initial state
//     (FunctionGroupSmState::FG_OFF)
//   - one handle_event overload per declared event type
//     (FgStart, FgStarted, , FgStop, FgDegraded, FgStopped, FgRetry)
//   - handle_event for ::theia::runtime::StateTimeoutMsg<FunctionGroupSmState>
//     covering states with `timeout → ...` rules
//   - subscribe/unsubscribe/broadcast helpers for sender ports
//
// User-overridable (in impl/):
//   - on_enter(new, old, data) — side effects (broadcast, log, persist)
//   - any handle_event overload (if the static table needs a guard)
class FunctionGroupSm : public ::theia::runtime::GenStateM<FunctionGroupSm,
                                                       FunctionGroupSmState,
                                                       FunctionGroupSmData> {
public:
    static constexpr const char* kNodeName = "fg_sm";
    static constexpr uint32_t kTipcType     = 0x8001003Du;
    static constexpr uint32_t kTipcInstance = 0u;

    // State enum → its .art name. The GenStateM base calls this when it emits
    // a STATEM trace so the record carries from/to state names (OFF→STARTING),
    // not just the bare ordinal — what `tdb tracecat` / the GUI / rf assert on.
    static const char* state_name(FunctionGroupSmState s) {
        switch (s) {
        case FunctionGroupSmState::FG_OFF: return "FG_OFF";
        case FunctionGroupSmState::FG_STARTUP: return "FG_STARTUP";
        case FunctionGroupSmState::FG_RUNNING: return "FG_RUNNING";
        case FunctionGroupSmState::FG_SHUTDOWN: return "FG_SHUTDOWN";
        case FunctionGroupSmState::FG_RESTART: return "FG_RESTART";
        }
        return "?";
    }

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). See doc on the non-statem Daemon template for full
    // semantics. statem-flavour FCs use the same per-(node, msg_type)
    // filter map as plain GenServer ones.
    static constexpr bool kReporting = true;


    // ---- Trace config (reporting=true only) -----------------------
    // Delegates to the process-wide Tracer per #355; see the
    // non-statem Daemon template for full semantics.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }

    // Keep the framework's config-service handler
    // (handle_cast(LogLevelPush)) visible (#386) — a derived handle_cast
    // would otherwise hide the base overload by name, so
    // register_cast<LogLevelPush> wouldn't resolve. Same name-hiding
    // guard as the handle_event using-decl below. GenStateM derives
    // from GenServer, so the handler is inherited.
    using ::theia::runtime::GenStateM<FunctionGroupSm,
                                    FunctionGroupSmState,
                                    FunctionGroupSmData>::handle_cast;


    FunctionGroupSmState init(FunctionGroupSmData& /*d*/) {
        return FunctionGroupSmState::FG_OFF;
    }

    // Keep base-class handle_event(StateTimeoutMsg) visible — derived
    // overloads otherwise hide it (C++ name hiding).
    using ::theia::runtime::GenStateM<FunctionGroupSm,
                                    FunctionGroupSmState,
                                    FunctionGroupSmData>::handle_event;




    // FgStart — handled from: FG_OFF → FG_STARTUP
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStart& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_OFF) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_STARTUP);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgStarted — handled from: FG_STARTUP → FG_RUNNING
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStarted& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_STARTUP) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_RUNNING);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgStop — handled from: FG_RUNNING → FG_SHUTDOWN
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStop& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_RUNNING) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_SHUTDOWN);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgDegraded — handled from: FG_RUNNING → FG_RESTART
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgDegraded& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_RUNNING) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_RESTART);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgStopped — handled from: FG_SHUTDOWN → FG_OFF
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStopped& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_SHUTDOWN) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_OFF);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgRetry — handled from: FG_RESTART → FG_STARTUP after 5000ms
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgRetry& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_RESTART) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_STARTUP, 5000);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }





    // ---- on_enter — defined in impl/ (user owns side effects)
    void on_enter(FunctionGroupSmState new_s, FunctionGroupSmState old_s,
                   FunctionGroupSmData& d);

    // ---- Subscriber registration (per sender-port data element) --------

    uint32_t subscribe_broadcast_fg_state(
        BroadcastFg_stateSubscriber s);
    void     unsubscribe_broadcast_fg_state(uint32_t id);
    void     broadcast_broadcast_fg_state(const FgStatusMsg& msg);


    // ---- Server-port operations (one per unique handler signature) — impl
    //
    // Deduplicated by (req_msg, rep_msg): when two server ports
    // share an interface (e.g. ctl_tdb + ctl_com both providing
    // TraceControl), the handler signature is identical and only
    // gets emitted once. Dispatch is by request type, not by port.


private:

    struct BroadcastFg_stateEntry {
        uint32_t id;
        BroadcastFg_stateSubscriber fn;
    };
    std::mutex broadcast_fg_state_mu_;
    uint32_t broadcast_fg_state_next_id_{1};
    std::vector<BroadcastFg_stateEntry>
        broadcast_fg_state_subs_;

};

// Subscriber + broadcast inline impls — pure boilerplate; kept in
// lib because they're per-instance bookkeeping with no policy.

inline uint32_t FunctionGroupSm::subscribe_broadcast_fg_state(
        BroadcastFg_stateSubscriber s) {
    std::lock_guard<std::mutex> lk(broadcast_fg_state_mu_);
    uint32_t id = broadcast_fg_state_next_id_++;
    broadcast_fg_state_subs_.push_back({id, std::move(s)});
    return id;
}

inline void FunctionGroupSm::unsubscribe_broadcast_fg_state(uint32_t id) {
    std::lock_guard<std::mutex> lk(broadcast_fg_state_mu_);
    auto& v = broadcast_fg_state_subs_;
    v.erase(std::remove_if(v.begin(), v.end(),
              [id](const auto& e) { return e.id == id; }), v.end());
}

inline void FunctionGroupSm::broadcast_broadcast_fg_state(const FgStatusMsg& msg) {
    std::vector<BroadcastFg_stateEntry> snap;
    {
        std::lock_guard<std::mutex> lk(broadcast_fg_state_mu_);
        snap = broadcast_fg_state_subs_;
    }
    for (const auto& e : snap) {
        try { e.fn(msg); }
        catch (...) {
            std::fprintf(stderr,
                "[%s] subscriber %u threw on broadcast.fg_state — dropping\n",
                kNodeName, e.id);
        }
    }
}




}  // namespace ara::sm


