// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/sm/component.art
//
// Lib slice (STATEM variant) — message wiring + GenStateM-derived
// daemon class for ONE node. Regenerated on every gen-app run. User
// edits land in impl/FunctionGroupSm_handlers.cc.
//
// This template is the statem-aware sibling of Daemon.hh.j2 — it
// fires when this node's .art NodeDecl carries a `statem { ... }`
// block. The daemon derives from ::theia::runtime::GenStateM<T,S,D> and
// the transition table is encoded as switch-on-state per event type
// (one handle_event overload per declared event type).

#pragma once

#include "GenStateM.hh"
#include "NodeRef.hh"   // TipcAddr (PG plumbing)
#include "PgClient.hh"  // OTP-pg broadcast fan-out (sender-port broadcast_*)
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "sm_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/sm/sm.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::sm {



// ---- FunctionGroupSm state machine ------------------------------------

// State enum: one entry per `.art statem.states [...]`, in declared
// order. Underlying type is uint8_t to match the gen_statem template
// + minimize per-event payload overhead.
enum class FunctionGroupSmState : uint8_t {
    FG_OFF = 0,
    FG_STARTUP = 1,
    FG_RUNNING = 2,
    FG_SHUTDOWN = 3,
    FG_RESTART = 4
};

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_sm_*); aliasing them here keeps callers'
// signatures readable.
using FgStatusMsg = system_services_sm_FgStatusMsg;

using FgStart = system_services_sm_FgStart;
using FgStarted = system_services_sm_FgStarted;
using FgStop = system_services_sm_FgStop;
using FgDegraded = system_services_sm_FgDegraded;
using FgStopped = system_services_sm_FgStopped;
using FgRetry = system_services_sm_FgRetry;


using FunctionGroupSmData = FgStatusMsg;

// (Subscriber-list / gen_event RETIRED — on_enter broadcasts the new state via
// the sender-port broadcast_*(), which is PURE PG multicast. Consumers pg_join
// the state message's group.)

// Forward-declare the user-facing daemon so the GenStateM template
// can be instantiated below (CRTP).
class FunctionGroupSm;

// FunctionGroupSm — GenStateM-derived FSM daemon.
//
// Generated members:
//   - init(FunctionGroupSmData&) returns the initial state
//     (FunctionGroupSmState::FG_OFF)
//   - one handle_event overload per declared event type
//     (FgStart, FgStarted, , FgStop, FgDegraded, FgStopped, FgRetry)
//   - handle_event for ::theia::runtime::StateTimeoutMsg<FunctionGroupSmState>
//     covering states with `timeout → ...` rules
//   - subscribe/unsubscribe/broadcast helpers for sender ports
//
// User-overridable (in impl/):
//   - on_enter(new, old, data) — side effects (broadcast, log, persist)
//   - any handle_event overload (if the static table needs a guard)
class FunctionGroupSm : public ::theia::runtime::GenStateM<FunctionGroupSm,
                                                       FunctionGroupSmState,
                                                       FunctionGroupSmData> {
public:
    static constexpr const char* kNodeName = "fg_sm";
    static constexpr uint32_t kTipcType     = 0x8001003Du;
    static constexpr uint32_t kTipcInstance = 0u;

    // State enum → its .art name. The GenStateM base calls this when it emits
    // a STATEM trace so the record carries from/to state names (OFF→STARTING),
    // not just the bare ordinal — what `tdb tracecat` / the GUI / rf assert on.
    static const char* state_name(FunctionGroupSmState s) {
        switch (s) {
        case FunctionGroupSmState::FG_OFF: return "FG_OFF";
        case FunctionGroupSmState::FG_STARTUP: return "FG_STARTUP";
        case FunctionGroupSmState::FG_RUNNING: return "FG_RUNNING";
        case FunctionGroupSmState::FG_SHUTDOWN: return "FG_SHUTDOWN";
        case FunctionGroupSmState::FG_RESTART: return "FG_RESTART";
        }
        return "?";
    }

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). See doc on the non-statem Daemon template for full
    // semantics. statem-flavour FCs use the same per-(node, msg_type)
    // filter map as plain GenServer ones.
    static constexpr bool kReporting = true;


    // ---- Trace config (reporting=true only) -----------------------
    // Delegates to the process-wide Tracer per #355; see the
    // non-statem Daemon template for full semantics.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }

    // ---- process groups (pg): MANUAL pub/sub over TIPC nameseq multicast ----
    // Same model as the non-statem Daemon template: group identity =
    // msg_type_name<T>() (the .art wire name); the supervisor allocates the
    // group's TIPC type + a unique instance; broadcast_*() multicasts ONE
    // datagram to the whole group. A consumer pg_join<T>()s from init(); a
    // broadcaster pg_resolve<T>()s the type (cached). See [[project-pg-broadcast-model]].
    void pg_attach(const char* node_name, ::theia::runtime::NodeBinding* b) {
        pg_.attach(node_name, b);
    }
    template <typename T> ::theia::runtime::PgClient::Group pg_join() {
        return pg_.join<T>();
    }
    template <typename T> ::theia::runtime::PgClient::Group pg_resolve() {
        if (!pg_groups_[::theia::runtime::RemoteCodec<T>::service_id].ok)
            pg_groups_[::theia::runtime::RemoteCodec<T>::service_id] = pg_.resolve<T>();
        return pg_groups_[::theia::runtime::RemoteCodec<T>::service_id];
    }
    template <typename T> void pg_leave() { pg_.leave<T>(); }
    template <typename T>
    void pg_broadcast(uint32_t group_type, const T& msg) {
        uint8_t _buf[8192];
        pb_ostream_t _os = pb_ostream_from_buffer(_buf, sizeof(_buf));
        if (!pb_encode(&_os, ::theia::runtime::RemoteCodec<T>::fields(), &msg))
            return;
        pg_.broadcast<T>(group_type, _buf,
                         static_cast<uint16_t>(_os.bytes_written));
    }

    // Keep the framework's config-service handler
    // (handle_cast(LogLevelPush)) visible (#386) — a derived handle_cast
    // would otherwise hide the base overload by name, so
    // register_cast<LogLevelPush> wouldn't resolve. Same name-hiding
    // guard as the handle_event using-decl below. GenStateM derives
    // from GenServer, so the handler is inherited.
    using ::theia::runtime::GenStateM<FunctionGroupSm,
                                    FunctionGroupSmState,
                                    FunctionGroupSmData>::handle_cast;


    FunctionGroupSmState init(FunctionGroupSmData& /*d*/) {
        return FunctionGroupSmState::FG_OFF;
    }

    // Keep base-class handle_event(StateTimeoutMsg) visible — derived
    // overloads otherwise hide it (C++ name hiding).
    using ::theia::runtime::GenStateM<FunctionGroupSm,
                                    FunctionGroupSmState,
                                    FunctionGroupSmData>::handle_event;




    // FgStart — handled from: FG_OFF → FG_STARTUP
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStart& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_OFF) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_STARTUP);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgStarted — handled from: FG_STARTUP → FG_RUNNING
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStarted& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_STARTUP) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_RUNNING);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgStop — handled from: FG_RUNNING → FG_SHUTDOWN
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStop& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_RUNNING) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_SHUTDOWN);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgDegraded — handled from: FG_RUNNING → FG_RESTART
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgDegraded& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_RUNNING) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_RESTART);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgStopped — handled from: FG_SHUTDOWN → FG_OFF
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgStopped& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_SHUTDOWN) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_OFF);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }

    // FgRetry — handled from: FG_RESTART → FG_STARTUP after 5000ms
    ::theia::runtime::EventResult<FunctionGroupSmState> handle_event(
            FunctionGroupSmState s, const FgRetry& /*e*/,
            FunctionGroupSmData& /*d*/) {
        if (s == FunctionGroupSmState::FG_RESTART) {
            return ::theia::runtime::transition_to<FunctionGroupSmState>(
                FunctionGroupSmState::FG_STARTUP, 5000);
        }
        return ::theia::runtime::keep_state<FunctionGroupSmState>();
    }





    // ---- on_enter — defined in impl/ (user owns side effects)
    void on_enter(FunctionGroupSmState new_s, FunctionGroupSmState old_s,
                   FunctionGroupSmData& d);

    // ---- Broadcast senders (per sender-port data element) — PG multicast --

    void     broadcast_broadcast_fg_state(const FgStatusMsg& msg);


    // ---- Server-port operations (one per unique handler signature) — impl
    //
    // Deduplicated by (req_msg, rep_msg): when two server ports
    // share an interface (e.g. ctl_tdb + ctl_com both providing
    // TraceControl), the handler signature is identical and only
    // gets emitted once. Dispatch is by request type, not by port.


private:
    // The node's PG client + broadcaster group-type cache (see the non-statem
    // Daemon template). Idle until the first pg_join/broadcast.
    ::theia::runtime::PgClient pg_;
    std::map<uint16_t, ::theia::runtime::PgClient::Group> pg_groups_;
};

// Broadcast fan-out — PG name-sequence multicast (one datagram → the whole
// group). Kept in lib (auto-generated); the user touches on_enter/handle_* only.

inline void FunctionGroupSm::broadcast_broadcast_fg_state(const FgStatusMsg& msg) {
    // group identity = msg_type_name<FgStatusMsg>() (the .art wire name); the
    // supervisor allocates group_type on first resolve. Members pg_join the same
    // type → register_cast<FgStatusMsg> delivers it to their handle_cast.
    auto _g = pg_resolve<FgStatusMsg>();
    if (!_g.ok) return;                       // supervisor unreachable — drop
    pg_broadcast<FgStatusMsg>(_g.type, msg);
}




}  // namespace ara::sm


