// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/system/sm/package.art
//
// Per-node signal routing table. ".art compositions + clusters say
// which signal lands at which TIPC address" — projected into a
// constexpr lookup so the runtime cast() path doesn't need any
// service discovery or subscription handshake.
//
// Format reminder (see docs/tasks/PROGRESS/netgraph-signal-routing):
//   - Each outbound signal has a constexpr TipcAddr[] of destinations.
//     Fan-out (sm → exec/com/ucm/per) is multiple entries.
//   - PSP signals would name the gateway as the single destination
//     (no bus-side detail at the app layer); per-bus PSP catalog
//     lives in `gateway_netgraph.py` output and is consumed by the
//     supervisor, not by the app.
//   - TIPC is a cluster protocol — the kernel resolves destinations
//     transparently across machines, so there's no host-vs-cluster
//     distinction in this table.

#pragma once

#include <cstdint>
#include <cstddef>

namespace ara::sm::netgraph {

// One TIPC endpoint. The kernel handles cluster-wide node discovery
// over Ethernet; this struct is just the address pair that's
// declared in each node's .art.
struct TipcAddr {
    uint32_t type;
    uint32_t instance;
};



}  // namespace ara::sm::netgraph
