// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/system/per/package.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/PerDaemon_handlers.cc.

#include "lib/PerDaemon.hh"

#include "TimerService.hh"

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    using namespace ara::per;

    demo::runtime::TimerService timers;
    (void)timers;  // wired into the daemon if it needs send_after

    PerDaemon per_daemon;
    per_daemon.start();
    std::fprintf(stderr, "[per_daemon] up — TIPC type=0x%x instance=%u\n",
                 PerDaemon::kTipcType, PerDaemon::kTipcInstance);


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    per_daemon.stop("signal");

    return 0;
}
