// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/vucm/component.art
//
// FC-wide inbound RemoteCodec specializations (#387).
//
// register_call / register_cast on a reporting node's config service
// need a RemoteCodec<T> for every inbound type. This header declares
// ONE THEIA_DECLARE_REMOTE_CODEC per inbound (receiver-port data /
// server-op req+rep) type, deduplicated across EVERY node in the FC.
//
// It lives in one header — not per-node — so that when two nodes in
// the same FC share an inbound type (e.g. com's ComDaemon and the
// test ProbeDaemon both take ComEmpty), the codec specialization is
// declared exactly once even though main.cc includes both node
// headers. Each node header #includes this (guarded by #pragma once),
// so a node header used standalone still has its codecs.
//
// A codec keys its service_id on the proto type name in the message's
// DEFINING package — so an inbound type imported from another package
// (e.g. a PSP bus PDU) declares its codec under that package's name,
// matching the sender. The #include set below covers every defining
// package an inbound type comes from.

#pragma once

#include "RemoteCodec.hh"   // THEIA_DECLARE_REMOTE_CODEC
#include "system/services/vucm/vucm.pb.h"

#include "system/services/sm/sm.pb.h"
#include "system/services/phm/phm.pb.h"



THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_CampaignProgress)
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_PackageManifest)
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_UcmReply)
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_ConfirmRequest)
THEIA_DECLARE_REMOTE_CODEC(system_services_ucm_CancelRequest)
THEIA_DECLARE_REMOTE_CODEC(system_services_per_GetConfigReq)
THEIA_DECLARE_REMOTE_CODEC(system_services_per_ConfigSnapshot)
THEIA_DECLARE_REMOTE_CODEC(system_services_per_PutConfigReq)
THEIA_DECLARE_REMOTE_CODEC(system_services_per_PerReply)
THEIA_DECLARE_REMOTE_CODEC(system_services_per_WatchConfigReq)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_CampaignRequest)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_CampaignReply)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_CampaignStatusReq)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_CommitRequest)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_DecisionReply)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_RollbackRequest)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvDeployment)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvPlanned)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvAuthorized)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvInstalled)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvProvisioned)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvCommit)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvValidated)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvBlocked)
THEIA_DECLARE_REMOTE_CODEC(system_services_vucm_EvFailed)
THEIA_DECLARE_REMOTE_CODEC(system_services_sm_SmStateMsg)
THEIA_DECLARE_REMOTE_CODEC(system_services_phm_PhmHealthStatus)

// FC-wide enum aliases — the enum TYPE and each VALUE inside the FC namespace, so
// impl code writes the readable `CampaignState` / `CMP_IDLE`
// instead of nanopb's double-prefixed name
// (system_services_vucm_<Enum>_<Enum>_<VALUE>). Emitted ONCE here (this header
// is #pragma once + included by every node header) — NOT per-node, so two node
// headers in one TU don't redefine them.
namespace ara::vucm {
using CampaignState = system_services_vucm_CampaignState;
inline constexpr CampaignState CMP_IDLE = system_services_vucm_CampaignState_CampaignState_CMP_IDLE;
inline constexpr CampaignState CMP_PLANNING = system_services_vucm_CampaignState_CampaignState_CMP_PLANNING;
inline constexpr CampaignState CMP_AUTHORIZING = system_services_vucm_CampaignState_CampaignState_CMP_AUTHORIZING;
inline constexpr CampaignState CMP_INSTALLING = system_services_vucm_CampaignState_CampaignState_CMP_INSTALLING;
inline constexpr CampaignState CMP_CONFIRMING = system_services_vucm_CampaignState_CampaignState_CMP_CONFIRMING;
inline constexpr CampaignState CMP_AWAITING_COMMIT = system_services_vucm_CampaignState_CampaignState_CMP_AWAITING_COMMIT;
inline constexpr CampaignState CMP_VALIDATING = system_services_vucm_CampaignState_CampaignState_CMP_VALIDATING;
inline constexpr CampaignState CMP_DONE = system_services_vucm_CampaignState_CampaignState_CMP_DONE;
inline constexpr CampaignState CMP_ROLLBACK = system_services_vucm_CampaignState_CampaignState_CMP_ROLLBACK;
}  // namespace ara::vucm
