// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/shwa/component.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/ShwaDaemon.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386)


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    using namespace ara::shwa;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map, sourced from Process.log_level on the
    // rig). Defaults to Info when unset/unparseable. Applied to every node's
    // logger below. The SINK kind comes from THEIA_LOGGER (MakeContextLogger).
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    ::theia::runtime::TimerService timers;
    (void)timers;  // no node requires_timers

    // Config-service receiver (#386). A reporting node binds its TIPC
    // name and register_cast's the supervisor's control push; the cast
    // lands in GenServer's base handle_cast(LogLevelPush) on the node
    // thread. Same standard GwMessageHeader path as any app message —
    // no bespoke control frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);


    ShwaDaemon shwa_daemon;
    // Per-node logger: tagged [#shwa_daemon] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto shwa_daemon_log = MakeContextLogger(ShwaDaemon::kNodeName);
        shwa_daemon_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(shwa_daemon_log);
        shwa_daemon.set_logger(std::move(shwa_daemon_log));
    }
    shwa_daemon.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(shwa_daemon.native_handle(),
        ShwaDaemon::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      ShwaDaemon::kTipcType, ShwaDaemon::kTipcInstance);
        shwa_daemon.log().info(_tipc);
    }

    if (auto* shwa_daemon_cfg = config_mux.bind_node(
            shwa_daemon, ShwaDaemon::kTipcType,
            ShwaDaemon::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            shwa_daemon_cfg, shwa_daemon);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            shwa_daemon_cfg, shwa_daemon);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
    } else {
        shwa_daemon.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    shwa_daemon.stop("signal");

    return 0;
}
