/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SERVICES_SERVICES_PER_PER_PB_H_INCLUDED
#define PB_SERVICES_SERVICES_PER_PER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _services_services_per_PerKey {
    pb_callback_t key;
} services_services_per_PerKey;

typedef struct _services_services_per_PerValue {
    pb_callback_t value;
    uint64_t mod_rev;
} services_services_per_PerValue;

typedef struct _services_services_per_PerPut {
    pb_callback_t key;
    pb_callback_t value;
} services_services_per_PerPut;

typedef struct _services_services_per_PerEmpty { /* empty body */
    char dummy_field;
} services_services_per_PerEmpty;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define services_services_per_PerKey_init_default {{{NULL}, NULL}}
#define services_services_per_PerValue_init_default {{{NULL}, NULL}, 0}
#define services_services_per_PerPut_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_services_per_PerEmpty_init_default {0}
#define services_services_per_PerKey_init_zero   {{{NULL}, NULL}}
#define services_services_per_PerValue_init_zero {{{NULL}, NULL}, 0}
#define services_services_per_PerPut_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_services_per_PerEmpty_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define services_services_per_PerKey_key_tag     1
#define services_services_per_PerValue_value_tag 1
#define services_services_per_PerValue_mod_rev_tag 2
#define services_services_per_PerPut_key_tag     1
#define services_services_per_PerPut_value_tag   2

/* Struct field encoding specification for nanopb */
#define services_services_per_PerKey_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1)
#define services_services_per_PerKey_CALLBACK pb_default_field_callback
#define services_services_per_PerKey_DEFAULT NULL

#define services_services_per_PerValue_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             1) \
X(a, STATIC,   SINGULAR, UINT64,   mod_rev,           2)
#define services_services_per_PerValue_CALLBACK pb_default_field_callback
#define services_services_per_PerValue_DEFAULT NULL

#define services_services_per_PerPut_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             2)
#define services_services_per_PerPut_CALLBACK pb_default_field_callback
#define services_services_per_PerPut_DEFAULT NULL

#define services_services_per_PerEmpty_FIELDLIST(X, a) \

#define services_services_per_PerEmpty_CALLBACK NULL
#define services_services_per_PerEmpty_DEFAULT NULL

extern const pb_msgdesc_t services_services_per_PerKey_msg;
extern const pb_msgdesc_t services_services_per_PerValue_msg;
extern const pb_msgdesc_t services_services_per_PerPut_msg;
extern const pb_msgdesc_t services_services_per_PerEmpty_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define services_services_per_PerKey_fields &services_services_per_PerKey_msg
#define services_services_per_PerValue_fields &services_services_per_PerValue_msg
#define services_services_per_PerPut_fields &services_services_per_PerPut_msg
#define services_services_per_PerEmpty_fields &services_services_per_PerEmpty_msg

/* Maximum encoded size of messages (where known) */
/* services_services_per_PerKey_size depends on runtime parameters */
/* services_services_per_PerValue_size depends on runtime parameters */
/* services_services_per_PerPut_size depends on runtime parameters */
#define services_services_per_PerEmpty_size      0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
