"""Demo deployment manifest — single-machine ``Demo3Way`` rig.

A worked example of the structured manifest DSL. Read it top-to-bottom:
each section builds on the one above.

    1. INPUTS      machines, platform-fabric components, and the
                   generated app binaries/processes (from
                   ``manifest/applications.py``).
    2. FC BRIDGE   ``DemoRig`` — the legacy ``Layer``/``merge_layers``
                   path. It is kept for one concrete reason: the artheia
                   FC loader only synthesises the per-FC ServiceManifests
                   while materialising a ``Rig``. The DSL spec below
                   reuses those. We pin each FC + Process to its host here.
    3. THE SPEC    ``DemoSoftware`` — the structured-DSL
                   :class:`SoftwareSpecification`, composed onto the
                   platform base with ``ServicesSoftware.mappend(...)``.
                   This is the part to copy when writing a new rig.
    4. PER-MACHINE ``CentralSoftware`` / ``CentralRig`` — the spec sliced
                   to exactly what one TARGET machine installs.

The DSL in one sentence: a :class:`SoftwareSpecification` is a record of
set-typed fields; ``base.mappend(layer)`` merges ``layer`` over ``base``
field-by-field, and a field holding ``{Append(x), Remove(y)}`` edits the
base's set rather than replacing it. See :class:`SoftwareSpecification`
for the field reference.

Exports (the module-level names other code depends on):

    DemoSoftware      the full spec — CLI ranks ``*Software`` attrs by name
    CentralSoftware   per-machine spec (central only)
    CentralRig        materialised single-machine Rig for ``executor emit``
    DemoRig, DemoLayer  legacy bridge, re-exported via manifest
"""

from __future__ import annotations

import dataclasses
from ipaddress import IPv4Address
from typing import cast

from artheia.manifest import (
    ApplicationManifest,
    CpuArchitecture,
    HardwareResource,
    OpkgArtifact,
    OsPackage,
    Layer,
    MachineManifest,
    RestartStrategy,
    Rig,
    SupervisorNode,
    SwComponent,
    VehicleIdentity,
    merge_layers,
)
from artheia.manifest.machine import CpuResource, IpEndpoint, ProcessToMachineMapping
from artheia.manifest.platform import PlatformBase
from artheia.manifest.rig import SoftwareSpecification
from artheia.manifest.applicative import Append, SetTransformTypes
from artheia.manifest.layer import Override
from services.manifest.service import ServicesSoftware

# The generated manifest for ``cluster Applications`` — one SwComponent /
# Executable / Process per Demo3Way member, paths derived from the .art.
# Regenerated by ``artheia gen-manifest``; never hand-edited.
from manifest.applications import (
    APPLICATIONS_COMPONENTS as _APP_COMPONENTS,
    APPLICATIONS_PROCESSES as DEMO_PROCESSES,
    APPLICATIONS_SHORTS as _APP_SHORTS,
)


# ===========================================================================
# 1. INPUTS — machines and components
# ===========================================================================

# The supervisor daemon, deployed as a Theia opkg with a systemd unit.
# (The gateway opkg lives in the consuming gataway_ws, not standalone theia.)
_PLATFORM_OPKG_ARTIFACTS = [
    OpkgArtifact(
        name="supervisor",
        bazel_target="//platform/supervisor/main:supervisor",
        target_dir="/opt/theia/supervisor/",
        systemd_unit="/etc/systemd/system/theia-supervisor.service",
    ),
]

# This rig is single-machine: everything lands on ``central``. The
# multi-host (central + compute) split lives in manifest/zonal_rig.py.
CentralHost = MachineManifest(
    name="central",
    hardware=HardwareResource(
        cpu=CpuResource(architecture=CpuArchitecture.X86_64),
    ),
    # services/com gRPC endpoint the GUI connects to. Loopback keeps
    # single-host bring-up working; the Docker scenario overrides it with
    # the container's bridge IP.
    com_endpoint=IpEndpoint(address=IPv4Address("127.0.0.1"), port=7700),
    # etcd from apt; supervisor as a Theia opkg. Application .ipks (FCs,
    # demo binaries) are staged later from application.yaml, not here.
    os_packages=[
        OsPackage(name="etcd-server", source="apt"),
        OsPackage(name="libsystemd0", source="apt"),
    ],
    opkg_artifacts=list(_PLATFORM_OPKG_ARTIFACTS),
)

# Back-compat alias for callers/tests that still say DemoHost.
DemoHost = CentralHost

# Platform-fabric components: the daemons that ARE the platform (from
# ``cluster Platform`` in system.art), distinct from the FCs and the demo
# binaries. Each names an opkg artifact on its target machine.
_PLATFORM_FABRIC_COMPONENTS: list[SwComponent] = [
    SwComponent(
        name="supervisor",
        bazel_target="//platform/supervisor/main:supervisor",
        owner="platform",
        art_node="system.supervisor/Supervisor",
        bazel_buildable=True,
    ),
    # The gateway SwComponent + its process + drv_sup Append are added by
    # the consuming gataway_ws rig, not here (theia.git is standalone).
]

# The Demo3Way per-process binaries (compute-bound AAs), straight from the
# generated applications.py.
DEMO_BINARIES = list(_APP_COMPONENTS)

# Legacy-path-only: the merge_layers flow wants one combined component bag.
# The DSL path below instead keeps fabric and binaries separate so each
# ApplicationManifest carries only what belongs to it.
DEMO_COMPONENTS = DEMO_BINARIES + _PLATFORM_FABRIC_COMPONENTS

# app_sup ships empty in the platform base (apps belong to the rig); this
# rig attaches its demo binaries as app_sup's children. Each child resolves
# through its Process (a real start_cmd) just like an FC leaf does.
_APP_SUP_CHILDREN = list(_APP_SHORTS)


# ===========================================================================
# 2. FC BRIDGE — DemoRig (legacy path), the source of FC service manifests
# ===========================================================================
#
# Why this still exists: the artheia FC loader synthesises one
# ServiceManifest (18 FC ServiceInstances) only as a side effect of
# materialising a Rig through merge_layers. The structured-DSL spec in
# section 3 reuses those manifests rather than re-deriving them. Once the
# loader can emit service manifests for a SoftwareSpecification directly,
# this whole section disappears.

DemoLayer = Layer(
    name="apps",
    set_vehicle=VehicleIdentity(name="apps", make="theia", model="gen_server-apps"),
    add_machines=[DemoHost],
    add_components=DEMO_COMPONENTS,
    add_executions=DEMO_PROCESSES,
    # Override (not Append) — REPLACE app_sup's empty children list with the
    # demo apps. Override does dataclasses.replace(base, **patch).
    override_supervisors=[
        Override(identity="app_sup", patch={"children": list(_APP_SUP_CHILDREN)}),
    ],
)

DemoRig: Rig = merge_layers(PlatformBase, [DemoLayer])

# Bind the platform application to the host. One application bag for the
# whole legacy rig; the supervisor splits it into the apps subtree by
# bazel_target prefix.
if DemoRig.applications:
    DemoRig.applications[0] = ApplicationManifest(
        name=DemoRig.applications[0].name,
        host_machine=DemoHost.name,
        components=DemoRig.applications[0].components,
    )

# Pin each FC's ServiceInstance to its host. The loader leaves
# remote_machine="", which makes the dist_manifest emitter fall back to
# include-everywhere — wrong for a multi-machine rig. Single-machine here,
# so every FC pins to central. (The shwa→compute pin lives in zonal_rig.)
for _sm in DemoRig.service_manifests:
    _sm.instances = [
        dataclasses.replace(_i, remote_machine=CentralHost.name)
        for _i in _sm.instances
    ]

# Pin Processes to machines via AUTOSAR §9.4 ProcessToMachineMapping. PTM
# is sparse-positive: list only deviations from the AA-host_machine default;
# unmapped Processes fall through. The supervisor-tree slicer reads these.
# Here only ``supervisor`` needs pinning (every machine runs its own
# supervisor binary; central is the host of record).
_PTM_ENTRIES = [
    ProcessToMachineMapping(name=f"ptm_{_proc}", process=_proc, machine=_mach)
    for _proc, _mach in {"supervisor": CentralHost.name}.items()
]
DemoRig.process_to_machine_mappings = (
    list(DemoRig.process_to_machine_mappings) + _PTM_ENTRIES
)


# ===========================================================================
# 3. THE SPEC — DemoSoftware (structured DSL) ← copy this for a new rig
# ===========================================================================
#
#     DemoSoftware = ServicesSoftware.mappend(DemoSpecLayer)
#
# ServicesSoftware is the platform-services base (18 FCs). DemoSpecLayer is
# the demo-specific delta. mappend merges the delta over the base
# field-by-field; same-identity Appends (e.g. platform_app) union into the
# base's element rather than replacing it.
#
# Two applications, each bound to a machine:
#   platform_app   the 18 FCs (from the base) + the platform fabric.
#   central_demo_app   the three demo binaries.
# This split is what lets Bazel emit one .ipk image per app/machine.

_PlatformAppOverlay = ApplicationManifest(
    name="platform_app",
    host_machine=CentralHost.name,
    # FCs arrive from the base via same-identity merge; we contribute the
    # platform-fabric components (supervisor), which belong on central.
    components=list(_PLATFORM_FABRIC_COMPONENTS),
)

_CentralDemoApp = ApplicationManifest(
    name="central_demo_app",
    host_machine=CentralHost.name,
    components=list(DEMO_BINARIES),
)

DemoSpecLayer = SoftwareSpecification(
    vehicle=VehicleIdentity(name="apps", make="theia", model="gen_server-apps"),

    # Add the host. (set[SetTransformTypes] cast keeps the type-checker
    # happy: each field is "concrete set | set-of-edits | Empty".)
    machines=cast(set[SetTransformTypes], {
        Append(CentralHost),
    }),

    # platform_app unions into the base's platform_app (same identity);
    # central_demo_app is new.
    applications=cast(set[SetTransformTypes], {
        Append(_PlatformAppOverlay),
        Append(_CentralDemoApp),
    }),

    # The demo Processes (with real start_cmds) join the base's FC processes.
    execution_manifests=cast(set[SetTransformTypes], {
        Append(p) for p in DEMO_PROCESSES
    }),

    # Reuse the host-pinned FC service manifests from section 2.
    service_manifests=cast(set[SetTransformTypes], {
        Append(_sm) for _sm in DemoRig.service_manifests
    }),

    # Carry the §9.4 PTM overrides through so the supervisor-tree slicer
    # sees them on the DSL path too.
    process_to_machine_mappings=cast(set[SetTransformTypes], {
        Append(_ptm) for _ptm in _PTM_ENTRIES
    }),

    # Attach the demo leaves to app_sup. The base ships app_sup with an
    # empty children list; a same-identity Append unions the leaves in
    # (matching DemoLayer.override_supervisors above).
    supervisors=cast(set[SetTransformTypes], {
        Append(SupervisorNode(
            name="app_sup",
            strategy=RestartStrategy.ONE_FOR_ONE,
            children=list(_APP_SUP_CHILDREN),
        )),
    }),
)

DemoSoftware: SoftwareSpecification = ServicesSoftware.mappend(DemoSpecLayer)


# ===========================================================================
# 4. PER-MACHINE — CentralSoftware / CentralRig
# ===========================================================================
#
# What one TARGET machine actually installs. Built STANDALONE (fresh
# per-machine lists), NOT via mappend onto ServicesSoftware — mappend would
# union with the base and drag the full FC set + platform root tree back in,
# undoing any per-machine partition. Each machine's spec therefore carries
# exactly its own slice, and "moving" an element to another machine is just
# leaving it out of this list — no explicit Remove needed.

from services.manifest.service import (  # noqa: E402
    SERVICES_COMPONENTS as _FC_COMPONENTS,
    SERVICES_PROCESSES as _FC_PROCESSES,
    SUPERVISORS as _PLATFORM_SUPERVISORS,
)

# Local-dev exclusion: this rig drives ``theia install`` (on-HOST, not
# containerised). FCs that touch the host network or need root/caps would
# disrupt a dev box, so they're dropped here. The full set runs in the
# container/target rigs (test_rig.py / zonal_rig.py) where caps + a netns
# make them safe. Dropping the component + process also prunes the
# supervisor leaf at build_supervisor_tree time.
#   nm, fw, idsm, osi, rds — host network / nftables / eBPF / cgroup / shm.
LOCAL_EXCLUDE_FCS = {"nm", "fw", "idsm", "osi", "rds"}

_central_fc_components = [c for c in _FC_COMPONENTS if c.name not in LOCAL_EXCLUDE_FCS]
_central_fc_processes = [p for p in _FC_PROCESSES if p.name not in LOCAL_EXCLUDE_FCS]
_central_app_shorts = [c.name for c in DEMO_BINARIES]

# Reuse the platform supervisor tree; only app_sup needs this rig's apps.
# (Excluded FCs stay declared under pltf_sup but, with no Process on
# central, their leaves are sliced out at build time — honest "declared but
# not running here", same mechanism shwa uses.)
_central_supervisors = [
    dataclasses.replace(s, children=list(_central_app_shorts))
    if s.name == "app_sup" else s
    for s in _PLATFORM_SUPERVISORS
]

# Drop the excluded FCs from the service manifests too, so the emitted
# service.yaml / comm-matrix don't reference an FC this rig doesn't run.
# Drop a manifest that ends up empty.
_LOCAL_SERVICE_MANIFESTS = [
    dataclasses.replace(_sm, instances=_kept)
    for _sm in DemoRig.service_manifests
    if (_kept := [i for i in _sm.instances if i.name not in LOCAL_EXCLUDE_FCS])
]


def _mk_app(name: str, host: str, components: list) -> ApplicationManifest:
    return ApplicationManifest(name=name, host_machine=host, components=list(components))


CentralSoftware: SoftwareSpecification = SoftwareSpecification(
    vehicle=VehicleIdentity(name="apps", make="theia", model="gen_server-apps"),
    machines=cast(set[SetTransformTypes], {Append(CentralHost)}),
    applications=cast(set[SetTransformTypes], {
        Append(_mk_app("platform_app", CentralHost.name,
                       _central_fc_components + _PLATFORM_FABRIC_COMPONENTS)),
        Append(_mk_app("central_app", CentralHost.name, DEMO_BINARIES)),
    }),
    execution_manifests=cast(set[SetTransformTypes], {
        Append(p) for p in (_central_fc_processes + list(DEMO_PROCESSES))
    }),
    service_manifests=cast(set[SetTransformTypes], {
        Append(_sm) for _sm in _LOCAL_SERVICE_MANIFESTS
    }),
    supervisors=cast(set[SetTransformTypes], {
        Append(s) for s in _central_supervisors
    }),
)

# Materialised rig consumed by ``artheia executor emit manifest.rig
# --rig CentralRig`` to write install/central/executor.json.
CentralRig: Rig = CentralSoftware.to_rig()
