// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: apps/system/apps/component.art
//
// Lib slice — message wiring + class declaration for ONE node. An FC
// may declare several nodes; each gets its own <Node>.hh (this file).
// Regenerated on every gen-app run. User edits land in
// impl/DriverNode_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "apps_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/apps/apps.pb.h"
// State held by the daemon — FIELDS are APP-OWNED (node behaviour, not
// derived from the .art), so the struct lives in a WRITE-ONCE impl header
// (seeded empty, never clobbered without --force) that the user fills in.
// Included at GLOBAL scope (the header opens its own `namespace
// demo`) so it isn't nested under this file's
// namespace block — bound as the GenServer State type below.
#include "impl/DriverNode_state.hh"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace demo {


// ---- DriverNode ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_apps_*); aliasing them here keeps callers'
// signatures readable.
using Inc = system_apps_Inc;
using Get = system_apps_Get;
using GetReply = system_apps_GetReply;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.
using Inc_outIncSubscriber =
    std::function<void(const Inc&)>;


class DriverNode : public ::theia::runtime::GenServer<DriverNode, DriverNodeState> {
public:
    static constexpr const char* kNodeName = "driver";
    static constexpr uint32_t kTipcType     = 0xd0010002u;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). When true, this node sends HeartbeatReport, the
    // supervisor watchdogs it, and the supervisor can push trace
    // config to it via the methods below.
    static constexpr bool kReporting = true;


    // Bring the framework's config-service handler
    // (handle_cast(LogLevelPush)) into scope (#386). A Derived
    // handle_cast for any port message would otherwise HIDE the base
    // overload by name, so register_cast<LogLevelPush> wouldn't
    // resolve. This using-decl keeps both visible; overload resolution
    // then picks the right one per message type.
    using ::theia::runtime::GenServer<DriverNode, DriverNodeState>::handle_cast;

    // ---- Trace config (reporting=true only) -----------------------
    //
    // Per #355, the per-message-type filter lives in the process-wide
    // Tracer (see platform/runtime/Tracer.hh). These methods are thin
    // delegations so the supervisor / NodeTraceCtl wire path has a
    // stable in-class API while the actual storage stays in one place.
    //
    // The supervisor (#361) pushes (msg_type, enabled) pairs by
    // calling trace_enable() on receipt of an ApplyConfig RPC. emit()
    // consults the same filter inside Tracer; non-listed types are
    // dropped on the disabled fast path.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }


    // ---- Subscriber registration ----------------------------------

    // inc_out.inc broadcast subscribers.
    uint32_t subscribe_inc_out_inc(
        Inc_outIncSubscriber s);
    void     unsubscribe_inc_out_inc(uint32_t id);


    // ---- GenServer plumbing: terminate default
    //
    // terminate keeps an inline no-op default; impl may shadow it.
    //
    // There is NO handle_info(const InfoMsg&) clause: the wire-info path
    // was removed. An inbound TIPC frame that matched no register_cast/
    // register_call is dropped with a CRITICAL log in TipcMux — never
    // delivered as untyped bytes. Cross-node traffic is exclusively typed
    // cast/call. The only handle_info is the LOCAL string clause below
    // (post_info / self-tick).
    void terminate(const char* /*reason*/, DriverNodeState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl
    //
    // Deduplicated by message type: if two ports share the same
    // interface (e.g. ctl_supdbg + ctl_com both providing
    // TraceControl) the handler signature is identical and only
    // gets emitted once. handle_call/handle_cast dispatch by
    // request type, not by port.



    // ---- OTP init/1 — body in impl (DriverNode_handlers.cc) ----------
    //
    // Called ONCE by the runtime on this node's thread after start(),
    // before the first mailbox item (GenServer::dispatch_init_). A
    // self-driving node bootstraps its work loop here (e.g.
    // ::theia::runtime::post_info(*this, "tick")); a passive node leaves it
    // empty. Emitted for every node so the hook is always visible.
    void init(DriverNodeState& s);

    // ---- string handle_info — body in impl ----------------------------
    //
    // The post_info()/send_after() string-message path (timer loops,
    // internal ticks). LOCAL-ONLY opaque signal — never crosses the wire.
    // Declared so a node can override the GenServer base no-op in its impl.
    void handle_info(const char* info, DriverNodeState& s);

    // ---- send helpers — bodies in impl (the broadcast fan-out)

    void broadcast_inc_out_inc(const Inc& msg);


private:

    struct Inc_outIncEntry {
        uint32_t id;
        Inc_outIncSubscriber fn;
    };
    std::mutex inc_out_inc_mu_;
    uint32_t inc_out_inc_next_id_{1};
    std::vector<Inc_outIncEntry>
        inc_out_inc_subs_;

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.

inline uint32_t DriverNode::subscribe_inc_out_inc(
        Inc_outIncSubscriber s) {
    std::lock_guard<std::mutex> lk(inc_out_inc_mu_);
    uint32_t id = inc_out_inc_next_id_++;
    inc_out_inc_subs_.push_back({id, std::move(s)});
    return id;
}

inline void DriverNode::unsubscribe_inc_out_inc(uint32_t id) {
    std::lock_guard<std::mutex> lk(inc_out_inc_mu_);
    auto& v = inc_out_inc_subs_;
    v.erase(std::remove_if(v.begin(), v.end(),
              [id](const auto& e) { return e.id == id; }), v.end());
}

inline void DriverNode::broadcast_inc_out_inc(const Inc& msg) {
    std::vector<Inc_outIncEntry> snap;
    {
        std::lock_guard<std::mutex> lk(inc_out_inc_mu_);
        snap = inc_out_inc_subs_;
    }
    for (const auto& e : snap) {
        try { e.fn(msg); }
        catch (...) {
            std::fprintf(stderr,
                "[%s] subscriber %u threw on inc_out.inc — dropping\n",
                kNodeName, e.id);
        }
    }
}




}  // namespace demo


