/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "com.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(services_services_com_ComEmpty, services_services_com_ComEmpty, AUTO)


PB_BIND(services_services_com_NetworkBindingRequest, services_services_com_NetworkBindingRequest, AUTO)



