/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GW_STATUS_GATEWAY_SYSTEM_STATUS_PB_H_INCLUDED
#define PB_GW_STATUS_GATEWAY_SYSTEM_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _gw_status_StatusGetStatusRequest { /* Empty: the gateway has only one status snapshot to return. */
    char dummy_field;
} gw_status_StatusGetStatusRequest;

typedef struct _gw_status_StatusGetStatusResponse {
    uint32_t uptime_ms; /* ms since cmp_gw process start (CLOCK_MONOTONIC) */
    uint32_t packet_count; /* ASAM-CMP packets seen since start */
} gw_status_StatusGetStatusResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define gw_status_StatusGetStatusRequest_init_default {0}
#define gw_status_StatusGetStatusResponse_init_default {0, 0}
#define gw_status_StatusGetStatusRequest_init_zero {0}
#define gw_status_StatusGetStatusResponse_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define gw_status_StatusGetStatusResponse_uptime_ms_tag 1
#define gw_status_StatusGetStatusResponse_packet_count_tag 2

/* Struct field encoding specification for nanopb */
#define gw_status_StatusGetStatusRequest_FIELDLIST(X, a) \

#define gw_status_StatusGetStatusRequest_CALLBACK NULL
#define gw_status_StatusGetStatusRequest_DEFAULT NULL

#define gw_status_StatusGetStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         1) \
X(a, STATIC,   SINGULAR, UINT32,   packet_count,      2)
#define gw_status_StatusGetStatusResponse_CALLBACK NULL
#define gw_status_StatusGetStatusResponse_DEFAULT NULL

extern const pb_msgdesc_t gw_status_StatusGetStatusRequest_msg;
extern const pb_msgdesc_t gw_status_StatusGetStatusResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gw_status_StatusGetStatusRequest_fields &gw_status_StatusGetStatusRequest_msg
#define gw_status_StatusGetStatusResponse_fields &gw_status_StatusGetStatusResponse_msg

/* Maximum encoded size of messages (where known) */
#define GW_STATUS_GATEWAY_SYSTEM_STATUS_PB_H_MAX_SIZE gw_status_StatusGetStatusResponse_size
#define gw_status_StatusGetStatusRequest_size    0
#define gw_status_StatusGetStatusResponse_size   12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
