// AUTO-GENERATED by `artheia gen-app` — DO NOT EDIT.
// source: odd_path_client/system/components/odd_path_monitor.art
// node:   OddPathMonitor
//
// Slice 2 (stub): tiny main(). Builds the runtime context, instantiates
// the app, runs the lifecycle, waits on SIGINT/SIGTERM, tears down.

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <future>
#include <thread>

#include "Clock.hh"
#include "Logger.hh"
#include "Timer.hh"

#include "OddPathMonitor.hh"
#include "OddPathMonitorInputs.hh"
#include "gw_client.h"
#include "gateway/system/status.pb.h"


namespace {

std::atomic<bool> g_shutdown{false};

void on_signal(int /*sig*/) noexcept {
    g_shutdown.store(true);
}

}  // namespace

// Placeholder for the per-node signal junction. Today the app talks to
// the gateway via GwClient directly (see OddPathMonitor.cc); the
// junction is reserved for future codegen wiring multiple apps to one
// libgw process without per-app threads.
namespace odd_path_client {
struct odd_path_monitor_signals {};
}

int main(int argc, char* argv[]) {
    (void)argc; (void)argv;

    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    auto logger        = platform::runtime::MakeConsoleLogger();
    auto clock         = platform::runtime::MakeSteadyClock();
    auto timer_factory = platform::runtime::MakeThreadTimerFactory();

    odd_path_client::odd_path_monitor_signals signals;

    odd_path_client::OddPathMonitorInputs inputs(timer_factory, signals, clock, logger);
    odd_path_client::OddPathMonitor app(inputs);

    logger->info("OddPathMonitor: starting");
    app.OnCreate();

    // ── Boot-time clientServer calls ────────────────────────────────────────
    // Issued between OnCreate (connect) and OnStart (rx thread spawn) so the
    // socket is ours alone — we can call pump_response() without racing the
    // rx loop. Each call is one round-trip on the same TIPC socket the app
    // will then use for signal subscriptions.

    {
        gw_status_StatusGetStatusRequest req = gw_status_StatusGetStatusRequest_init_zero;
        auto fut = app.status_query_GetStatus(req);
        // Pump the socket waiting for the RESPONSE. In pcap-replay mode
        // the gateway floods SIGNAL_UPDATE frames; the demuxer discards
        // them until the matching RPC RESPONSE arrives. Cap at 5s so a
        // misconfigured gateway can't hang boot indefinitely.
        bool got = app.client() && app.client()->pump_response(5000);
        // fut is a deferred future (the proxy chains std::async(deferred,
        // ...) around the raw byte vector future). Don't .wait_for(0) it
        // — deferred futures show "timeout" until you actually .get()
        // them. pump_response's return tells us whether the inner promise
        // was fulfilled.
        if (got) {
            gw_status_StatusGetStatusResponse resp = fut.get();
            std::fprintf(stderr,
                "[boot] status_query.GetStatus OK\n");
            (void)resp;
            std::fprintf(stderr,
                "       uptime_ms=%u  packet_count=%u\n",
                (unsigned)resp.uptime_ms, (unsigned)resp.packet_count);
        } else {
            std::fprintf(stderr,
                "[boot] status_query.GetStatus TIMEOUT — no response in 5s\n");
        }
    }

    app.OnStart();
    while (!g_shutdown.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(200));
    }
    logger->info("OddPathMonitor: stopping");
    app.OnStop();
    return 0;
}
