// AUTO-GENERATED by `artheia gen-app` — DO NOT EDIT.
// source: odd_path_client/system/components/odd_path_monitor.art
// node:   OddPathMonitor
//
// Slice 2 (stub): tiny main() that wires the runtime, creates inputs,
// instantiates the app, and hands control to the framework's run loop.

#include "OddPathMonitor.hh"
#include "OddPathMonitorInputs.hh"
#include "gateway/libs/pero_cmp_lnx/lib/include/runtime.hh"

int main(int argc, char* argv[]) {
  auto runtime = pero_cmp_lnx::create_runtime(argc, argv);
  auto inputs = odd_path_client::OddPathMonitorInputs(
      runtime.execution_factory_.CreateTimer(),
      runtime.odd_path_monitor_signals_,
      runtime.context_.clock,
      runtime.context_.logger);
  odd_path_client::OddPathMonitor app(inputs);
  runtime.run(app);
  return 0;
}
