// AUTO-GENERATED by `artheia gen-app` — DO NOT EDIT.
// source: odd_path_client/system/components/odd_path_monitor.art
// node:   OddPathMonitor
//
// Slice 2 (stub): tiny main(). Builds the runtime context, constructs
// the signal junction (provided by libgw codegen — TODO until host
// protos land), and runs the LifecycleInterface manually:
// OnCreate → OnStart → wait → OnStop.

#include <atomic>
#include <chrono>
#include <csignal>
#include <thread>

#include "Clock.hh"
#include "Logger.hh"
#include "Timer.hh"

#include "OddPathMonitor.hh"
#include "OddPathMonitorInputs.hh"

namespace {

std::atomic<bool> g_shutdown{false};

void on_signal(int /*sig*/) noexcept {
    g_shutdown.store(true);
}

}  // namespace

// Provided by the (forthcoming) host-side signal-junction codegen.
// For now: a stub that the linker resolves to an empty struct when
// libgw's generated signal junction is available.
namespace odd_path_client {
struct odd_path_monitor_signals {};
}

int main(int argc, char* argv[]) {
    (void)argc; (void)argv;

    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    auto logger        = platform::runtime::MakeConsoleLogger();
    auto clock         = platform::runtime::MakeSteadyClock();
    auto timer_factory = platform::runtime::MakeThreadTimerFactory();

    odd_path_client::odd_path_monitor_signals signals;

    odd_path_client::OddPathMonitorInputs inputs(timer_factory, signals, clock, logger);
    odd_path_client::OddPathMonitor app(inputs);

    logger->info("OddPathMonitor: starting");
    app.OnCreate();
    app.OnStart();
    while (!g_shutdown.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    logger->info("OddPathMonitor: stopping");
    app.OnStop();
    return 0;
}
