// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/supervisor/package.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/SupervisorCtl.hh"
#include "lib/SupervisorWorker.hh"

#include "lib/Log.hh"    // per-node MakeContextLogger(tag) — tagged + $THEIA_LOGGER sink
#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / process_logger / set_process_logger
#include "NodeAffinity.hh"  // apply_node_affinity($THEIA_NODE_CFG) per node
#include "ParamsConfig.hh"  // init_config(fc) / get_config() — static params JSON
#include "tombstone/tombstone.h"  // install_handlers — crash → tombstone file

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386).
                         // GenServer nodes use bind_node + register_cast;
                         // reporting runnables use bind_listener +
                         // register_cast_inline (no mailbox).
#include "HeartbeatPublisher.hh"  // periodic liveness beat to the supervisor
                         // watchdog — every reporting node (GenServer AND
                         // runnable). Hand-framed cast, no supervisor-proto dep.
#include <memory>
#include <vector>


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    // Crash forensics: install the libtombstone fatal-signal handler BEFORE any
    // node starts, so a SIGSEGV/SIGABRT/etc — even during startup — writes a
    // tombstone (backtrace + maps) to $THEIA_TOMBSTONE_DIR (the supervisor sets
    // it per child). The supervisor's GetTombstone serves it back (GUI
    // "Download tombstone"). No dir set (standalone run) → handler not armed.
    if (const char* td = std::getenv("THEIA_TOMBSTONE_DIR")) {
        if (td[0]) tombstone::install_handlers("supervisor", td);
    }

    using namespace ara::exec;

    // Boot log level — THEIA_LOG_LEVEL from the env (supervisor sets it from
    // executor.json's per-child env map, sourced from Process.log_level on the
    // rig). Defaults to Info when unset/unparseable. Applied to every node's
    // logger below. The SINK kind comes from THEIA_LOGGER (MakeContextLogger).
    auto boot_level = ::theia::runtime::kDefaultLogLevel;
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        boot_level = ::theia::runtime::parse_log_level(lvl);
    }

    // Static params (#params): load this FC's deployment-config JSON ONCE,
    // before any node is constructed, so a node's ctor / init() can read its
    // knobs via ::theia::runtime::get_config().node(kNodeName).u32(...). A
    // missing file is fine — every lookup falls back to the caller's default.
    // Path from $THEIA_CONFIG / $THEIA_CONFIG_DIR / ./config/supervisor.json.
    ::theia::runtime::init_config("supervisor");

    ::theia::runtime::TimerService timers;
    (void)timers;  // no node requires_timers

    // Config-service receiver (#386). A reporting node binds its TIPC name
    // and registers the supervisor's control pushes. A GenServer node's cast
    // lands in its base handle_cast on the node thread; a reporting runnable
    // (no mailbox) takes them INLINE on the mux thread (register_cast_inline).
    // Same standard GwMessageHeader path as any app message — no bespoke frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);

    // Heartbeat publishers — one per reporting node, kept alive for the
    // process lifetime (each owns a timer thread). Started after the node's
    // own start() below. The supervisor watchdog only watches nodes that
    // beat, so non-reporting nodes simply never appear here.
    std::vector<std::unique_ptr<::theia::runtime::HeartbeatPublisher>> heartbeats;


    SupervisorCtl supervisor_ctl;
    // Per-node logger: tagged [#supervisor_ctl] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto supervisor_ctl_log = MakeContextLogger(SupervisorCtl::kNodeName);
        supervisor_ctl_log->set_level(boot_level);
        ::theia::runtime::set_process_logger(supervisor_ctl_log);
        supervisor_ctl.set_logger(std::move(supervisor_ctl_log));
    }
    supervisor_ctl.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(supervisor_ctl.native_handle(),
        SupervisorCtl::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      SupervisorCtl::kTipcType, SupervisorCtl::kTipcInstance);
        supervisor_ctl.log().info(_tipc);
    }

    if (auto* supervisor_ctl_cfg = config_mux.bind_node(
            supervisor_ctl, SupervisorCtl::kTipcType,
            SupervisorCtl::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            supervisor_ctl_cfg, supervisor_ctl);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            supervisor_ctl_cfg, supervisor_ctl);
        // Config update: services/per casts ConfigUpdated when a watched
        // config changes — same framework path; GenServer base handle_cast
        // applies it (decode + on_config_update hook).
        config_mux.register_cast<platform_runtime_ConfigUpdated>(
            supervisor_ctl_cfg, supervisor_ctl);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<GetTreeRequest, TreeSnapshot>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetChildRequest, ChildState>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<StartChildRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<DeleteChildRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<ChildSelector, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<Stop, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetSystemInfoRequest, SystemInfo>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetHealthRequest, HealthBeacon>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<ConfigureTraceRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetTraceConfigRequest, TraceConfigList>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<ConfigureLogLevelRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetLogLevelConfigRequest, LogLevelConfigList>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetTombstoneRequest, GetTombstoneReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_cast<HeartbeatReport>(supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_cast<SendTimeoutReport>(supervisor_ctl_cfg, supervisor_ctl);
    } else {
        supervisor_ctl.log().warn("config service bind failed; live log-level "
                                 "push + signal inject disabled");
    }



    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto supervisor_ctl_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(SupervisorCtl::kNodeName);
        if (supervisor_ctl_hb->open()) {
            supervisor_ctl_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(supervisor_ctl_hb));
        } else {
            supervisor_ctl.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }


    SupervisorWorker supervisor_worker;
    // Per-node logger: tagged [#supervisor_worker] (kNodeName, matches `tdb ps`),
    // sink chosen by $THEIA_LOGGER. Installed BEFORE start() so do_start/init
    // log through it. The FIRST node's logger also backs process_logger() — the
    // ConfigureLogLevel-push fallback target + any process_logger() caller.
    {
        auto supervisor_worker_log = MakeContextLogger(SupervisorWorker::kNodeName);
        supervisor_worker_log->set_level(boot_level);
        supervisor_worker.set_logger(std::move(supervisor_worker_log));
    }
    supervisor_worker.start();
    // Per-node CPU affinity + scheduler from $THEIA_NODE_CFG (the supervisor
    // sets it from the rig's NodeToCPUMapping). No-op when unset / no entry for
    // this node; soft-fails (logs) on EPERM. Applied AFTER start() — the thread
    // exists now.
    ::theia::runtime::apply_node_affinity(supervisor_worker.native_handle(),
        SupervisorWorker::kNodeName, std::getenv("THEIA_NODE_CFG"));
    {
        char _tipc[64];
        std::snprintf(_tipc, sizeof(_tipc), "up — TIPC type=0x%x instance=%u",
                      SupervisorWorker::kTipcType, SupervisorWorker::kTipcInstance);
        supervisor_worker.log().info(_tipc);
    }


    // GenRunnable has no mailbox, so it can't take the supervisor's control
    // pushes via the GenServer handle_cast/mailbox path. Bind a listener and
    // register the LogLevelPush / TraceControlPush INLINE — the mux dispatch
    // thread applies them directly (on_log_level_push / on_trace_control_push,
    // touching only atomics). This is what makes a runnable's log level + trace
    // live-controllable (`tdb loglevel`/`trace <node>`), same as a gen_server.
    if (auto* supervisor_worker_cfg = config_mux.bind_listener(
            SupervisorWorker::kTipcType, SupervisorWorker::kTipcInstance)) {
        config_mux.register_cast_inline<platform_runtime_LogLevelPush>(
            supervisor_worker_cfg, supervisor_worker, &SupervisorWorker::on_log_level_push);
        config_mux.register_cast_inline<platform_runtime_TraceControlPush>(
            supervisor_worker_cfg, supervisor_worker, &SupervisorWorker::on_trace_control_push);
    } else {
        supervisor_worker.log().warn("config service bind failed; live log-level "
                                 "push disabled");
    }


    // Liveness beat to the supervisor watchdog (#PHM). A reporting node — of
    // EITHER base — must beat or the watchdog SIGTERMs it after K missed
    // deadlines. One publisher per node, own timer thread; period TODO from the
    // manifest (1s default matches the supervisor's check cadence).
    {
        auto supervisor_worker_hb = std::make_unique<
            ::theia::runtime::HeartbeatPublisher>(SupervisorWorker::kNodeName);
        if (supervisor_worker_hb->open()) {
            supervisor_worker_hb->start(/*period_ms=*/1000);
            heartbeats.push_back(std::move(supervisor_worker_hb));
        } else {
            supervisor_worker.log().warn("heartbeat publisher open failed; "
                                     "supervisor watchdog will not see beats");
        }
    }



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    supervisor_ctl.stop("signal");

    supervisor_worker.stop("signal");

    return 0;
}
