// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/supervisor/component.art
//
// Main slice — thread executor for the node(s) declared in .art.
// Regenerated on every gen-app run. User code lives in
// impl/<Node>_handlers.cc (one per node).

#include "lib/SupervisorCtl.hh"
#include "lib/SupervisorWorker.hh"

#include "TimerService.hh"
#include "Logger.hh"     // parse_log_level / MakeContextLogger / process_logger

#include "TipcMux.hh"    // config-service receiver for reporting nodes (#386)


#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <thread>

namespace {

std::atomic<bool> g_running{true};

void on_signal(int /*sig*/) { g_running.store(false); }

}  // namespace

int main() {
    std::signal(SIGINT,  on_signal);
    std::signal(SIGTERM, on_signal);

    using namespace ara::exec;

    // Process-wide logger. Pick up THEIA_LOG_LEVEL from the env
    // (supervisor sets it from executor.json's per-child env map,
    // sourced from Process.log_level on the rig). Defaults to Info
    // when unset or unparseable. set_process_logger publishes it so a
    // reporting node's config service can apply a live ConfigureLogLevel
    // push (#386) via process_logger().set_level on the node thread.
    auto logger = MakeContextLogger();
    if (const char* lvl = std::getenv("THEIA_LOG_LEVEL")) {
        logger->set_level(::theia::runtime::parse_log_level(lvl));
    }
    ::theia::runtime::set_process_logger(logger);
    (void)logger;  // available for user handlers via RuntimeContext

    ::theia::runtime::TimerService timers;
    (void)timers;  // no node requires_timers

    // Config-service receiver (#386). A reporting node binds its TIPC
    // name and register_cast's the supervisor's control push; the cast
    // lands in GenServer's base handle_cast(LogLevelPush) on the node
    // thread. Same standard GwMessageHeader path as any app message —
    // no bespoke control frame.
    ::theia::runtime::TipcMux config_mux;
    // Publish the one per-app mux (the single epoll/select loop) so a
    // handler's ad-hoc RemoteRef registers its call-reply fd here via
    // process_mux() — without it a synchronous call(ref,...) from inside
    // a handler would never get its reply pumped.
    ::theia::runtime::set_process_mux(&config_mux);


    SupervisorCtl supervisor_ctl;
    supervisor_ctl.start();
    std::fprintf(stderr, "[supervisor_ctl] up — TIPC type=0x%x instance=%u\n",
                 SupervisorCtl::kTipcType, SupervisorCtl::kTipcInstance);

    if (auto* supervisor_ctl_cfg = config_mux.bind_node(
            supervisor_ctl, SupervisorCtl::kTipcType,
            SupervisorCtl::kTipcInstance)) {
        config_mux.register_cast<platform_runtime_LogLevelPush>(
            supervisor_ctl_cfg, supervisor_ctl);
        // Trace control (#403): supervisor pushes TraceControlPush to flip
        // this node's Tracer kind filter — same path as LogLevelPush.
        config_mux.register_cast<platform_runtime_TraceControlPush>(
            supervisor_ctl_cfg, supervisor_ctl);
        // Receiver ports (#387): register the node's declared inbound
        // types so a real peer — or a robot-test inject via services/com
        // — lands on the same handle_call / handle_cast path. clientServer
        // ops → register_call; senderReceiver `in` data → register_cast.
        config_mux.register_call<GetTreeRequest, TreeSnapshot>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetChildRequest, ChildState>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<StartChildRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<DeleteChildRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<ChildSelector, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<Stop, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetSystemInfoRequest, SystemInfo>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<ConfigureTraceRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<GetTraceConfigRequest, TraceConfigList>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_call<ConfigureLogLevelRequest, ControlReply>(
            supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_cast<HeartbeatReport>(supervisor_ctl_cfg, supervisor_ctl);
        config_mux.register_cast<SendTimeoutReport>(supervisor_ctl_cfg, supervisor_ctl);
    } else {
        std::fprintf(stderr,
                     "[supervisor_ctl] WARN: config service bind failed; "
                     "live log-level push + signal inject disabled\n");
    }


    SupervisorWorker supervisor_worker;
    supervisor_worker.start();
    std::fprintf(stderr, "[supervisor_worker] up — TIPC type=0x%x instance=%u\n",
                 SupervisorWorker::kTipcType, SupervisorWorker::kTipcInstance);



    config_mux.start();


    while (g_running.load()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }


    config_mux.stop();


    supervisor_ctl.stop("signal");

    supervisor_worker.stop("signal");

    return 0;
}
