// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/log/system/package.art
//
// Lib slice — message wiring + class declaration for ONE node. An FC
// may declare several nodes; each gets its own <Node>.hh (this file).
// Regenerated on every gen-app run. User edits land in
// impl/TraceCollector_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "log_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/log/log.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::log {


// ---- TraceCollector ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (services_services_log_*); aliasing them here keeps callers'
// signatures readable.
using TraceConfigRequest = services_services_log_TraceConfigRequest;
using TraceEmpty = services_services_log_TraceEmpty;
using TraceRecord = services_services_log_TraceRecord;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.
using Stream_outRecSubscriber =
    std::function<void(const TraceRecord&)>;


// State held by the daemon — kept minimal; per-handler scratch
// goes in impl. Future iterations push more here once the FC has
// real persistent state needs.
struct TraceCollectorState {
    
    int  reserved{0};
};

class TraceCollector : public demo::runtime::GenServer<TraceCollector, TraceCollectorState> {
public:
    static constexpr const char* kNodeName = "trace_collector";
    static constexpr uint32_t kTipcType     = 0x80010013u;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). When true, this node sends HeartbeatReport, the
    // supervisor watchdogs it, and the supervisor can push trace
    // config to it via the methods below.
    static constexpr bool kReporting = true;


    // Bring the framework's config-service handler
    // (handle_cast(LogLevelPush)) into scope (#386). A Derived
    // handle_cast for any port message would otherwise HIDE the base
    // overload by name, so register_cast<LogLevelPush> wouldn't
    // resolve. This using-decl keeps both visible; overload resolution
    // then picks the right one per message type.
    using demo::runtime::GenServer<TraceCollector, TraceCollectorState>::handle_cast;

    // ---- Trace config (reporting=true only) -----------------------
    //
    // Per #355, the per-message-type filter lives in the process-wide
    // Tracer (see platform/runtime/Tracer.hh). These methods are thin
    // delegations so the supervisor / NodeTraceCtl wire path has a
    // stable in-class API while the actual storage stays in one place.
    //
    // The supervisor (#361) pushes (msg_type, enabled) pairs by
    // calling trace_enable() on receipt of an ApplyConfig RPC. emit()
    // consults the same filter inside Tracer; non-listed types are
    // dropped on the disabled fast path.
    void trace_enable(const char* msg_type, bool enabled) {
        ::demo::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::demo::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::demo::runtime::tracer_for(kNodeName).trace_clear_all();
    }


    // ---- Subscriber registration ----------------------------------

    // stream_out.rec broadcast subscribers.
    uint32_t subscribe_stream_out_rec(
        Stream_outRecSubscriber s);
    void     unsubscribe_stream_out_rec(uint32_t id);


    // ---- GenServer plumbing: terminate default
    //
    // handle_info is NOT declared here on purpose. The GenServer base
    // provides both clauses:
    //   * handle_info(const char*, State&) — benign no-op for post_info().
    //   * handle_info(const InfoMsg&, State&) — an inbound TIPC frame that
    //     matched no register_cast/register_call: the base default is a
    //     CRITICAL ERROR (an unrouted message ⇒ the netgraph and the
    //     running wiring disagree). A node that legitimately handles
    //     arbitrary traffic (the test probe) shadows the InfoMsg clause in
    //     its impl; a normal FC node must NOT — letting an unknown message
    //     through silently is exactly the bug this guards against.
    // terminate keeps an inline no-op default; impl may shadow it.
    void terminate(const char* /*reason*/, TraceCollectorState& /*s*/) noexcept {}


    // ---- handle_cast / handle_call — declared here, body in impl
    //
    // Deduplicated by message type: if two ports share the same
    // interface (e.g. ctl_supdbg + ctl_com both providing
    // TraceControl) the handler signature is identical and only
    // gets emitted once. handle_call/handle_cast dispatch by
    // request type, not by port.

    void handle_cast(const TraceRecord& msg, TraceCollectorState& s);


    TraceEmpty handle_call(const TraceConfigRequest& req,
                                            TraceCollectorState& s);


    // ---- send helpers — bodies in impl (the broadcast fan-out)

    void broadcast_stream_out_rec(const TraceRecord& msg);


private:

    struct Stream_outRecEntry {
        uint32_t id;
        Stream_outRecSubscriber fn;
    };
    std::mutex stream_out_rec_mu_;
    uint32_t stream_out_rec_next_id_{1};
    std::vector<Stream_outRecEntry>
        stream_out_rec_subs_;

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.

inline uint32_t TraceCollector::subscribe_stream_out_rec(
        Stream_outRecSubscriber s) {
    std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
    uint32_t id = stream_out_rec_next_id_++;
    stream_out_rec_subs_.push_back({id, std::move(s)});
    return id;
}

inline void TraceCollector::unsubscribe_stream_out_rec(uint32_t id) {
    std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
    auto& v = stream_out_rec_subs_;
    v.erase(std::remove_if(v.begin(), v.end(),
              [id](const auto& e) { return e.id == id; }), v.end());
}

inline void TraceCollector::broadcast_stream_out_rec(const TraceRecord& msg) {
    std::vector<Stream_outRecEntry> snap;
    {
        std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
        snap = stream_out_rec_subs_;
    }
    for (const auto& e : snap) {
        try { e.fn(msg); }
        catch (...) {
            std::fprintf(stderr,
                "[%s] subscriber %u threw on stream_out.rec — dropping\n",
                kNodeName, e.id);
        }
    }
}




}  // namespace ara::log


