// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/log/system/log/package.art
//
// Lib slice — message wiring + class declaration for ONE node. An FC
// may declare several nodes; each gets its own <Node>.hh (this file).
// Regenerated on every gen-app run. User edits land in
// impl/TraceCollector_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "log_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/services/log/log.pb.h"
// State held by the daemon — FIELDS are APP-OWNED (node behaviour, not
// derived from the .art), so the struct lives in a WRITE-ONCE impl header
// (seeded empty, never clobbered without --force) that the user fills in.
// Included at GLOBAL scope (the header opens its own `namespace
// ara::log`) so it isn't nested under this file's
// namespace block — bound as the GenServer State type below.
#include "impl/TraceCollector_state.hh"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace ara::log {


// ---- TraceCollector ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_services_log_*); aliasing them here keeps callers'
// signatures readable.
using TraceConfigRequest = system_services_log_TraceConfigRequest;
using TraceEmpty = system_services_log_TraceEmpty;
using TraceRecord = system_services_log_TraceRecord;
using LogRecord = system_services_log_LogRecord;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.
using Stream_outRecSubscriber =
    std::function<void(const TraceRecord&)>;
using To_logRecordSubscriber =
    std::function<void(const LogRecord&)>;


class TraceCollector : public ::theia::runtime::GenServer<TraceCollector, TraceCollectorState> {
public:
    static constexpr const char* kNodeName = "trace_collector";
    static constexpr uint32_t kTipcType     = 0x80010013u;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). When true, this node sends HeartbeatReport, the
    // supervisor watchdogs it, and the supervisor can push trace
    // config to it via the methods below.
    static constexpr bool kReporting = true;


    // Bring the framework's config-service handler
    // (handle_cast(LogLevelPush)) into scope (#386). A Derived
    // handle_cast for any port message would otherwise HIDE the base
    // overload by name, so register_cast<LogLevelPush> wouldn't
    // resolve. This using-decl keeps both visible; overload resolution
    // then picks the right one per message type.
    using ::theia::runtime::GenServer<TraceCollector, TraceCollectorState>::handle_cast;

    // ---- Trace config (reporting=true only) -----------------------
    //
    // Per #355, the per-message-type filter lives in the process-wide
    // Tracer (see platform/runtime/Tracer.hh). These methods are thin
    // delegations so the supervisor / NodeTraceCtl wire path has a
    // stable in-class API while the actual storage stays in one place.
    //
    // The supervisor (#361) pushes (msg_type, enabled) pairs by
    // calling trace_enable() on receipt of an ApplyConfig RPC. emit()
    // consults the same filter inside Tracer; non-listed types are
    // dropped on the disabled fast path.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }


    // ---- Subscriber registration ----------------------------------

    // stream_out.rec broadcast subscribers.
    uint32_t subscribe_stream_out_rec(
        Stream_outRecSubscriber s);
    void     unsubscribe_stream_out_rec(uint32_t id);

    // to_log.record broadcast subscribers.
    uint32_t subscribe_to_log_record(
        To_logRecordSubscriber s);
    void     unsubscribe_to_log_record(uint32_t id);


    // ---- GenServer plumbing: terminate default
    //
    // terminate keeps an inline no-op default; impl may shadow it.
    //
    // There is NO handle_info(const InfoMsg&) clause: the wire-info path
    // was removed. An inbound TIPC frame that matched no register_cast/
    // register_call is dropped with a CRITICAL log in TipcMux — never
    // delivered as untyped bytes. Cross-node traffic is exclusively typed
    // cast/call. The only handle_info is the LOCAL string clause below
    // (post_info / self-tick).
    void terminate(const char* /*reason*/, TraceCollectorState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl
    //
    // Deduplicated by message type: if two ports share the same
    // interface (e.g. ctl_supdbg + ctl_com both providing
    // TraceControl) the handler signature is identical and only
    // gets emitted once. handle_call/handle_cast dispatch by
    // request type, not by port.

    void handle_cast(const TraceRecord& msg, TraceCollectorState& s);


    TraceEmpty handle_call(const TraceConfigRequest& req,
                                            TraceCollectorState& s);


    // ---- OTP init/1 — body in impl (TraceCollector_handlers.cc) ----------
    //
    // Called ONCE by the runtime on this node's thread after start(),
    // before the first mailbox item (GenServer::dispatch_init_). A
    // self-driving node bootstraps its work loop here (e.g.
    // ::theia::runtime::post_info(*this, "tick")); a passive node leaves it
    // empty. Emitted for every node so the hook is always visible.
    void init(TraceCollectorState& s);

    // ---- string handle_info — body in impl ----------------------------
    //
    // The post_info()/send_after() string-message path (timer loops,
    // internal ticks). LOCAL-ONLY opaque signal — never crosses the wire.
    // Declared so a node can override the GenServer base no-op in its impl.
    void handle_info(const char* info, TraceCollectorState& s);

    // ---- send helpers — bodies in impl (the broadcast fan-out)

    void broadcast_stream_out_rec(const TraceRecord& msg);

    void broadcast_to_log_record(const LogRecord& msg);


private:

    struct Stream_outRecEntry {
        uint32_t id;
        Stream_outRecSubscriber fn;
    };
    std::mutex stream_out_rec_mu_;
    uint32_t stream_out_rec_next_id_{1};
    std::vector<Stream_outRecEntry>
        stream_out_rec_subs_;

    struct To_logRecordEntry {
        uint32_t id;
        To_logRecordSubscriber fn;
    };
    std::mutex to_log_record_mu_;
    uint32_t to_log_record_next_id_{1};
    std::vector<To_logRecordEntry>
        to_log_record_subs_;

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.

inline uint32_t TraceCollector::subscribe_stream_out_rec(
        Stream_outRecSubscriber s) {
    std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
    uint32_t id = stream_out_rec_next_id_++;
    stream_out_rec_subs_.push_back({id, std::move(s)});
    return id;
}

inline void TraceCollector::unsubscribe_stream_out_rec(uint32_t id) {
    std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
    auto& v = stream_out_rec_subs_;
    v.erase(std::remove_if(v.begin(), v.end(),
              [id](const auto& e) { return e.id == id; }), v.end());
}

inline void TraceCollector::broadcast_stream_out_rec(const TraceRecord& msg) {
    std::vector<Stream_outRecEntry> snap;
    {
        std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
        snap = stream_out_rec_subs_;
    }
    for (const auto& e : snap) {
        try { e.fn(msg); }
        catch (...) {
            std::fprintf(stderr,
                "[%s] subscriber %u threw on stream_out.rec — dropping\n",
                kNodeName, e.id);
        }
    }
}

inline uint32_t TraceCollector::subscribe_to_log_record(
        To_logRecordSubscriber s) {
    std::lock_guard<std::mutex> lk(to_log_record_mu_);
    uint32_t id = to_log_record_next_id_++;
    to_log_record_subs_.push_back({id, std::move(s)});
    return id;
}

inline void TraceCollector::unsubscribe_to_log_record(uint32_t id) {
    std::lock_guard<std::mutex> lk(to_log_record_mu_);
    auto& v = to_log_record_subs_;
    v.erase(std::remove_if(v.begin(), v.end(),
              [id](const auto& e) { return e.id == id; }), v.end());
}

inline void TraceCollector::broadcast_to_log_record(const LogRecord& msg) {
    std::vector<To_logRecordEntry> snap;
    {
        std::lock_guard<std::mutex> lk(to_log_record_mu_);
        snap = to_log_record_subs_;
    }
    for (const auto& e : snap) {
        try { e.fn(msg); }
        catch (...) {
            std::fprintf(stderr,
                "[%s] subscriber %u threw on to_log.record — dropping\n",
                kNodeName, e.id);
        }
    }
}




}  // namespace ara::log


