"""rig.bzl — bzlmod module extension wiring a TEST-TARGET rig into Bazel.

A test target's deployment is described as a Python module on the manifest
engine — `manifest.<target>.rig` (manifest.single.rig / manifest.split.rig /
manifest.local.rig) — exporting a `DeploymentLayer` attribute (RIG; split also
exports DOCKER / HW). The layer assembles the framework `manifest.services`
with the demo `manifest.apps` (a PEP-420-style namespace package split across
the framework root and the consuming workspace).

The module extension below runs

    artheia serialize-manifest manifest.<target>.rig --attr <ATTR> --out <dir>

at module-load time (which validate()s FIRST, refusing on any inconsistency),
reads the resulting per-machine JSON, and materializes a synthetic repository
(one per rig) exposing per-machine targets:

    @rig_single//central:components   # filegroup of all process binaries
    @rig_single//central:image        # opkg .ipk / .deb for central
    @rig_single//central:executor     # executor.json only
    @rig_single//:machines_json       # the machine NAME LIST

Usage from MODULE.bazel:

    rig_ext = use_extension("@pero_theia//rules:rig.bzl", "rig_ext")
    rig_ext.declare(name = "rig_apps", rig_module = "manifest.apps.rig",
                    rig_attr = "RIG")
    use_repo(rig_ext, "rig_single")

Then:

    bazel build @rig_single//central:components   # the per-machine binaries
    bazel build @rig_single//central:image        # the deploy bundle

The synthetic repo references the user's actual cc_binary targets via the
`executable` bazel-target string in each machine's execution.json. The user is
responsible for those targets existing (`//services/com/main:com` resolves to a
cc_binary in @pero_theia; `//apps/Demo3WayP1/main:apps` to one in the consuming
workspace).

Data source: this extension consumes `serialize-manifest`'s JSON, NOT the old
`rig-deps` flat-component dict. The two relevant files per machine are:

    <out>/machines.json                  {"machines": ["central", ...]}  NAME LIST
    <out>/<machine>/machine.json         {"name","arch":"x86_64"|"aarch64",...}
    <out>/<machine>/execution.json       {"processes":[{"name","executable",...}]}
    <out>/<machine>/executor.json        the per-machine supervisor tree

Implementation notes:
- Module extensions run during MODULE.bazel resolution, BEFORE the
  workspace-loading phase. `artheia` is resolved from the consuming ws .venv,
  then the @pero_theia framework venv, then PATH.
- PYTHONPATH for the serialize-manifest subprocess mirrors theia.py's _run:
  [framework_root/artheia, consuming_ws, framework_root]. BOTH the consuming ws
  (manifest.apps + the rig module) and the framework root (manifest.services)
  must be visible for the namespace package + rig import to resolve.
- The DIST (no-python) path is a SEPARATE rule — see rules/dist_ipk.bzl's
  dist_pkg, driven by `theia dist` from a committed serialized dir. This file is
  only the DEV (serialize-at-eval) path.
"""

# -----------------------------------------------------------------------------
# repository_rule — materialize one synthetic repo per rig
# -----------------------------------------------------------------------------

_BUILD_HEADER = '''\
# AUTO-GENERATED by //rules:rig.bzl from rig_module "{rig_module}" (--attr {rig_attr}).
# DO NOT EDIT — regenerate via `bazel mod tidy`.
#
# Machines: {machine_names}

load("@pero_theia//rules:opkg.bzl", "pkg_opkg")

package(default_visibility = ["//visibility:public"])

'''


# Framework label prefixes — targets that live in the @pero_theia module
# (the Theia framework), NOT the consuming workspace. Mirrors theia.py's
# _is_framework_target so the deploy bundle and `theia install` agree on
# which binaries come from the framework vs the user's own app tree.
_FRAMEWORK_PREFIXES = ("//platform/", "//services/")


def _abs_label(label):
    """Make a bare `//…` process-`executable` label absolute against the repo
    that actually defines it. A rig declared from a CONSUMING workspace mixes
    two origins: framework binaries (//platform/…, //services/…) live in the
    @pero_theia module, while the workspace's OWN app binaries (//apps/…) live
    in the consuming (root) module. The synthetic @rig_<name>// repo resolves a
    bare //… against ITSELF (wrong for both), so partition explicitly:
      - framework prefixes → @pero_theia//…
      - everything else    → @@//… (the root module — the consuming workspace,
        or theia.git itself when the rig is the framework's own demo).
    A non-`//` label (already repo-qualified or relative) is left untouched."""
    if not label.startswith("//"):
        return label
    for pfx in _FRAMEWORK_PREFIXES:
        if label.startswith(pfx):
            return "@pero_theia" + label
    return "@@" + label


def _machine_targets(machine_name, arch, processes):
    """Emit BUILD content for one machine from its serialize-manifest JSON.

    `processes` is execution.json["processes"] — each a dict with at least
    `name` (the deploy basename, e.g. "p1") and `executable` (the bazel target,
    e.g. "//apps/Demo3WayP1/main:apps"). All targets land in:

      :components   a filegroup of every process binary (via _abs_label).
      :image        a pkg_opkg packaging each binary at /opt/theia/bin/<name>
                    (matches the executor start_cmd `bin/<name>` resolved
                    against THEIA_ROOT_DIR=/opt/theia) + the executor.json,
                    with Architecture from machine.json (x86_64→amd64,
                    aarch64→arm64 — done inside pkg_opkg's arch table).
      :executor     the per-machine executor.json (supervisor tree).

    `bin/<name>` uses the PROCESS name as the dest basename, not the bazel
    target's own output name: the demo p1/p2/p3/p4 binaries are ALL the cc_binary
    `:apps`, distinguished only by their package path, so the executor's
    `bin/p1`…`bin/p4` must be the dest, with each label staged to its own slot.
    """
    lines = []
    lines.append("# --- machine {name} ({arch}) ---------------------------".format(
        name = machine_name,
        arch = arch,
    ))

    if not processes:
        # No processes on this machine: keep the targets but empty, so
        # downstream `:all` references still resolve.
        lines.append('''
filegroup(name = "components", srcs = [])

filegroup(name = "image", srcs = [])

exports_files(["executor.json"])
''')
        return "".join(lines)

    # filegroup aggregating every process binary. All labels go via _abs_label
    # so they reference @pero_theia (services) / @@ (apps), not the synthetic
    # @rig_<name>// repo. Dedup: a single cc_binary (`:apps`) backs several
    # processes — list each distinct label once in the filegroup.
    seen = {}
    distinct_labels = []
    for p in processes:
        lbl = _abs_label(p["executable"])
        if lbl not in seen:
            seen[lbl] = True
            distinct_labels.append(lbl)
    targets_str = ",\n        ".join(['"{}"'.format(l) for l in distinct_labels])
    lines.append('''
filegroup(
    name = "components",
    srcs = [
        {targets}
    ],
)
'''.format(targets = targets_str))

    # pkg_opkg packaging every process binary into /opt/theia/bin/<name> (the
    # process name, not the target name). The supervisor's child lookup uses the
    # executor.json start_cmd `bin/<name>` resolved against THEIA_ROOT_DIR. The
    # executor.json itself is staged at /opt/theia/executor.json. pkg_opkg's
    # `files` map is {label: dest_path}; the arch token comes straight from
    # machine.json (pkg_opkg's _DEB_ARCH maps x86_64→amd64, aarch64→arm64).
    files_entries = []
    for p in processes:
        files_entries.append(
            '        "{label}": "/opt/theia/bin/{name}",'.format(
                label = _abs_label(p["executable"]),
                name = p["name"],
            ),
        )
    files_entries.append(
        '        ":executor.json": "/opt/theia/executor.json",',
    )
    lines.append('''
exports_files(["executor.json"])

alias(
    name = "executor",
    actual = ":executor.json",
)

pkg_opkg(
    name = "image",
    package = "theia-{machine}",
    version = "1.0.0",
    # Architecture from machine.json (the target machine's declared CPU arch —
    # what `dpkg -i` expects on the box). pkg_opkg maps x86_64→amd64,
    # aarch64→arm64. Use --platforms=//rules/config:rpi4 to drive the underlying
    # cc_toolchain when the rig cross-builds aarch64 cc_binary components.
    arch = "{arch}",
    description = "Deploy bundle for {machine}",
    section = "apps",
    files = {{
{files}
    }},
)
'''.format(
        machine = machine_name,
        arch = arch,
        files = "\n".join(files_entries),
    ))

    return "".join(lines)


def _rig_repo_impl(ctx):
    """repository_rule body: run `artheia serialize-manifest`, emit one
    BUILD.bazel per machine subdir, plus a top-level BUILD.bazel with the
    machines-name-list convenience target."""

    # 1. Resolve artheia + the import roots for the rig module.
    #
    # The rig MODULE (e.g. `manifest.single.rig`) imports manifest.apps (owned
    # by the CONSUMING workspace = the ROOT module) AND manifest.services
    # (owned by the @pero_theia framework module). serialize-manifest must run
    # with BOTH roots on PYTHONPATH so the `manifest` namespace package resolves
    # across both. `ctx.workspace_root` is the consuming root (the main repo dir).
    consuming_ws = str(ctx.workspace_root)
    framework_ws = str(ctx.path(Label("@pero_theia//:MODULE.bazel")).dirname)

    # artheia binary: prefer the consuming workspace's own .venv, then the
    # @pero_theia framework venv (the editable install lives there in a source
    # checkout), then PATH.
    candidates = [
        consuming_ws + "/.venv/bin/artheia",
        framework_ws + "/.venv/bin/artheia",
    ]
    artheia = None
    for cand in candidates:
        if ctx.execute([cand, "--version"], quiet = True).return_code == 0:
            artheia = cand
            break
    if artheia == None:
        if ctx.execute(["which", "artheia"], quiet = True).return_code == 0:
            artheia = "artheia"
        else:
            fail(
                "Could not find `artheia` CLI. Install the workspace venv " +
                "(`pip install -e artheia/`) and ensure one of {} is on PATH.".format(
                    candidates,
                ),
            )

    # 2. PYTHONPATH mirrors theia.py _run: prepend the framework's `artheia/`
    # source parent (so the editable-installed `artheia` PACKAGE wins over the
    # bare `artheia/` source DIRECTORY that would otherwise shadow it as a
    # namespace portion), then the consuming ws (manifest.apps + the rig module),
    # then the framework root (manifest.services). os.pathsep is ":" on Linux.
    pythonpath = [consuming_ws, framework_ws]
    if ctx.path(framework_ws + "/artheia/artheia/__init__.py").exists:
        pythonpath.insert(0, framework_ws + "/artheia")
    rig_env = {"PYTHONPATH": ":".join(pythonpath)}

    # 3. serialize-manifest manifest.<target>.rig --attr <ATTR> --out <dir>.
    # Write into a `manifest/` dir inside the repo rule's output.
    out_dir = "manifest"
    attr = ctx.attr.rig_attr if ctx.attr.rig_attr else "RIG"
    cmd = [
        artheia,
        "serialize-manifest",
        ctx.attr.rig_module,
        "--attr",
        attr,
        "--out",
        out_dir,
    ]
    result = ctx.execute(cmd, quiet = False, environment = rig_env)
    if result.return_code != 0:
        fail("artheia serialize-manifest {} --attr {} failed:\n{}\n{}".format(
            ctx.attr.rig_module,
            attr,
            result.stdout,
            result.stderr,
        ))

    # 4. Read machines.json (a NAME LIST) → per-machine machine.json (arch) +
    # execution.json (processes). Emit one subdir per machine.
    machines = json.decode(ctx.read(out_dir + "/machines.json"))["machines"]
    machine_names = ", ".join(machines)
    for name in machines:
        machine = json.decode(ctx.read("{}/{}/machine.json".format(out_dir, name)))
        execution = json.decode(
            ctx.read("{}/{}/execution.json".format(out_dir, name)),
        )
        arch = machine.get("arch", "x86_64")
        processes = execution.get("processes", [])

        # Copy executor.json into the machine subdir so :executor / the image's
        # /opt/theia/executor.json can reference it as a same-package source.
        ctx.file(
            "{}/executor.json".format(name),
            ctx.read("{}/{}/executor.json".format(out_dir, name)),
        )

        ctx.file(
            "{}/BUILD.bazel".format(name),
            _BUILD_HEADER.format(
                rig_module = ctx.attr.rig_module,
                rig_attr = attr,
                machine_names = machine_names,
            ) + _machine_targets(name, arch, processes),
        )

    # 5. Top-level @rig_<name>//:machines_json (the machine NAME LIST, copied in
    # from serialize-manifest) + an `all` summary filegroup of every :image.
    ctx.file(
        "machines.json",
        ctx.read(out_dir + "/machines.json"),
    )
    ctx.file("BUILD.bazel", '''\
# AUTO-GENERATED by //rules:rig.bzl from rig_module "{rig_module}" (--attr {rig_attr}).

package(default_visibility = ["//visibility:public"])

# machines.json — the machine NAME LIST ({{"machines":[...]}}), as serialized by
# `artheia serialize-manifest`. The GUI / supervisor-gui reads this to know the
# deploy's target machines.
exports_files(["machines.json"])

alias(
    name = "machines_json",
    actual = ":machines.json",
)

# A summary filegroup for `bazel build @{name}//:all`.
filegroup(
    name = "all",
    srcs = [
        ":machines_json",
{machine_image_targets}
    ],
)
'''.format(
        rig_module = ctx.attr.rig_module,
        rig_attr = attr,
        name = ctx.attr.name,
        machine_image_targets = "\n".join([
            '        "//{name}:image",'.format(name = name)
            for name in machines
        ]),
    ))


rig_repo = repository_rule(
    implementation = _rig_repo_impl,
    attrs = {
        "rig_module": attr.string(
            mandatory = True,
            doc = "Python dotted import path to the rig module, e.g. " +
                  "manifest.single.rig.",
        ),
        "rig_attr": attr.string(
            default = "",
            doc = "Which DeploymentLayer export in the module to serialize " +
                  "(passed as `--attr`). Empty = \"RIG\". e.g. manifest.split.rig " +
                  "exports DOCKER and HW alongside RIG.",
        ),
    },
    doc = "Materialize a per-rig synthetic Bazel repo from a Python rig spec " +
          "via `artheia serialize-manifest`.",
)


# -----------------------------------------------------------------------------
# Module extension — the tag class users declare from MODULE.bazel
# -----------------------------------------------------------------------------

_declare = tag_class(
    attrs = {
        "name": attr.string(
            mandatory = True,
            doc = "Synthetic-repo name (e.g. rig_single).",
        ),
        "rig_module": attr.string(
            mandatory = True,
            doc = "Dotted Python import path to the rig module.",
        ),
        "rig_attr": attr.string(
            default = "",
            doc = "Which DeploymentLayer export to serialize (--attr). " +
                  "Empty = \"RIG\". See rig_repo's rig_attr doc.",
        ),
    },
)


def _rig_ext_impl(module_ctx):
    """Module extension entry: walk every `rig_ext.declare(...)` call
    across the module graph and instantiate a `rig_repo` for each."""
    for mod in module_ctx.modules:
        for tag in mod.tags.declare:
            rig_repo(
                name = tag.name,
                rig_module = tag.rig_module,
                rig_attr = tag.rig_attr,
            )


rig_ext = module_extension(
    implementation = _rig_ext_impl,
    tag_classes = {"declare": _declare},
    doc = "Module extension: declare one synthetic rig repo per test-target rig.",
)
