"""rig.bzl — bzlmod module extension wiring rig.py into Bazel.

A vendor's rig is described declaratively in a Python module
(e.g. `demo/manifest/rig.py`) as a `SoftwareSpecification` literal.
The module extension below runs `artheia rig-deps <module>` at
module-load time, reads the resulting JSON, and materializes a
synthetic repository (one per rig) exposing per-machine targets:

    @rig_demo//demo_host:image       # opkg .ipk for demo_host
    @rig_demo//demo_host:executor    # executor.yaml only
    @rig_demo//demo_host:components  # filegroup of all binaries
    @rig_demo//executor_yaml         # combined executor.yaml (multi-host)
    @rig_demo//machines_yaml         # GUI manifest

Usage from MODULE.bazel:

    rig_ext = use_extension("//rules:rig.bzl", "rig_ext")
    rig_ext.declare(name = "rig_demo", rig_module = "demo.manifest.rig")
    use_repo(rig_ext, "rig_demo")

Then:

    bazel build @rig_demo//demo_host:image      # the deploy bundle
    bazel build @rig_demo//demo_host:executor   # just the supervisor manifest

The synthetic repo references the user's actual cc_binary / py_binary
targets via the bazel_target strings declared in the rig's
SwComponents. The user is responsible for those targets existing
(e.g. `//demo:p1_main` resolves to a cc_binary in demo/BUILD.bazel).

Implementation notes:
- Module extensions run during MODULE.bazel resolution, BEFORE the
  workspace-loading phase. So `artheia` must be reachable via $PATH —
  the workspace .venv/bin must be on PATH before `bazel build`.
- The synthetic repo's BUILD content is generated at extension-eval
  time. If the rig.py changes, re-run `bazel mod tidy` or similar
  to refresh.
- Each rig generates a deterministic set of files; lockfile stability
  is preserved.
"""

# -----------------------------------------------------------------------------
# repository_rule — materialize one synthetic repo per rig
# -----------------------------------------------------------------------------

_BUILD_HEADER = '''\
# AUTO-GENERATED by //rules:rig.bzl from rig_module "{rig_module}".
# DO NOT EDIT — regenerate via `bazel mod tidy`.
#
# Vehicle: {vehicle_name} ({vehicle_make} / {vehicle_model})
# Machines: {machine_names}

load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("@pero_theia//rules:opkg.bzl", "pkg_opkg")

package(default_visibility = ["//visibility:public"])

'''


def _abs_label(label):
    """Rewrite a label like `//services/com` to be absolute against
    the main pero_theia repo. The synthetic @rig_<name>// repo
    resolves bare //... labels relative to itself, which isn't what
    the user wrote in the rig.py SwComponent."""
    if label.startswith("//"):
        return "@pero_theia" + label
    return label


def _machine_targets(machine, vehicle_name):
    """Emit BUILD content for one machine: filegroup + opkg target.

    Only ``bazel_buildable=True`` SwComponents land in the filegroup
    and the opkg payload. Components with ``bazel_buildable=False``
    (legacy bash daemons under ``theia_runtime/``, FCs not yet bridged
    into Bazel, etc.) are skipped — their references stay in the
    rig.py and the executor.yaml so the supervisor knows about them,
    but the deploy bundle doesn't try to package them.
    """
    lines = []
    lines.append("# --- machine {name} -----------------------------------".format(
        name = machine["name"],
    ))

    buildable = [c for c in machine["all_components"] if c.get("bazel_buildable")]
    skipped = [c for c in machine["all_components"] if not c.get("bazel_buildable")]

    if skipped:
        skipped_names = ", ".join([c["name"] for c in skipped])
        lines.append(
            "\n# Skipped (bazel_buildable=False): " + skipped_names + "\n",
        )

    if not buildable:
        # Empty machine: keep the targets but with no srcs/files. This
        # is the realistic state for an FC-only platform layer until
        # the FC binaries get real Bazel targets.
        lines.append('''
filegroup(name = "components", srcs = [])

# No buildable components on this machine; emit an empty filegroup
# for `image` so downstream `:all` references still resolve.
filegroup(
    name = "image",
    srcs = [],
)
''')
        return "".join(lines)

    # filegroup aggregating every component binary. All labels go via
    # `_abs_label` so they reference the main pero_theia repo, not the
    # synthetic @rig_<name>// one.
    targets_str = ",\n        ".join(
        ['"{}"'.format(_abs_label(c["bazel_target"])) for c in buildable],
    )
    lines.append('''
filegroup(
    name = "components",
    srcs = [
        {targets}
    ],
)
'''.format(targets = targets_str))

    # pkg_opkg target packaging every binary into /usr/bin/<name>.
    # Note: this assumes each bazel_target produces a single binary
    # output mapped to /usr/bin/<component-name>. cc_binary's default
    # output filename matches the target name, so //demo:p1_main →
    # bazel-bin/demo/p1_main. The opkg rule's `files` map expects
    # {label: dest_path}.
    files_entries = []
    for c in buildable:
        files_entries.append(
            '        "{label}": "/usr/bin/{name}",'.format(
                label = _abs_label(c["bazel_target"]),
                name = c["name"],
            ),
        )

    lines.append('''
pkg_opkg(
    name = "image",
    package = "{vehicle}-{machine}",
    version = "1.0.0",
    arch = "x86_64",
    description = "Deploy bundle for {vehicle} on {machine}",
    section = "apps",
    files = {{
{files}
    }},
)
'''.format(
        vehicle = vehicle_name,
        machine = machine["name"],
        files = "\n".join(files_entries),
    ))

    return "".join(lines)


def _rig_repo_impl(ctx):
    """repository_rule body: run `artheia rig-deps`, emit one BUILD.bazel
    per machine subdir, plus a top-level BUILD.bazel with executor /
    machines yaml targets."""

    # 1. Resolve artheia. Prefer the workspace .venv; fall back to PATH.
    workspace = ctx.path(Label("@pero_theia//:MODULE.bazel")).dirname
    venv_artheia = str(workspace) + "/.venv/bin/artheia"

    artheia = venv_artheia
    result = ctx.execute([artheia, "--version"], quiet = True)
    if result.return_code != 0:
        # Try PATH-resolved artheia.
        artheia = "artheia"
        result = ctx.execute(["which", "artheia"], quiet = True)
        if result.return_code != 0:
            fail(
                "Could not find `artheia` CLI. Install the workspace venv " +
                "(`pip install -e artheia/`) and ensure {} is on PATH.".format(
                    venv_artheia,
                ),
            )

    # 2. Run rig-deps to get the structure.
    rig_json = "rig.json"
    result = ctx.execute(
        [artheia, "rig-deps", ctx.attr.rig_module, "--out", rig_json],
        quiet = False,
    )
    if result.return_code != 0:
        fail("artheia rig-deps {} failed:\n{}\n{}".format(
            ctx.attr.rig_module,
            result.stdout,
            result.stderr,
        ))

    rig = json.decode(ctx.read(rig_json))

    # 3. Build per-machine `all_components` lists (the flat_components
    # filtered by machine name), then emit BUILD content.
    machines = rig["machines"]
    flat = rig["flat_components"]
    for m in machines:
        m["all_components"] = [
            c for c in flat if c["machine"] == m["name"]
        ]

    # 4. Emit one subdirectory per machine: @rig_demo//demo_host:image etc.
    machine_names = ", ".join([m["name"] for m in machines])
    for m in machines:
        ctx.file(
            "{}/BUILD.bazel".format(m["name"]),
            _BUILD_HEADER.format(
                rig_module = ctx.attr.rig_module,
                vehicle_name = rig["vehicle"]["name"],
                vehicle_make = rig["vehicle"]["make"],
                vehicle_model = rig["vehicle"]["model"],
                machine_names = machine_names,
            ) + _machine_targets(m, rig["vehicle"]["name"]),
        )

    # 5. Top-level @rig_demo//:executor_yaml + machines_yaml via genrules.
    # These call back into artheia at build time (so the YAMLs always
    # reflect the current rig.py state) — they aren't read at
    # module-extension-eval time.
    ctx.file("BUILD.bazel", '''\
# AUTO-GENERATED by //rules:rig.bzl from rig_module "{rig_module}".

package(default_visibility = ["//visibility:public"])

genrule(
    name = "executor_yaml",
    outs = ["executor.yaml"],
    cmd = "bash $(rootpath @pero_theia//tools:artheia_wrapper.sh) executor emit {rig_module} --out $@",
    tools = ["@pero_theia//tools:artheia_wrapper.sh"],
)

genrule(
    name = "machines_yaml",
    outs = ["machines.yaml"],
    cmd = "bash $(rootpath @pero_theia//tools:artheia_wrapper.sh) gui emit {rig_module} --out $@",
    tools = ["@pero_theia//tools:artheia_wrapper.sh"],
)

# A summary filegroup for `bazel build @{name}//:all`.
filegroup(
    name = "all",
    srcs = [
        ":executor_yaml",
        ":machines_yaml",
{machine_image_targets}
    ],
)
'''.format(
        rig_module = ctx.attr.rig_module,
        name = ctx.attr.name,
        machine_image_targets = "\n".join([
            '        "//{name}:image",'.format(name = m["name"])
            for m in machines
        ]),
    ))


rig_repo = repository_rule(
    implementation = _rig_repo_impl,
    attrs = {
        "rig_module": attr.string(
            mandatory = True,
            doc = "Python dotted import path to the rig module, e.g. demo.manifest.rig.",
        ),
    },
    doc = "Materialize a per-rig synthetic Bazel repo from a Python rig spec.",
)


# -----------------------------------------------------------------------------
# Module extension — the tag class users declare from MODULE.bazel
# -----------------------------------------------------------------------------

_declare = tag_class(
    attrs = {
        "name": attr.string(
            mandatory = True,
            doc = "Synthetic-repo name (e.g. rig_demo).",
        ),
        "rig_module": attr.string(
            mandatory = True,
            doc = "Dotted Python import path to the rig module.",
        ),
    },
)


def _rig_ext_impl(module_ctx):
    """Module extension entry: walk every `rig_ext.declare(...)` call
    across the module graph and instantiate a `rig_repo` for each."""
    for mod in module_ctx.modules:
        for tag in mod.tags.declare:
            rig_repo(
                name = tag.name,
                rig_module = tag.rig_module,
            )


rig_ext = module_extension(
    implementation = _rig_ext_impl,
    tag_classes = {"declare": _declare},
    doc = "Module extension: declare one synthetic rig repo per rig.py.",
)
