// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/rds/package.art
//
// GENERATED do_* bodies for the prebuilt node RoudiBroker — it forks and
// supervises the third-party binary "/usr/bin/iox-roudi". Unlike a `node runnable`,
// this impl is NOT hand-written: gen-app overwrites it on every regen. The
// child's stdout/stderr are drained line-by-line into this node's logger
// (behave-like-a-pipe) so a chatty broker's output lands in the Theia log
// instead of the supervisor's tty.

#include "lib/RoudiBroker.hh"

#include "ParamsConfig.hh"   // get_config() — per-machine enabled/args override

#include <array>
#include <cerrno>
#include <csignal>
#include <cstring>
#include <sstream>
#include <string>
#include <vector>

#include <fcntl.h>
#include <poll.h>
#include <sys/wait.h>
#include <unistd.h>

namespace ara::rds {


namespace {

// The compiled-default argv tail from the .art `args` param. Per-machine config
// (config/rds.json, key "roudi.args") overrides it at
// runtime so the SAME binary runs e.g. ptp4l as master on central / slave on
// compute without a rebuild. Whitespace-split tokens; no shell.
constexpr const char* kDefaultArgs = "";

// Drain whatever is ready on `fd` and emit each COMPLETE line through `emit`.
// `carry` holds a partial trailing line between calls. Returns false on EOF
// (the child closed its end / exited), true otherwise.
template <typename Emit>
bool drain_fd(int fd, std::string& carry, Emit&& emit) {
    std::array<char, 4096> buf;
    for (;;) {
        ssize_t r = ::read(fd, buf.data(), buf.size());
        if (r > 0) {
            carry.append(buf.data(), static_cast<size_t>(r));
            size_t nl;
            while ((nl = carry.find('\n')) != std::string::npos) {
                emit(carry.substr(0, nl));
                carry.erase(0, nl + 1);
            }
            continue;   // keep reading until EAGAIN
        }
        if (r == 0) return false;                      // EOF
        if (errno == EAGAIN || errno == EWOULDBLOCK) return true;
        if (errno == EINTR) continue;
        return false;                                  // hard error → treat as EOF
    }
}

}  // namespace

// fork() + execvp the third-party binary; keep the read ends of its stdout/
// stderr pipes (non-blocking) so do_loop() can pump them into our logger.
void RoudiBroker::do_start() {
    // `enabled` gate (config/rds.json, key "roudi.enabled",
    // default true): a Provider not wanted on this machine (e.g. gpsd on a board
    // with no GPS) stays UN-forked. do_loop then just idles — no execvp, no
    // restart churn. Per-machine gen-config flips it.
    auto cfg = ::theia::runtime::get_config().node(RoudiBroker::kNodeName);
    if (!cfg.boolean("enabled", true)) {
        log().info("[roudi] disabled (params.enabled=false) — not forking /usr/bin/iox-roudi");
        child_pid_ = -1;
        return;
    }

    // argv = kPath + the runtime `args` (config override, else the .art default),
    // whitespace-split into tokens. Built in the PARENT (heap) before fork; the
    // child only dup2's + execvp's the NUL-terminated vector.
    std::vector<std::string> arg_store;
    arg_store.emplace_back(RoudiBroker::kPath);
    {
        std::string args = cfg.str("args", kDefaultArgs);
        std::istringstream iss(args);
        std::string tok;
        while (iss >> tok) arg_store.push_back(tok);
    }
    std::vector<char*> c_argv;
    for (auto& s : arg_store) c_argv.push_back(const_cast<char*>(s.c_str()));
    c_argv.push_back(nullptr);

    int out_pipe[2] = {-1, -1};
    int err_pipe[2] = {-1, -1};
    if (::pipe(out_pipe) != 0 || ::pipe(err_pipe) != 0) {
        log().error(std::string("[roudi] pipe() failed: ") + std::strerror(errno));
        return;
    }

    pid_t pid = ::fork();
    if (pid < 0) {
        log().error(std::string("[roudi] fork() failed: ") + std::strerror(errno));
        ::close(out_pipe[0]); ::close(out_pipe[1]);
        ::close(err_pipe[0]); ::close(err_pipe[1]);
        return;
    }
    if (pid == 0) {
        // Child: wire stdout/stderr to the pipe write ends, close the rest, exec.
        ::dup2(out_pipe[1], STDOUT_FILENO);
        ::dup2(err_pipe[1], STDERR_FILENO);
        ::close(out_pipe[0]); ::close(out_pipe[1]);
        ::close(err_pipe[0]); ::close(err_pipe[1]);
        ::execvp(c_argv[0], c_argv.data());
        // exec failed — report on the (redirected) stderr and die. The parent
        // sees EOF + a non-zero wait status and the supervisor restarts us.
        std::fprintf(stderr, "execvp(%s): %s\n", c_argv[0], std::strerror(errno));
        _exit(127);
    }

    // Parent: keep the read ends (non-blocking), drop the write ends.
    ::close(out_pipe[1]);
    ::close(err_pipe[1]);
    ::fcntl(out_pipe[0], F_SETFL, O_NONBLOCK);
    ::fcntl(err_pipe[0], F_SETFL, O_NONBLOCK);
    child_pid_ = pid;
    out_fd_    = out_pipe[0];
    err_fd_    = err_pipe[0];
    log().info(std::string("[roudi] forked /usr/bin/iox-roudi pid=") + std::to_string(pid));
}

// Pump the child's stdout (→ info) + stderr (→ warn) into our logger until the
// child exits, then return so the supervisor's restart strategy re-forks us.
void RoudiBroker::do_loop() {
    if (child_pid_ < 0) {
        // do_start() failed to fork — back off a beat so a restart storm of
        // this runnable doesn't busy-spin the supervisor.
        for (int i = 0; i < 10 && !stop_requested(); ++i) ::usleep(100 * 1000);
        return;
    }
    std::string out_carry, err_carry;
    bool out_open = true, err_open = true;

    while (!stop_requested() && (out_open || err_open)) {
        struct pollfd fds[2];
        nfds_t nf = 0;
        if (out_open) fds[nf++] = {out_fd_, POLLIN, 0};
        if (err_open) fds[nf++] = {err_fd_, POLLIN, 0};
        int rv = ::poll(fds, nf, 500 /*ms*/);
        if (rv < 0) { if (errno == EINTR) continue; break; }

        for (nfds_t i = 0; i < nf; ++i) {
            if (!(fds[i].revents & (POLLIN | POLLHUP | POLLERR))) continue;
            if (fds[i].fd == out_fd_ && out_open) {
                out_open = drain_fd(out_fd_, out_carry,
                    [this](const std::string& l){ log().info("[roudi] " + l); });
            } else if (fds[i].fd == err_fd_ && err_open) {
                err_open = drain_fd(err_fd_, err_carry,
                    [this](const std::string& l){ log().warn("[roudi] " + l); });
            }
        }

        // Has the child gone? WNOHANG: don't block the pump.
        int status = 0;
        pid_t w = ::waitpid(child_pid_, &status, WNOHANG);
        if (w == child_pid_) {
            if (!out_carry.empty()) log().info("[roudi] " + out_carry);
            if (!err_carry.empty()) log().warn("[roudi] " + err_carry);
            std::string how = WIFSIGNALED(status)
                ? ("signal " + std::to_string(WTERMSIG(status)))
                : ("exit " + std::to_string(WEXITSTATUS(status)));
            log().warn(std::string("[roudi] /usr/bin/iox-roudi terminated (") + how + ")");
            child_pid_ = -1;
            break;   // return → GenRunnable thread ends → supervisor restarts us
        }
    }
}

// Bring the child down: SIGTERM, brief grace, SIGKILL if it lingers; reap.
void RoudiBroker::do_stop() {
    if (child_pid_ > 0) {
        ::kill(child_pid_, SIGTERM);
        for (int i = 0; i < 50; ++i) {   // up to ~5s grace
            if (::waitpid(child_pid_, nullptr, WNOHANG) == child_pid_) { child_pid_ = -1; break; }
            ::usleep(100 * 1000);
        }
        if (child_pid_ > 0) {
            ::kill(child_pid_, SIGKILL);
            ::waitpid(child_pid_, nullptr, 0);
            child_pid_ = -1;
        }
    }
    if (out_fd_ >= 0) { ::close(out_fd_); out_fd_ = -1; }
    if (err_fd_ >= 0) { ::close(err_fd_); err_fd_ = -1; }
}

}  // namespace ara::rds
