// HeartbeatPublisher — periodic node-liveness reports to the supervisor.
//
// Adaptive AUTOSAR's Platform Health Manager owns "alive supervision":
// every reporting application emits a heartbeat at a known cadence; the
// supervisor watchdog kills nodes that miss N consecutive beats.
// This is the publisher half. The watchdog lives in
// platform/supervisor/src/runtime.cpp (check_heartbeats()).
//
// Header-only by design: the runtime library is built with Bazel,
// while supervisor protos (HeartbeatReport.pb.h / SendTimeoutReport.pb.h)
// are generated by the CMake build of platform/supervisor. Inlining
// the implementation here lets daemons consume only the headers they
// need without forcing a Bazel↔CMake dance.
//
// Usage in a daemon's main():
//
//     #include "HeartbeatPublisher.hh"
//     #include "HeartbeatReport.pb.h"        // must be findable via -I
//     #include "SendTimeoutReport.pb.h"
//
//     platform::runtime::HeartbeatPublisher hb("my_node");
//     if (hb.open()) hb.start(/*period_ms=*/1000);
//     // ... rest of node startup ...
//
// open() may return false on hosts without AF_TIPC (no kernel module
// or no permission); the publisher is then inert and the daemon runs
// normally. The supervisor only watchdogs nodes that have ever
// reported, so passive daemons stay exempt.

#pragma once

#include "HeartbeatReport.pb.h"
#include "SendTimeoutReport.pb.h"

#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <linux/tipc.h>
#include <string>
#include <sys/socket.h>
#include <sys/types.h>
#include <thread>
#include <unistd.h>

namespace platform { namespace runtime {

class HeartbeatPublisher {
public:
    // Tags must match platform/supervisor/include/supervisor/tipc_publisher.h.
    static constexpr uint16_t kTagHeartbeat   = 0x0200;
    static constexpr uint16_t kTagSendTimeout = 0x0201;
    static constexpr uint32_t kSupTipcType     = 0x80020001;
    static constexpr uint32_t kSupTipcInstance = 0;

    // Construct with the node's own name (matches the .art `node atomic`
    // identifier so the supervisor's watchdog logs read naturally).
    explicit HeartbeatPublisher(std::string node_name)
        : node_name_(std::move(node_name)),
          self_pid_(::getpid()) {}

    ~HeartbeatPublisher() {
        stop();
        close();
    }

    HeartbeatPublisher(const HeartbeatPublisher&)            = delete;
    HeartbeatPublisher& operator=(const HeartbeatPublisher&) = delete;

    bool open() {
        fd_ = ::socket(AF_TIPC, SOCK_SEQPACKET | SOCK_CLOEXEC, 0);
        if (fd_ < 0) return false;
        struct sockaddr_tipc addr{};
        addr.family                  = AF_TIPC;
        addr.addrtype                = TIPC_ADDR_NAME;
        addr.addr.name.name.type     = kSupTipcType;
        addr.addr.name.name.instance = kSupTipcInstance;
        addr.scope                   = TIPC_NODE_SCOPE;
        if (::connect(fd_, reinterpret_cast<struct sockaddr*>(&addr),
                       sizeof(addr)) < 0) {
            ::close(fd_);
            fd_ = -1;
            return false;
        }
        return true;
    }

    void close() {
        if (fd_ >= 0) ::close(fd_);
        fd_ = -1;
    }

    bool is_open() const { return fd_ >= 0; }

    void send_once() {
        if (fd_ < 0) return;
        ::services::supervisor::HeartbeatReport hb;
        hb.set_node_name(node_name_);
        hb.set_pid(self_pid_);
        hb.set_seq(++seq_);
        hb.set_monotonic_ns(monotonic_ns());
        send_framed(kTagHeartbeat, hb.SerializeAsString());
    }

    void send_timeout(const std::string& caller_node,
                      const std::string& callee_node,
                      const std::string& iface,
                      const std::string& method,
                      uint32_t budget_ms,
                      uint32_t observed_ms) {
        if (fd_ < 0) return;
        ::services::supervisor::SendTimeoutReport rep;
        rep.set_caller_node(caller_node);
        rep.set_callee_node(callee_node);
        rep.set_iface(iface);
        rep.set_method(method);
        rep.set_budget_ms(budget_ms);
        rep.set_observed_ms(observed_ms);
        send_framed(kTagSendTimeout, rep.SerializeAsString());
    }

    void start(uint32_t period_ms) {
        if (fd_ < 0) return;
        if (running_.exchange(true)) return;
        period_ms_ = period_ms;
        thread_ = std::thread([this] {
            while (running_.load()) {
                send_once();
                std::this_thread::sleep_for(
                    std::chrono::milliseconds(period_ms_));
            }
        });
    }

    void stop() {
        if (!running_.exchange(false)) return;
        if (thread_.joinable()) thread_.join();
    }

    uint64_t seq() const { return seq_.load(); }

private:
    void send_framed(uint16_t tag, const std::string& payload) {
        if (fd_ < 0) return;
        std::string buf;
        buf.resize(2 + payload.size());
        buf[0] = static_cast<char>((tag >> 8) & 0xff);
        buf[1] = static_cast<char>(tag & 0xff);
        std::memcpy(&buf[2], payload.data(), payload.size());
        (void)::send(fd_, buf.data(), buf.size(), MSG_NOSIGNAL);
    }

    static uint64_t monotonic_ns() {
        struct timespec ts;
        clock_gettime(CLOCK_MONOTONIC, &ts);
        return static_cast<uint64_t>(ts.tv_sec) * 1'000'000'000ull +
               static_cast<uint64_t>(ts.tv_nsec);
    }

    std::string             node_name_;
    int                     fd_       = -1;
    std::atomic<uint64_t>   seq_      {0};
    pid_t                   self_pid_ = -1;

    std::atomic<bool>       running_  {false};
    std::thread             thread_;
    uint32_t                period_ms_ = 0;
};

}}  // namespace platform::runtime
