// theia::runtime::ParamsConfig — the static-deploy params singleton.
//
// The STATIC half of the params/config lifecycle (the dynamic, observable half
// is services/per + ConfigUpdated). params are deployment knobs: read ONCE at
// process boot from a generated per-FC JSON, then immutable — a change requires
// a restart.
//
// Layout (one file per FC, generated by `artheia` params emitter, staged at
// <ROOT>/<machine>/config/<fc>.json):
//
//   { "package": "...", "nodes": { "<prototype>": { "<param>": <value>, ... } } }
//
// Each section is keyed by the node's PROTOTYPE name — which is exactly what a
// node's kNodeName holds — so a node reads its own params with:
//
//   auto cfg = ::theia::runtime::get_config();          // process singleton
//   uint32_t period = cfg.node(kNodeName).u32("period_ms", 1000);
//   std::string ep  = cfg.node(kNodeName).str("etcd_endpoint", "127.0.0.1:2379");
//
// Read-once + default-on-miss: an absent file, section, or key falls back to
// the caller-supplied default, so a node always boots with sane values even if
// the JSON wasn't staged. The generated main.cc calls init_config() early in
// boot; nodes pull values in their ctor / init().
//
// Tiny hand-rolled JSON reader (flat string/number/bool values per section) so
// the runtime pulls in no JSON dependency. Not a general JSON parser — it reads
// exactly the shape the params emitter produces.

#pragma once

#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <map>
#include <mutex>
#include <sstream>
#include <string>

namespace theia {
namespace runtime {

// A read-only view of one node's params section: typed getters with a default.
class NodeParams {
public:
    explicit NodeParams(const std::map<std::string, std::string>* kv) : kv_(kv) {}

    bool has(const std::string& key) const {
        return kv_ && kv_->count(key) != 0;
    }
    std::string str(const std::string& key, const std::string& dflt = "") const {
        auto* v = find(key);
        return v ? *v : dflt;
    }
    uint32_t u32(const std::string& key, uint32_t dflt = 0) const {
        auto* v = find(key);
        return v ? static_cast<uint32_t>(std::strtoul(v->c_str(), nullptr, 0))
                 : dflt;
    }
    uint64_t u64(const std::string& key, uint64_t dflt = 0) const {
        auto* v = find(key);
        return v ? static_cast<uint64_t>(std::strtoull(v->c_str(), nullptr, 0))
                 : dflt;
    }
    int32_t i32(const std::string& key, int32_t dflt = 0) const {
        auto* v = find(key);
        return v ? static_cast<int32_t>(std::strtol(v->c_str(), nullptr, 0))
                 : dflt;
    }
    double f64(const std::string& key, double dflt = 0.0) const {
        auto* v = find(key);
        return v ? std::strtod(v->c_str(), nullptr) : dflt;
    }
    bool boolean(const std::string& key, bool dflt = false) const {
        auto* v = find(key);
        if (!v) return dflt;
        return *v == "true" || *v == "1";
    }

private:
    const std::string* find(const std::string& key) const {
        if (!kv_) return nullptr;
        auto it = kv_->find(key);
        return it == kv_->end() ? nullptr : &it->second;
    }
    const std::map<std::string, std::string>* kv_;
};

class ParamsConfig {
public:
    // Process-wide singleton.
    static ParamsConfig& instance() {
        static ParamsConfig s;
        return s;
    }

    // Load the per-FC JSON ONCE. Safe to call repeatedly (only the first load
    // takes effect); a missing/unreadable file leaves the config empty (every
    // lookup then returns its default). Returns true if a file was parsed.
    bool load(const std::string& path) {
        std::lock_guard<std::mutex> lk(mu_);
        if (loaded_) return parsed_;
        loaded_ = true;
        std::ifstream f(path);
        if (!f) return (parsed_ = false);
        std::stringstream ss; ss << f.rdbuf();
        parse(ss.str());
        return (parsed_ = true);
    }

    // The params view for one node (by its kNodeName / prototype name). Returns
    // an empty view (all-defaults) when the section is absent.
    NodeParams node(const std::string& node_name) const {
        std::lock_guard<std::mutex> lk(const_cast<std::mutex&>(mu_));
        auto it = nodes_.find(node_name);
        return NodeParams(it == nodes_.end() ? nullptr : &it->second);
    }

private:
    ParamsConfig() = default;

    // Parse the exact shape the params emitter writes:
    //   { "package": "...", "nodes": { "<node>": { "<k>": <v>, ... }, ... } }
    // Flat values only (string | number | bool). We scan structurally rather
    // than recursively: find the "nodes" object, then per-node sub-objects, and
    // store every key as a STRING (the typed getters coerce on read).
    void parse(const std::string& s) {
        std::size_t np = s.find("\"nodes\"");
        if (np == std::string::npos) return;
        std::size_t obj = s.find('{', np);
        if (obj == std::string::npos) return;
        // Walk node sections inside the "nodes" object until its matching close.
        std::size_t depth = 1;       // we're inside "nodes" { ... }
        std::size_t i = obj + 1;
        while (i < s.size() && depth > 0) {
            char c = s[i];
            if (c == '{') { ++depth; ++i; continue; }
            if (c == '}') { --depth; ++i; continue; }
            if (c == '"' && depth == 1) {
                // A node-section key at depth 1: "<node>": { ... }
                std::size_t k1 = i + 1, k2 = s.find('"', k1);
                std::string node = s.substr(k1, k2 - k1);
                std::size_t so = s.find('{', k2);
                std::size_t se = match_brace(s, so);
                parse_section(node, s.substr(so + 1, se - so - 1));
                i = se + 1;
                continue;
            }
            ++i;
        }
    }

    void parse_section(const std::string& node, const std::string& body) {
        auto& kv = nodes_[node];
        std::size_t i = 0;
        while (i < body.size()) {
            std::size_t k1 = body.find('"', i);
            if (k1 == std::string::npos) break;
            std::size_t k2 = body.find('"', k1 + 1);
            if (k2 == std::string::npos) break;
            std::string key = body.substr(k1 + 1, k2 - k1 - 1);
            std::size_t colon = body.find(':', k2);
            if (colon == std::string::npos) break;
            // Value: a quoted string, or a bare token (number / true / false).
            std::size_t v = colon + 1;
            while (v < body.size() && (body[v] == ' ' || body[v] == '\t' ||
                                       body[v] == '\n' || body[v] == '\r')) ++v;
            std::string val;
            std::size_t after;
            if (v < body.size() && body[v] == '"') {
                std::size_t vq = body.find('"', v + 1);
                val = body.substr(v + 1, vq - v - 1);
                after = vq + 1;
            } else {
                std::size_t ve = v;
                while (ve < body.size() && body[ve] != ',' && body[ve] != '}' &&
                       body[ve] != '\n' && body[ve] != '\r') ++ve;
                val = body.substr(v, ve - v);
                // trim trailing whitespace
                while (!val.empty() && (val.back() == ' ' || val.back() == '\t'))
                    val.pop_back();
                after = ve;
            }
            kv[key] = val;
            i = after;
        }
    }

    static std::size_t match_brace(const std::string& s, std::size_t open) {
        std::size_t depth = 0;
        for (std::size_t i = open; i < s.size(); ++i) {
            if (s[i] == '{') ++depth;
            else if (s[i] == '}') { if (--depth == 0) return i; }
        }
        return s.size();
    }

    mutable std::mutex mu_;
    bool loaded_ = false;
    bool parsed_ = false;
    std::map<std::string, std::map<std::string, std::string>> nodes_;
};

// ---- Free-function API the generated main.cc + node code uses ---------------

// Resolve the per-PROCESS config path and load it once. main.cc calls this early
// in boot, passing its FC leaf name (the .art package leaf) as the FALLBACK.
// Filename precedence:
//   $THEIA_PROCESS_NAME.json — the SUPERVISED case. serialize-manifest stages
//     config per PROCESS (config/<process>.json, e.g. app.json — one composition
//     binary can run as several processes, each with its own params), and the
//     supervisor exports THEIA_PROCESS_NAME to every child it forks. The compiled
//     fc leaf CANNOT know the process name (a deploy-time identity) — keying the
//     file on the leaf made every supervised app's params silently default (the
//     staged file was app.json; the binary looked for <leaf>.json; services never
//     noticed because their leaf == process name, e.g. sm/sm.json).
//   <fc_name>.json           — bare/unsupervised runs (host dev, tests).
// Path precedence (unchanged):
//   $THEIA_CONFIG  (full path override, for tests)         -> use verbatim
//   $THEIA_CONFIG_DIR/<name>.json                          -> dir + name
//   ./config/<name>.json                                   -> CWD default
// A missing file is fine (every lookup returns its default).
//
// THEIA_CONFIG_DIR is "config" (RELATIVE) in the executor env. The supervisor
// forks each child with CWD = THEIA_INSTALL_DIR = $THEIA_ROOT_DIR/current (the
// active release — day-1 the runtime, day-2/3 an SWP release; two-plane OTA, see
// docs/design/two-plane-ota.md). So a relative "config" resolves to
// current/config/ — the ACTIVE release's config, which follows a `current` flip.
// This is the model: EVERYTHING is read through `current` (executor + per-FC
// config), so a rollout/rollback is a single symlink flip. A relative dir stays
// relative to CWD (current); an absolute THEIA_CONFIG_DIR / THEIA_CONFIG wins.
inline bool init_config(const std::string& fc_name) {
    if (const char* full = std::getenv("THEIA_CONFIG")) {
        return ParamsConfig::instance().load(full);
    }
    std::string name = fc_name;
    if (const char* pn = std::getenv("THEIA_PROCESS_NAME"); pn && *pn)
        name = pn;                       // supervised: the per-process file wins
    std::string dir = "config";
    if (const char* d = std::getenv("THEIA_CONFIG_DIR")) dir = d;
    // A relative dir resolves against CWD (= current, the active release). Do NOT
    // anchor to $THEIA_ROOT_DIR — that pinned config to a shared flat dir that an
    // SWP flip couldn't change. Absolute dir is used verbatim.
    return ParamsConfig::instance().load(dir + "/" + name + ".json");
}

// The process config singleton — nodes call get_config().node(kNodeName)....
inline ParamsConfig& get_config() { return ParamsConfig::instance(); }

// Resolve the directory holding an FC's static DATA resources (LUTs, tables —
// baked into the FC's deb at /opt/theia/share/<fc>/data by `theia dist` from the
// manifest's ProcessLayer.resources). Returns "<base>/<fc>/data" WITHOUT a
// trailing slash; append "/<file>" to open a resource.
//
// Resolution mirrors init_config (everything reads through `current`, so an OTA
// flip/rollback swaps the data with the code):
//   $THEIA_SHARE_DIR/<fc>/data     (absolute override — deb install / tests)
//   ./share/<fc>/data              (relative default; CWD = current, the active
//                                   release — a relative dir follows the flip)
// A deb install exports THEIA_SHARE_DIR=/opt/theia/share; a supervised release
// leaves it unset and the relative default resolves under `current`.
inline std::string share_dir(const std::string& fc_name) {
    std::string base = "share";
    if (const char* d = std::getenv("THEIA_SHARE_DIR"); d && *d) base = d;
    return base + "/" + fc_name + "/data";
}

// Resolve the caller's OWN share dir. The share path is keyed by the manifest
// PROCESS name (the same name theia dist bakes under /opt/theia/share/<proc>/data
// and that the supervisor exports as THEIA_PROCESS_NAME) — NOT the node's
// kNodeName. A supervised process reads $THEIA_PROCESS_NAME; unset (a bare run)
// falls back to the passed default (typically the FC/prototype name).
inline std::string share_dir_self(const std::string& fallback_name) {
    if (const char* pn = std::getenv("THEIA_PROCESS_NAME"); pn && *pn)
        return share_dir(pn);
    return share_dir(fallback_name);
}

}  // namespace runtime
}  // namespace theia
