// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/services/fw/component.art
//
// FC-wide inbound RemoteCodec specializations (#387).
//
// register_call / register_cast on a reporting node's config service
// need a RemoteCodec<T> for every inbound type. This header declares
// ONE THEIA_DECLARE_REMOTE_CODEC per inbound (receiver-port data /
// server-op req+rep) type, deduplicated across EVERY node in the FC.
//
// It lives in one header — not per-node — so that when two nodes in
// the same FC share an inbound type (e.g. com's ComDaemon and the
// test ProbeDaemon both take ComEmpty), the codec specialization is
// declared exactly once even though main.cc includes both node
// headers. Each node header #includes this (guarded by #pragma once),
// so a node header used standalone still has its codecs.
//
// A codec keys its service_id on the proto type name in the message's
// DEFINING package — so an inbound type imported from another package
// (e.g. a PSP bus PDU) declares its codec under that package's name,
// matching the sender. The #include set below covers every defining
// package an inbound type comes from.

#pragma once

#include "RemoteCodec.hh"   // THEIA_DECLARE_REMOTE_CODEC
#include "system/services/fw/fw.pb.h"

#include "system/services/phm/phm.pb.h"



THEIA_DECLARE_REMOTE_CODEC(system_services_fw_FwStatusReq)
THEIA_DECLARE_REMOTE_CODEC(system_services_fw_FwStatusMsg)
THEIA_DECLARE_REMOTE_CODEC(system_services_fw_ReloadReq)
THEIA_DECLARE_REMOTE_CODEC(system_services_fw_ReloadReply)
THEIA_DECLARE_REMOTE_CODEC(system_services_phm_FcHealthReport)

// FC-wide enum aliases — the enum TYPE and each VALUE inside the FC namespace, so
// impl code writes the readable `FwState` / `FW_UNKNOWN`
// instead of nanopb's double-prefixed name
// (system_services_fw_<Enum>_<Enum>_<VALUE>). Emitted ONCE here (this header
// is #pragma once + included by every node header) — NOT per-node, so two node
// headers in one TU don't redefine them.
namespace ara::fw {
using FwState = system_services_fw_FwState;
inline constexpr FwState FW_UNKNOWN = system_services_fw_FwState_FwState_FW_UNKNOWN;
inline constexpr FwState FW_APPLIED = system_services_fw_FwState_FwState_FW_APPLIED;
inline constexpr FwState FW_DEGRADED = system_services_fw_FwState_FwState_FW_DEGRADED;
inline constexpr FwState FW_DISABLED = system_services_fw_FwState_FwState_FW_DISABLED;
}  // namespace ara::fw
