// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: system/apps/component.art
//
// Lib slice — message wiring + class declaration for ONE node. An FC
// may declare several nodes; each gets its own <Node>.hh (this file).
// Regenerated on every gen-app run. User edits land in
// impl/DemoFsmGate_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "NodeRef.hh"   // cast(self, msg, TipcAddr) — pg broadcast fan-out
#include "PgClient.hh"  // OTP-pg broadcast fan-out (sender-port broadcast_*)
#include "Log.hh"      // sibling — per-FC ContextLogger + kLogTag
#include "apps_codecs.hh"   // FC-wide inbound RemoteCodecs (#387)
#include "system/apps/apps.pb.h"
// State held by the daemon — FIELDS are APP-OWNED (node behaviour, not
// derived from the .art), so the struct lives in a WRITE-ONCE impl header
// (seeded empty, never clobbered without --force) that the user fills in.
// Included at GLOBAL scope (the header opens its own `namespace
// system_apps`) so it isn't nested under this file's
// namespace block — bound as the GenServer State type below.
#include "impl/DemoFsmGate_state.hh"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <map>
#include <set>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

namespace system_apps {


// ---- DemoFsmGate ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (system_apps_*); aliasing them here keeps callers'
// signatures readable.
using DemoStart = system_apps_DemoStart;
using DemoFinish = system_apps_DemoFinish;
using DemoReset = system_apps_DemoReset;

// statem block declared in .art — see the corresponding StateMBase
// header produced by `artheia gen-cpp-stubs`. The daemon below
// derives from DemoFsmGateStateMBase (gen_statem-shaped); without
// statem it would derive directly from GenServer.
//
// (The StateMBase emission is gen-cpp-stubs's job, not gen-app's;
// for FCs with statem blocks, run gen-cpp-stubs alongside.)

// (The in-process subscriber-list / gen_event pattern is RETIRED — OTP
// deprecated gen_event. A sender-port broadcast_*() is PURE PG multicast now;
// consumers pg_join the message type's group. No std::function subscriber
// typedef, no subscribe_*/unsubscribe_*, no per-node _subs_ list.)

class DemoFsmGate : public ::theia::runtime::GenServer<DemoFsmGate, DemoFsmGateState> {
public:
    static constexpr const char* kNodeName = "demo_gate";
    static constexpr uint32_t kTipcType     = 0xd0010007u;
    static constexpr uint32_t kTipcInstance = 0u;

    // AUTOSAR Reporting / Non-Reporting flag (per .art `reporting`
    // field). When true, this node sends HeartbeatReport, the
    // supervisor watchdogs it, and the supervisor can push trace
    // config to it via the methods below.
    static constexpr bool kReporting = true;


    // Bring the framework's config-service handler
    // (handle_cast(LogLevelPush)) into scope (#386). A Derived
    // handle_cast for any port message would otherwise HIDE the base
    // overload by name, so register_cast<LogLevelPush> wouldn't
    // resolve. This using-decl keeps both visible; overload resolution
    // then picks the right one per message type.
    using ::theia::runtime::GenServer<DemoFsmGate, DemoFsmGateState>::handle_cast;

    // ---- Trace config (reporting=true only) -----------------------
    //
    // Per #355, the per-message-type filter lives in the process-wide
    // Tracer (see platform/runtime/Tracer.hh). These methods are thin
    // delegations so the supervisor / NodeTraceCtl wire path has a
    // stable in-class API while the actual storage stays in one place.
    //
    // The supervisor (#361) pushes (msg_type, enabled) pairs by
    // calling trace_enable() on receipt of an ApplyConfig RPC. emit()
    // consults the same filter inside Tracer; non-listed types are
    // dropped on the disabled fast path.
    void trace_enable(const char* msg_type, bool enabled) {
        ::theia::runtime::tracer_for(kNodeName).trace_enable(
            msg_type, enabled);
    }
    bool trace_enabled(const char* msg_type) const {
        return ::theia::runtime::tracer_for(kNodeName)
            .trace_filter_passes(msg_type);
    }
    void trace_clear_all() {
        ::theia::runtime::tracer_for(kNodeName).trace_clear_all();
    }

    // ---- process groups (pg): MANUAL pub/sub, the node decides WHEN ------
    //
    // OTP pg:join/leave shape over TIPC name-sequence MULTICAST. A group's
    // identity is its message TYPE T (group name = msg_type_name<T>(), a
    // generated .art-derived wire constant — no strings, no collision). The
    // OTP `pg` shape. The SUPERVISOR is the namespace authority + the membership
    // monitor. A CONSUMER pg_join<T>()s (the supervisor allocates {group_type,
    // unique instance}; received frames flow into this node's handle_cast via its
    // demux). A PRODUCER pg_watch<T>()s (OTP pg:monitor) — gets the current member
    // list AND a PgMembership push on every join/leave/reap; broadcast_*() then
    // loops the WATCHED member list and casts to each (OTP `[Pid ! Msg || Pid <-
    // pg:get_members]`). The producer impl keeps CONTROL: it can pg_members<T>()
    // to see who's listening (empty → skip work, e.g. logcat stop-tailing) or
    // branch on its own state. JOIN/WATCH/BROADCAST are DELIBERATE node calls.
    //   pg_join<T>()    — consume T's group (deliver to this node's handle_cast).
    //   pg_watch<T>()   — monitor T's membership before broadcasting (producer).
    //   pg_members<T>() — this producer's current view of T's member list.
    //   pg_leave<T>()   — stop consuming T (frees the instance).
    //   broadcast_<port>_<data>(msg) — cast to each watched member of T's group.
    // pg_attach() is called once by main.cc with this node's name + demux binding
    // + its bound addr (the watcher address the supervisor pushes PgMembership to).
    void pg_attach(const char* node_name, ::theia::runtime::NodeBinding* b,
                   uint32_t self_type = 0, uint32_t self_instance = 0) {
        pg_.attach(node_name, b);
        pg_self_type_ = self_type; pg_self_instance_ = self_instance;
    }
    template <typename T> ::theia::runtime::PgClient::Group pg_join() {
        return pg_.join<T>();
    }
    // OTP pg:monitor — watch T's group (idempotent; watches once). on_change fires
    // on every membership change so the impl can react ({pg_join}/{pg_leave}).
    template <typename T>
    ::theia::runtime::PgClient::Group pg_watch(std::function<void()> on_change = {}) {
        uint16_t _sid = ::theia::runtime::RemoteCodec<T>::service_id;
        if (!pg_watched_.count(_sid)) {
            pg_watched_.insert(_sid);
            return pg_.watch<T>(pg_self_type_, pg_self_instance_, std::move(on_change));
        }
        return {true, 0, 0};
    }
    template <typename T>
    std::vector<::theia::runtime::PgClient::Member> pg_members() {
        return pg_.members<T>();
    }
    template <typename T> void pg_leave() { pg_.leave<T>(); }
    // Escape hatch for a node that is ITSELF the allocator (the supervisor): it
    // resolves the group type LOCALLY (engine registry) and nameseq-multicasts,
    // never TIPC-self-CALLing watch/resolve. Normal FCs use broadcast_*().
    template <typename T>
    void pg_broadcast(uint32_t group_type, const T& msg) {
        uint8_t _buf[8192];
        pb_ostream_t _os = pb_ostream_from_buffer(_buf, sizeof(_buf));
        if (!pb_encode(&_os, ::theia::runtime::RemoteCodec<T>::fields(), &msg))
            return;
        pg_.broadcast<T>(group_type, _buf,
                         static_cast<uint16_t>(_os.bytes_written));
    }


    // ---- GenServer plumbing: terminate default
    //
    // terminate keeps an inline no-op default; impl may shadow it.
    //
    // There is NO handle_info(const InfoMsg&) clause: the wire-info path
    // was removed. An inbound TIPC frame that matched no register_cast/
    // register_call is dropped with a CRITICAL log in TipcMux — never
    // delivered as untyped bytes. Cross-node traffic is exclusively typed
    // cast/call. The only handle_info is the LOCAL string clause below
    // (post_info / self-tick).
    void terminate(const char* /*reason*/, DemoFsmGateState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl
    //
    // Deduplicated by message type: if two ports share the same
    // interface (e.g. ctl_tdb + ctl_com both providing
    // TraceControl) the handler signature is identical and only
    // gets emitted once. handle_call/handle_cast dispatch by
    // request type, not by port.

    void handle_cast(const DemoStart& msg, DemoFsmGateState& s);

    void handle_cast(const DemoFinish& msg, DemoFsmGateState& s);

    void handle_cast(const DemoReset& msg, DemoFsmGateState& s);



    // ---- OTP init/1 — body in impl (DemoFsmGate_handlers.cc) ----------
    //
    // Called ONCE by the runtime on this node's thread after start(),
    // before the first mailbox item (GenServer::dispatch_init_). A
    // self-driving node bootstraps its work loop here (e.g.
    // ::theia::runtime::post_info(*this, "tick")); a passive node leaves it
    // empty. Emitted for every node so the hook is always visible.
    void init(DemoFsmGateState& s);

    // ---- string handle_info — body in impl ----------------------------
    //
    // The post_info()/send_after() string-message path (timer loops,
    // internal ticks). LOCAL-ONLY opaque signal — never crosses the wire.
    // Declared so a node can override the GenServer base no-op in its impl.
    void handle_info(const char* info, DemoFsmGateState& s);

    // ---- send helpers — bodies in impl (the broadcast fan-out)


private:
    // The node's process-group client: owns the recv thread for joined groups, the
    // watch cache, and the supervisor CALL channel. Attached via pg_attach().
    ::theia::runtime::PgClient pg_;
    std::set<uint16_t> pg_watched_;          // groups this node already pg_watch'd
    uint32_t pg_self_type_{0};               // this node's bound addr (watcher addr)
    uint32_t pg_self_instance_{0};
};

// Broadcast fan-out — OTP `[Pid ! Msg || Pid <- pg:get_members(group)]`. Defined
// in the lib slice (auto-generated); the user touches handle_*/init in impl.




}  // namespace system_apps


