/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ucm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(services_services_ucm_UcmRequest, services_services_ucm_UcmRequest, AUTO)


PB_BIND(services_services_ucm_UcmReply, services_services_ucm_UcmReply, AUTO)


PB_BIND(services_services_ucm_UpdateModeRequest, services_services_ucm_UpdateModeRequest, AUTO)



