// AUTO-GENERATED by `artheia gen-app --kind fc` — DO NOT EDIT.
// source: services/log/system/package.art
//
// Lib slice — message wiring + class declaration. Regenerated on
// every gen-app run. User edits land in impl/TraceCollector_handlers.cc.

#pragma once

#include "GenServer.hh"
#include "system/services/log/log.pb.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <mutex>
#include <utility>
#include <vector>

namespace ara::log {


// ---- TraceCollector ----------------------------------------------------------

// Local-namespace aliases over the nanopb C structs. The nanopb
// generator prefixes types with the libc-safe proto package
// (services_services_log_*); aliasing them here keeps callers'
// signatures readable.
using TraceConfigRequest = services_services_log_TraceConfigRequest;
using TraceEmpty = services_services_log_TraceEmpty;
using TraceRecord = services_services_log_TraceRecord;
using TraceConfigDecision = services_services_log_TraceConfigDecision;



// One subscriber on every sender-port broadcast. Free-function so
// the daemon doesn't care whether delivery is in-process, TIPC, or
// gRPC. Subscribers MUST be best-effort.
using Stream_outRecSubscriber =
    std::function<void(const TraceRecord&)>;


// State held by the daemon — kept minimal; per-handler scratch
// goes in impl. Future iterations push more here once the FC has
// real persistent state needs.
struct TraceCollectorState {
    
    int  reserved{0};
};

class TraceCollector : public demo::runtime::GenServer<TraceCollector, TraceCollectorState> {
public:
    static constexpr const char* kNodeName = "trace_collector";
    static constexpr uint32_t kTipcType     = 0x80010013u;
    static constexpr uint32_t kTipcInstance = 0u;

    // ---- Subscriber registration ----------------------------------

    // stream_out.rec broadcast subscribers.
    uint32_t subscribe_stream_out_rec(
        Stream_outRecSubscriber s);
    void     unsubscribe_stream_out_rec(uint32_t id);


    // ---- GenServer plumbing: handle_info + terminate defaults
    //
    // GenServer's dispatch_info_ unconditionally calls
    // Derived::handle_info; the base also looks for terminate. We
    // provide no-op defaults inline; impl can shadow either with
    // its own overload if the daemon needs them.
    void handle_info(const char* /*info*/, TraceCollectorState& /*s*/) {}
    void terminate(const char* /*reason*/, TraceCollectorState& /*s*/) noexcept {}

    // ---- handle_cast / handle_call — declared here, body in impl

    TraceEmpty handle_call(const TraceConfigRequest& req,
                                            TraceCollectorState& s);

    TraceEmpty handle_call(const TraceConfigRequest& req,
                                            TraceCollectorState& s);

    void handle_cast(const TraceRecord& msg, TraceCollectorState& s);


    // ---- send helpers — bodies in impl (the broadcast fan-out)

    void broadcast_stream_out_rec(const TraceRecord& msg);


private:

    struct Stream_outRecEntry {
        uint32_t id;
        Stream_outRecSubscriber fn;
    };
    std::mutex stream_out_rec_mu_;
    uint32_t stream_out_rec_next_id_{1};
    std::vector<Stream_outRecEntry>
        stream_out_rec_subs_;

};

// Subscriber registration — defined in the lib slice (not impl) so
// it stays auto-generated. The user touches handle_* in impl.

inline uint32_t TraceCollector::subscribe_stream_out_rec(
        Stream_outRecSubscriber s) {
    std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
    uint32_t id = stream_out_rec_next_id_++;
    stream_out_rec_subs_.push_back({id, std::move(s)});
    return id;
}

inline void TraceCollector::unsubscribe_stream_out_rec(uint32_t id) {
    std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
    auto& v = stream_out_rec_subs_;
    v.erase(std::remove_if(v.begin(), v.end(),
              [id](const auto& e) { return e.id == id; }), v.end());
}

inline void TraceCollector::broadcast_stream_out_rec(const TraceRecord& msg) {
    std::vector<Stream_outRecEntry> snap;
    {
        std::lock_guard<std::mutex> lk(stream_out_rec_mu_);
        snap = stream_out_rec_subs_;
    }
    for (const auto& e : snap) {
        try { e.fn(msg); }
        catch (...) {
            std::fprintf(stderr,
                "[%s] subscriber %u threw on stream_out.rec — dropping\n",
                kNodeName, e.id);
        }
    }
}




}  // namespace ara::log
